antvis/G2Plot

src/plots/gauge/index.ts
src/plots/gauge/theme.ts
src/plots/liquid/index.ts
src/plots/liquid/theme.ts
src/theme/default.ts

fix: move plot theme to plot src

---

package.json
src/plots/line/applyResponsive/axis.ts
tsconfig.json

fix: unit test pass

---

.travis.yml

[WIP]feat: enable ci

---

src/interface/config.ts
src/theme/ali-dark.ts
src/theme/ali-light.ts

ali橙色系两套主题调整。bx 主题放在bizcharts中。

fix: ali系 两套主题调整

---

__tests__/unit/pie.spec.js
src/plots/ring/component/annotation/centralText_template.ts
src/plots/ring/index.ts

Fix issue 29

---

__tests__/unit/connectedArea-spec.js
package.json
src/base/controller/padding.ts
src/base/controller/state.ts
src/components/connectedArea.ts
src/geoms/point/guide.ts
src/plots/radar/index.ts
src/plots/stack-column/index.ts

为堆叠柱状图和堆叠条形图添加可交互的connected-area组件
todo list:

add connectedArea component

---

__tests__/unit/stack-area.spec.js
package.json
src/components/connectedArea.ts
src/plots/stack-area/component/label.ts
src/plots/stack-area/index.ts

WIP: add area label

---

__tests__/unit/gauge-spec.js
__tests__/unit/liquid-spec.js
package.json

feat(plot): update liquid & gauge unit test.

---

__tests__/unit/stackArea-spec.js

完善、增加堆叠面积图的测试用例

---

src/components/axis/parser.ts
src/index.ts
src/interface/config.ts
src/util/scale.ts

- axis grid配置项支持callback方式
- axis minLimit/maxLimit参数透传

fix: support axis grid function config

---

demos/column-slider.html
src/interface/config.ts
src/layers/SliderLayer.ts
src/plots/column/index.ts
src/plots/line/index.ts
src/plots/stack-area/component/label/areaLabel.ts
tsconfig.json

- 移除tsconfig baseUrl
- 柱形图支持缩略轴

feat: support slider for column plot

---

package.json
src/plots/stack-area/component/label/lineLabel.ts

- 添加tslib依赖
- 使用@antv/util代替lodash

修复lodash和tslib依赖缺失问题

---

src/base/Plot.ts

获取顶层g2 plot 实例的接口

---

package.json
src/base/Layer.ts
src/base/Plot.ts
src/base/ViewLayer.ts
src/base/controller/canvas.ts
src/base/controller/padding.ts
src/interface/config.ts
src/plots/area/AreaLayer.ts
src/plots/bar/BarLayer.ts
src/plots/column/ColumnLayer.ts
src/plots/group-column/GroupColumnLayer.ts
src/plots/line/LineLayer.ts
src/plots/pie/PieLayer.ts
src/plots/radar/RadarLayer.ts
src/plots/ring/RingLayer.ts
src/tinyPlots/progress/ProgressLayer.ts
src/tinyPlots/ring-progress/RingProgressLayer.ts
src/tinyPlots/tiny-area/TinyAreaLayer.ts
src/tinyPlots/tiny-column/TinyColumnLayer.ts
src/tinyPlots/tiny-line/TinyLineLayer.ts
src/util/scale.ts

如题；
特殊说明：因event-emit  函数名_events  与layer 方法重名。遂修改layer _events 方法名为 _parserEvent()

axis 增加scale type ；fix forceFit 失效；新增 layer afterrender的勾子；

---

src/interaction/ScrollBarInteraction.ts

fix: prevent scrollbar scroll to negative ratio

---

__tests__/unit/histogram-spec.js
demos/histogram.html
package.json
src/base/ViewLayer.ts
src/index.ts
src/plots/histogram/index.ts
src/plots/histogram/layer.ts

设计文档： https://yuque.antfin-inc.com/antv/g2-4/zgfv42

add histogram

---

src/base/ViewLayer.ts

fix: 事件解析bug

---

src/base/Plot.ts
src/base/controller/canvas.ts

refactor(canvas-controller): refactor & bugfix

---

__tests__/unit/pie-spec.js
src/base/ViewLayer.ts
src/interface/config.ts
src/plots/area/AreaLayer.ts
src/plots/bar/BarLayer.ts

几个小问题一起修
* title & description无法用visible配置项控制显示
* areaPlot的label设visible为false时报错
* barPlot的x、y坐标轴autoRotateTitle配置转置

 title & description visibility 

---

package.json
src/interaction/ScrollBarInteraction.ts
src/interaction/SliderInteraction.ts
src/interaction/helper/data-range.ts

1. 更新gui依赖；修复scrolbar在碰到最短滑条的情况下不能滑都最右/最下的bug
2. 修复slider和scrollbar在有细分字段情况的数据切分问题

fix: slider和scrollbar更新

---

src/base/view-layer.ts

feat: 允许自定义Tooltip的样式等选项

---

examples/line/basic/demo/area.js
examples/pie/basic/demo/area.js

json 路径有点问题，一级分类的演示的直接 `data/xxx.json`，二级分类的演示的需要 `../data/xxx.json` 这样写。

docs: fix example data url

---

src/base/plot.ts
src/geoms/line/main.ts

* 修复layer重构后，plot层的updateConfig失效
* 修复折线图线宽配置失效

fix update config error

---

__tests__/unit/area-spec.js
__tests__/unit/groupColumn-spec.js
__tests__/unit/line-spec.js
src/base/global.ts
src/base/plot.ts
src/base/view-layer.ts
src/plots/area/layer.ts
src/plots/line/index.ts
src/plots/line/layer.ts
src/plots/liquid/layer.ts

feat(default-cfg): update defaultCfg of area & stack-area & line

---

__tests__/unit/title-desc-spec.ts
demos/area-basic.ts
demos/tsconfig.json
package.json
scripts/demo-route.js
src/base/controller/padding.ts
src/base/view-layer.ts
tsconfig.json

fix  #199 
修复把title或者desc的visible 从true变为false 不会重新计算布局，不会销毁title/desc市里的 bug

Title desc rerender

---

src/components/description.ts

1. 如果title的第一个字符就比width宽，就会出现死循环，修改为如果第一个字符就比width宽则原样返回
2. 优化代码逻辑

fix: title/desc 可能出现死循环

---

src/base/view-layer.ts
src/plots/bar/layer.ts
src/plots/column/component/label/column-label.ts
src/plots/column/layer.ts
src/plots/group-bar/layer.ts
src/plots/group-column/layer.ts
src/plots/stack-bar/layer.ts
src/plots/stack-column/layer.ts

feat: 更新柱条系列图形默认配置项

---

src/base/layer.ts
src/base/view-layer.ts

@paleface001 @hustcc  updateConfig更新size的确有问题，在这里修复了

fix: updateConfig size 更新修复

---

__tests__/unit/utils-spec.ts
src/base/controller/padding.ts
src/base/controller/theme.ts
src/base/view-layer.ts
src/components/axis/parser.ts
src/components/description.ts
src/components/factory.ts
src/interface/config.ts
src/plots/area/layer.ts
src/plots/bar/layer.ts
src/theme/default.ts
src/theme/utils.ts
src/util/common.ts

title和description在为空 或者其text为空的情况下不渲染
如果没有title description使用 title的上边距，保证上padding一致
修复axis 修改line tickLine的无效的bug
bar  和 area的layer使用Viewlayer的axis逻辑

修复axis，以及title/ desc的bug

---

__tests__/unit/title-desc-spec.ts
src/components/description.ts
src/theme/default.ts

fix: title and description wrap bug

---

__tests__/unit/title-desc-spec.ts
src/components/description.ts

fix: 修复标题和description换行的bug

---

__tests__/unit/theme/index-spec.ts
src/base/controller/canvas.ts
src/base/controller/theme.ts
src/base/plot.ts
src/base/view-layer.ts
src/components/axis/parser.ts
src/components/label/parser.ts
src/theme/dark.ts
src/theme/global.ts
src/theme/theme.ts

feat: 支持dark主题

---

docs/manual/getting-started.zh.md
docs/manual/plots/area.zh.md
docs/manual/plots/bar.zh.md
docs/manual/plots/column.zh.md
docs/manual/plots/gauge.zh.md
docs/manual/plots/group-bar.zh.md
docs/manual/plots/group-column.zh.md
docs/manual/plots/line.zh.md
docs/manual/plots/pie.zh.md
docs/manual/plots/radar.zh.md
docs/manual/plots/ring.zh.md
docs/manual/plots/stack-area.zh.md
docs/manual/plots/stack-bar.zh.md
docs/manual/plots/stack-column.zh.md
docs/manual/plots/tinyPlot-progress.zh.md
docs/manual/plots/tinyPlot-ring-progress.zh.md

docs: line & area

---

src/geoms/base.ts
src/interface/config.ts
src/theme/dark.ts
src/theme/default.ts

@paleface001 在这里设置是生效的，可以不用改g2了

fix: 在g2plot里设置widthRatio

---

src/plots/ring/component/annotation/central-text-template.ts
src/plots/ring/layer.ts

feat(ring-center-text): 环图中心文本默认显示总计 & 数值大小为32px

---

src/plots/radar/layer.ts

1. 图例默认左上
2. 轴标签文字颜色 #000 65%
3. 轴标签距离轴线为8px

feat(radar-style): 调整radar样式

---

src/components/label/parser.ts
src/plots/pie/layer.ts

修复饼图 label type inner outer 无效的bug
修复反复切换label.type offset 计算问题

Fix pie label bug

---

examples/area/basic/demo/slider.js
examples/line/basic/demo/line-point-style.js
examples/line/basic/demo/line-slider.js
examples/line/basic/demo/line.js
src/plots/stack-column/layer.ts
src/theme/default.ts

Fix line area x date

---

gatsby-config.js
package.json

https://github.com/antvis/antvis.github.io/issues/18

🚀 g2plot.antv.vision

---

src/plots/bar/layer.ts
src/plots/percentage-stack-bar/layer.ts

feat: 隐藏bar 和 percentagestackbar x轴的tickline

---

src/base/plot.ts
src/util/event.ts

fix: dblClick event name

---

src/interaction/helper/data-range.ts
src/interaction/scrollbar.ts
src/plots/percentage-stack-bar/layer.ts

fix: 百分比堆积条形图数据顺序 & 垂直滚动条数据范围修复

---

CHANGELOG.md
examples/bar/basic/demo/meta.json
package.json

- 更新下之前自动生成的CHANGELOG
- 条形图一的DEMO截图更新

docs: update changelog for v0.11.1

---

package.json

fix: remove sideEffects flag for now

---

src/base/controller/padding.ts
src/theme/dark.ts
src/theme/default.ts

close #321 
fix-before:
fix-after:

fix: fix auto padding for title & axis

---

tsconfig.json

fix: export declaration file

---

src/plots/column/layer.ts
src/plots/radar/layer.ts

fix: column scale

---

src/tiny-plots/progress/event.ts
src/tiny-plots/progress/layer.ts
src/tiny-plots/ring-progress/event.ts

在progress上代理了一下，否则mousenter和mouseleave都无法正常触发。

fix: progress mouseenter & mouseleave event triggered by mask

---

.github/workflows/release.yml
docs/manual/getting-started.en.md
docs/manual/getting-started.zh.md
package.json
webpack.config.js

- 官网快速上手部分增加使用示例
- release action publish-site 改写

docs: umd import usage docs

---

__tests__/unit/tinyPlot/progress-spec.ts
package.json
src/plots/percentage-stack-area/layer.ts
src/plots/percentage-stack-bar/layer.ts
src/plots/percentage-stack-column/layer.ts
src/tiny-plots/progress/component/marker.ts
src/tiny-plots/progress/layer.ts
src/tiny-plots/ring-progress/layer.ts
src/tiny-plots/tiny-area/layer.ts
src/tiny-plots/tiny-column/layer.ts
src/tiny-plots/tiny-line/layer.ts

progress update

---

.github/workflows/release.yml
examples/bar/basic/API.zh.md
examples/column/basic/API.zh.md
package.json
src/interface/config.ts
src/plots/bar/component/label/bar-label.ts

- ref: #351 允许用户通过`adjustPosition`来控制标签的位置调整
- 升级 gatsby-antv-theme

feat: label添加adjustPosition选项

---

gatsby-config.js
package.json
site/pages/index.zh.tsx

修复网站搜索。
https://github.com/algolia/docsearch-configs/blob/37a0e87e5c667a6492222e2df2b1623e87efcbea/configs/antv_g2plot.json
https://github.com/antvis/gatsby-theme-antv/issues/79

docs: 🔍 Add algolia docsearchOptions

---

demos/bubble-basic.ts
demos/scatter-basic.ts
package.json
src/base/view-layer.ts
src/plots/bubble/component/label/bubble-label.ts
src/plots/bubble/layer.ts
src/plots/column/component/label/column-label.ts
src/plots/scatter/components/quadrant.ts
src/plots/scatter/components/trendline.ts
src/plots/scatter/layer.ts
src/util/math.ts

checklist:
完成稿：
`linear` `quadratic` `cubic` `power` `logarithmic`
完成稿：

feat: 散点图 & 气泡图功能优化

---

__tests__/unit/groupColumn-spec.ts
__tests__/unit/pie-spec.ts
package.json
src/plots/line/layer.ts

ref: https://github.com/antvis/G2/pull/1807/files

fix(label): move label into foreground

---

.github/workflows/release.yml
package.json

chore: update g2 & scale dependency

---

__tests__/unit/pie-label-spec.ts
__tests__/unit/pie-outerLabel-spec.ts
__tests__/utils/dom.ts
src/plots/pie/component/label/base-label.ts
src/plots/pie/component/label/outer-label.ts

refactor(pie): 优化pie outer-label布局摆放

---

__tests__/bugs/issue-419-spec.ts
src/plots/pie/component/label/spider-label.ts

fix(issue-419): spider-label pie点击图例 label绘制出错

---

src/base/controller/padding.ts

fix: 只有一个数据时 autoPadding 报错

---

examples/gallery/index.en.md
examples/gallery/index.zh.md
gatsby-config.js

修复 https://github.com/antvis/gatsby-theme-antv/issues/89

docs: fix examples url 404

---

src/base/plot.ts
src/base/view-layer.ts
src/interface/config.ts
src/interface/types.ts
src/plots/bar/component/label/bar-label.ts
src/plots/column/component/label/column-label.ts
src/plots/line/layer.ts
src/plots/pie/component/label/spider-label.ts
src/plots/radar/layer.ts
src/plots/ring/layer.ts
src/plots/scatter/components/label/scatter-label.ts
src/util/event.ts
src/util/responsive/responsive.ts
src/util/state-manager.ts

fix(ts): ts definition fix

---

demos/bubble-quadrant.ts
demos/bubble-trendline.ts
demos/scatter-basic.ts
examples/bubble/basic/demo/basic.js
src/plots/bubble/layer.ts
src/plots/scatter/components/quadrant.ts
src/plots/scatter/layer.ts

fix: 解决 scatter/bubble 继承/Tooltip 问题

---

examples/line/multiple/demo/line-label.js
src/plots/line/animation/clipIn-with-data.ts
src/plots/line/layer.ts

尾部跟随label动画

---

package.json

avoid tree shaking not working

refactor: use unpkg other than browser field in package.json

---

__tests__/bugs/issue-467-spec.ts
src/base/controller/theme.ts

fix: 修复不同plot设置theme option互相影响

---

docs/manual/general-config.zh.md
src/components/label/parser.ts
src/interface/config.ts
src/plots/funnel/component/label/parser.ts
src/plots/funnel/layer.ts
src/util/formatter.ts

```ts
label: {
precision?: number,
suffix?: string
}
```
close #351

feat(label): 数据标签精度和后缀单位配置

---

__tests__/unit/components/breadcrumb-spec.ts
package.json
src/components/base.ts
src/components/breadcrumb.ts

feat: 面包屑组件

---

__tests__/bugs/issue-478-spec.ts
docs/manual/general-config.en.md
docs/manual/general-config.zh.md
src/plots/bar/layer.ts

fix: 条形度暗黑主题修复

---

__tests__/unit/pie-innerLabel-spec.ts
__tests__/unit/pie-spec.ts
__tests__/unit/utils-math-spec.ts
src/plots/pie/component/label/inner-label.ts
src/plots/pie/layer.ts
src/util/math.ts

详细见 commit 记录
新增特性：
1. offset 可设置字符串百分比
2. allowOverlap
待全部 label 完毕，完善文档

feat: 饼图 inner label

---

examples/funnel/basic/demo/basic.js
examples/funnel/basic/demo/percent.js
examples/liquid/basic/demo/basic.js
examples/liquid/basic/demo/meta.json
src/plots/funnel/layer.ts

漏斗图优化与文档更新

---

__tests__/unit/pie-spec.ts
docs/manual/plots/pie.en.md
docs/manual/plots/pie.zh.md
examples/pie/basic/API.zh.md
examples/pie/basic/demo/meta.json
examples/pie/basic/demo/outer-center-label.js
src/plots/pie/component/label/outer-center-label.ts
src/plots/pie/component/label/outer-label.ts
src/plots/pie/layer.ts

算法说明：
- adjustPosiiton之后，不做偏移调整，直接做碰撞隐藏
checklist

feat(pie-label): outer-center label布局

---

demos/radar-basic.ts
docs/manual/plots/radar.en.md
docs/manual/plots/radar.zh.md
src/interface/config.ts
src/plots/radar/layer.ts

feat: update radar docs and config

---

.github/workflows/auto-merge.yml
.github/workflows/dependabot-auto-merge.yml
.github/workflows/pr-size-label.yml
.github/workflows/stale.yml

- 自动关闭过期issue
- 自动合并dependabot的PR

chore: add stale and auto merge workflows

---

.github/workflows/auto-merge.yml
src/base/view-layer.ts
src/plots/line/layer.ts

fix(types): correct data types and point style types

---

__tests__/unit/ring-spec.ts
src/plots/pie/component/label/inner-label.ts
src/plots/pie/component/label/outer-label.ts
src/plots/pie/layer.ts
src/plots/ring/layer.ts

1. 当type为inner-label时，默认文本居中对齐，饼图offset为-1/3，环图居中
2. 环图单测修复 & 新增label位置断言

fix(inner-label): inner-label支持百分比offset & 默认调整label offset

---

package.json
src/base/controller/padding.ts
src/base/view-layer.ts
src/plots/heatmap/components/legend.ts
src/plots/heatmap/layer.ts
src/plots/matrix/component/legend.ts
src/plots/matrix/layer.ts

paddingController中添加clearOuterComponents()方法，修复heatmap & maxtrix updateConfig时legend visible不生效问题

fix: heatmap & matrix legend visible Closes #511

---

src/combo-plots/base.ts

fix(types): fix combo base interface

---

package.json

暂时锁定 gatsby 版本
https://github.com/gatsbyjs/gatsby/issues/20943
https://github.com/antvis/gatsby-theme-antv/issues/103

fix: non-nullable field SiteSiteMetadata.id

---

__tests__/bugs/issue-556-spec.ts
src/plots/waterfall/layer.ts

fix: waterfall yAxis

---

src/plots/bullet/base-layer.ts
src/plots/bullet/event.ts
src/plots/bullet/index.ts
src/plots/bullet/layer.ts
src/plots/index.ts
src/plots/pie/component/label/outer-label.ts
src/plots/pie/layer.ts

1. label line绘制优化
2. label line 支持配置样式
3. close #580

饼图 label line 优化绘制

---

package.json

close https://github.com/antvis/gatsby-theme-antv/issues/103

fix: 🆙 upgrade gatsby theme version

---

__tests__/bugs/issue-598-spec.ts
src/plots/pie/layer.ts

fix: pie label type update error 

---

demos/pie-basic2.ts
docs/manual/general-config.zh.md
src/base/view-layer.ts
src/interface/config.ts

feat: add legend config marker

---

__tests__/unit/radar-spec.ts
demos/radar-basic.ts
demos/radar-series.ts
examples/radar/basic/demo/basic.js
examples/radar/basic/demo/series.js
gatsby-browser.js
src/base/view-layer.ts
src/components/axis/parser.ts
src/interface/config.ts
src/plots/index.ts
src/plots/pie/component/label/outer-label.ts
src/plots/radar/event.ts
src/plots/radar/index.ts
src/plots/radar/layer.ts
src/plots/radar/theme.ts
src/sparkline/progress/layer.ts

* theme 不生效
* legend 的 position 和交互均不生效
* G2 4.x 无法拿到组件级别的渲染实例，例如坐标轴标签，这样不易测试

【1.x】迁移 radar 到 G2 4.x

---

demos/bubble-basic.ts
demos/bubble-quadrant.ts
demos/scatter-basic.ts
examples/bubble/basic/demo/basic.js
examples/bubble/basic/demo/quadrant.js
examples/bubble/basic/demo/trendline.js
examples/scatter/basic/demo/basic.js
examples/scatter/basic/demo/color-mapping.js
examples/scatter/basic/demo/label-placement.js
examples/scatter/basic/demo/trendline.js
src/geoms/point/circle.ts
src/plots/bubble/index.ts
src/plots/bubble/layer.ts
src/plots/index.ts
src/plots/scatter/components/label.ts
src/plots/scatter/components/quadrant.ts
src/plots/scatter/components/trendline.ts
src/plots/scatter/event.ts
src/plots/scatter/index.ts
src/plots/scatter/layer.ts
src/plots/waterfall/component/label/diff-label.ts

migrate scatter and bubble

---

demos/bubble-basic.ts
demos/bubble-quadrant.ts
examples/bubble/basic/demo/basic.js
examples/bubble/basic/demo/quadrant.js
examples/scatter/basic/demo/basic.js
examples/scatter/basic/demo/color-mapping.js
src/plots/scatter/layer.ts

* 去除 hover showMarker，https://github.com/antvis/G2/issues/2005#issuecomment-589544637
* 内置 processData 过滤非法数据，https://github.com/antvis/G2/issues/2005#issuecomment-589465324

[1.x] 修复 scatter 迁移问题

---

src/plots/pie/component/label/base-label.ts

feat(pie-label): 添加标签抽样，优先显示占比大的标签的配置

---

package.json
src/base/view-layer.ts
src/util/bbox.ts

fix: 修复升级scale后的label超出区域问题

---

src/plots/word-cloud/layer.ts

render canvas size bug when without imageMask

feat(word-cloud): fix render bug without imageMask

---

src/plots/pie/layer.ts

[0.1.x ] fix: 饼图 tooltip 需要调用 layer 里的 tooltip 方法

---

__tests__/unit/word-cloud-spec.ts
src/plots/word-cloud/layer.ts
src/plots/word-cloud/word-cloud-tooltips.ts
src/plots/word-cloud/wordcloud2.ts

Feat: 词云图 Tooltip 定制
Fix: 背景色支持透明

Feat: 词云图 Tooltip 定制和背景色支持透明

---

src/plots/bullet/theme.ts
src/plots/pie/theme.ts
src/plots/waterfall/layer.ts
src/theme/theme.ts

1. 饼图主题注册
2. 瀑布图 tooltip
> 注意下，主题那一块，现在的方式有所变化。要在内部兼容为 master 上的注册方式，还是统一修改（文档也需要修改）

1.x 饼图 & 瀑布图走查

---

.eslintrc
__tests__/unit/base/controller/canvas-controller-spec.ts
__tests__/unit/plots/pie/pie-spider-label-spec.ts
__tests__/utils/dom.ts
src/base/controller/canvas.ts
src/base/layer.ts
src/components/description.ts
src/dependents.ts
src/plots/bar/component/label.ts
src/plots/heatmap/components/legend.ts
src/plots/line/component/label/line-label.ts
src/plots/pie/component/label/outer-label.ts
src/plots/pie/component/label/spider-label.ts
src/plots/stack-column/layer.ts

Feat svg supported

---

__tests__/unit/plots/radar/radar-spec.ts
demos/radar-basic.ts
examples/radar/basic/demo/basic.js
examples/radar/basic/demo/series.js
src/components/axis/parser.ts
src/plots/line/layer.ts
src/plots/radar/layer.ts
src/plots/rose/layer.ts

【1.x】雷达图上线走查

---

__tests__/unit/plots/column/column-spec.ts
__tests__/unit/plots/range-column/rangeColumn-spec.ts
package.json
src/components/guide-line.ts

fix: 辅助线样式设置

---

package.json

chore: Improve lint staged prettier workflow

---

__tests__/unit/plots/scatter/scatter-quadrant-spec.ts
src/plots/scatter/components/quadrant.ts
src/plots/scatter/layer.ts

fix: 修复 scatter 四象限问题及添加测试用例

---

__tests__/unit/plots/bubble/bubble-spec.ts
src/geoms/point/circle.ts
src/plots/bubble/layer.ts
src/plots/bubble/shape.ts
src/plots/bubble/theme.ts
src/plots/scatter/layer.ts
src/plots/scatter/theme.ts

【1.x】scatter & bubble 视觉走查

---

__tests__/unit/plots/bar/bar-scrollbar-spec.ts
src/interaction/scrollbar.ts

component和gui的实现对滚动条滑块有差别，调整下滑块的最小值

fix: set default min scrollbar size

---

src/interface/config.ts

https://github.com/antvis/G2Plot/blob/8db7d1f713fa76eede2a1ee87e1f5a59d6523d36/src/util/scale.ts#L35-L37

fix(types): add mask for ITimeAxis

---

examples/bar/basic/demo/basic.js
examples/bar/basic/demo/label-position.js
src/plots/bar/layer.ts
src/plots/column/layer.ts
src/plots/liquid/layer.ts
src/sparkline/progress/layer.ts

yunfengdie issue批量修复

---

docs/manual/plots/donut.en.md
docs/manual/plots/donut.zh.md
examples/pie/donut/API.zh.md
src/plots/donut/component/ring-statistic.ts
src/plots/donut/layer.ts

feat(donut): 环图指标卡新增`totalLabel`配置

---

.gitignore
__tests__/unit/plots/pie/pie-outer-label-spec.ts
__tests__/unit/util/common-spec.ts
package.json
src/combo-plots/util/globalAxis.ts
src/combo-plots/util/globalLegend.ts
src/combo-plots/util/globalTooltip.ts
src/components/breadcrumb.ts
src/dependents.ts
src/plots/funnel/layer.ts
src/plots/gauge/geometry/shape/gauge-shape.ts
src/plots/treemap/interaction/drillDown.ts
src/util/common.ts
src/util/responsive/node/shape-nodes.ts
src/util/responsive/responsive.ts
src/util/responsive/rules/clear-overlapping.ts
src/util/responsive/rules/digits-abbreviate.ts
src/util/responsive/rules/node-jitter-upward.ts
src/util/responsive/rules/node-jitter.ts
src/util/responsive/rules/nodes-resampling-by-change.ts
src/util/responsive/rules/nodes-resampling-by-state.ts
src/util/responsive/rules/robust-abbrevaite.ts
src/util/responsive/rules/text-abbreviate.ts
src/util/responsive/rules/text-hide.ts
src/util/responsive/rules/text-rotation.ts
src/util/responsive/rules/text-wrapper.ts
webpack.config.js

测试npm包使用都ok，https://codesandbox.io/s/g2plot-test-qlv4n

fix: cleanup dependencies and imports

---

__tests__/bugs/issue-803-spec.ts
src/base/controller/canvas.ts

修复 tooltip 偏移的问题

---

README.md

chore: fix coverage badge

---

docs/manual/plots/donut.en.md
docs/manual/plots/donut.zh.md
docs/manual/plots/pie.en.md
docs/manual/plots/pie.zh.md
examples/pie/donut/API.zh.md

Refactor docs

---

__tests__/bugs/issue-830-spec.ts
src/plots/pie/component/label/base-label.ts
src/plots/pie/component/label/utils/index.ts

fix: pie label autoRotate failed

---

__tests__/bugs/issue-813-spec.ts
__tests__/bugs/issue-866-spec.ts
__tests__/utils/common.ts
package.json
src/base/layer.ts
src/base/view-layer.ts
src/interaction/base.ts
src/interaction/slider.ts

fix: changeData and updateConfig fix

---

__tests__/unit/components/label/label-spec.ts
__tests__/unit/plots/stacked-area/stackArea-label-spec.ts
__tests__/unit/plots/stacked-column/component/label-spec.ts
src/components/label/base.ts
src/components/label/point.ts
src/dependents.ts
src/plots/bar/component/label.ts
src/plots/column/component/label.ts

feat: 数据标签动画补上

---

__tests__/data/common.ts
__tests__/unit/plots/bar/component/label-spec.ts
__tests__/unit/plots/column/component/label-spec.ts
package.json
src/interface/config.ts
src/plots/bar/component/label.ts
src/plots/column/component/label.ts
src/plots/line/layer.ts
src/plots/pie/component/label/base-label.ts
src/plots/pie/layer.ts
src/plots/stacked-area/layer.ts

* Column/Bar 在有负数情况下的位置修正
* TS 定义一些微调

fix: correct label position for negative data

---

src/base/controller/padding.ts
src/dependents.ts
src/interface/config.ts
src/util/common.ts

临时先修复下，还是需要整理把inner padding相关的逻辑移除掉

fix: auto inner padding calc for axis component

---

tsconfig.json

chore: add sourcesContent to sourcemap

---

src/combo/dual-line/layer.ts

- add default legend config for dual line

fix: fix dual line render error without legend config

---

examples/general/tooltip/demo/isolate-tooltip.js
examples/general/tooltip/demo/tooltip-inner-chart.js
examples/general/tooltip/demo/tooltip-statistic-value.js
package.json
src/base/view-layer.ts
src/combo/column-line/layer.ts
src/combo/dual-line/layer.ts
src/combo/groupedColumn-line/layer.ts
src/combo/stackedColumn-line/layer.ts
src/interface/config.ts

```
tooltip:{
visible: true,
custom:{
container:'', // 自定义tooltip容器，可不指定
follow: false, // 是否固定tooltip容器位置
customContent: ()=>{} // 透传component方法，
onChange:()=>{} // 仅动态指定tooltip.ev.items
}
}
```

feat: customTooltip 配置项更新

---

src/plots/area/interface.ts
src/plots/bar/interface.ts
src/plots/column/interface.ts
src/plots/line/layer.ts

- rename `scrollBar` to `scrollbar`
https://github.com/antvis/G2Plot/blob/c3ba85b5484f67d18f4e486d5553f0dcc2bf7be4/src/base/view-layer.ts#L504-L519
- mark scrollbar interaction config as optional

fix(types): fix scrollbar type definitions

---

__tests__/bugs/issue-830-spec.ts
package.json
src/plots/funnel/animation/funnel-scale-in-x.ts
src/plots/funnel/animation/funnel-scale-in-y.ts
src/plots/pie/component/label/base-label.ts
src/util/g-util.ts
src/util/math.ts
src/util/path.ts

https://github.com/antvis/util/issues/46

chore(deps): 升级 matrix-util

---

src/plots/word-cloud/layer.ts
src/plots/word-cloud/wordcloud2.ts

Feat: 词云图禁用动画模式增加

---

src/plots/pie/component/label/spider-label.ts

fix: spider label 修复

---

gatsby-config.js
package.json
site/pages/index.zh.tsx

feat: news

---

__tests__/unit/theme/theme-spec.ts
docs/manual/plots/line.en.md
docs/manual/plots/line.zh.md
src/base/controller/theme.ts
src/theme/interface.ts
src/theme/theme.ts

themeController 中获取用户配置的 theme，需要转换为 G2 的主题。
同时添加了类型定义 & 测试用例
clsoe #897

fix: 修改 theme config 失效，需要转换为 g2 主题

---

examples/line/multiple/demo/marker-active.js
examples/line/multiple/demo/meta.json
src/geoms/point/guide.ts
src/plots/line/interaction/index.ts
src/plots/line/interaction/marker-active.ts

- 同时 `point/guide` style 回调函数增加了 xField 和 yField 字段映射

feat: 添加 active marker，自定义 tooltip controller

---

__tests__/bugs/donut-statistic-spec.ts
src/plots/donut/component/ring-statistic.ts
src/plots/pie/component/label/base-label.ts

当在 scale 上设置 formatter 时，label 及指标卡部分没有生效~~~~~~

饼及环图的 label 以及 Statistics 的内容可受 scale 影响

---

src/plots/donut/component/statistic-template.ts
src/plots/donut/component/statistic.ts

Fix donut statistic

---

__tests__/bugs/issue-1161-spec.ts
examples/line/multiple/demo/marker-active.js
src/plots/pie/layer.ts

fix(pie): 修复饼图数据全为 0 展示

---

__tests__/bugs/issue-1137-spec.ts
src/base/constants.ts
src/base/view-layer.ts
src/components/label/base.ts
src/interaction/scrollbar.ts
src/plots/bar/component/label-auto.ts
src/plots/column/component/label-auto.ts

fix: update scrollbar and data label when changeData

---

src/components/guide-line.ts

[![Edit young-sound-9ffd1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-sound-9ffd1?fontsize=14&hidenavigation=1&theme=dark)

fix: fix guide line render error without plot data

---

CONTRIBUTING.md
CONTRIBUTING.zh-CN.md

Update markdown format of links.
Earlier, rendering of links were not taking place due to an extra space in the links. I have updated them for proper rendering.

docs: update CONTRIBUTING.md and CONTRIBUTING.zh-CN.md

---

__tests__/bugs/donut-statistic-spec.ts
src/plots/donut/component/ring-statistic.ts
src/plots/donut/component/statistic-template.ts
src/plots/pie/component/label/base-label.ts
src/plots/pie/component/label/spider-label.ts

1. 合并拆分两套模板的逻辑
2. 修复 htmlContent 失效的问题
3. 完善 htmlContent 回调函数的参数内容

环图 Statistics 区域优化

---

__tests__/unit/utils/flow-spec.ts
src/core/adaptor.ts
src/core/plot.ts
src/plots/line/adaptor.ts
src/plots/line/index.ts
src/utils/flow.ts
src/utils/index.ts

feat(flow): adaptor 使用 flow 的方式处理,让逻辑散开且容易复用

---

.github/workflows/mirror.yml
.prettierignore
__tests__/unit/plots/line/axis-spec.ts
__tests__/unit/plots/line/index-spec.ts
__tests__/unit/utils/pick-spec.ts
src/plots/line/adaptor.ts
src/types/axis.ts
src/utils/index.ts
src/utils/pick.ts

feat(line): meta config -> scale

---

__tests__/unit/plots/pie/index-spec.ts
__tests__/unit/plots/pie/label-spec.ts
src/plots/pie/adaptor.ts

feat(pie/label):  add pie options

---

__tests__/unit/core/index-spec.ts
src/core/plot.ts
src/plots/line/types.ts
src/plots/tiny-line/adaptor.ts
src/plots/tiny-line/types.ts
src/types/common.ts
src/types/index.ts

Refactor base types

---

__tests__/unit/plots/tiny-column/index-spec.ts
src/index.ts
src/plots/tiny-column/adaptor.ts
src/plots/tiny-column/index.ts
src/plots/tiny-column/types.ts

加入 迷你柱形图
废弃 color & colorField

V2 mini chart tiny column

---

__tests__/unit/plots/tiny-area/index-spec.ts
package.json
src/index.ts
src/plots/tiny-area/adaptor.ts
src/plots/tiny-area/index.ts
src/plots/tiny-area/types.ts

V2 mini chart tiny area

---

docs/manual/plots/donut.en.md
docs/manual/plots/donut.zh.md
docs/manual/plots/liquid.en.md
docs/manual/plots/liquid.zh.md

docs(donut, liquid): modify based on issue #1260

---

__tests__/unit/plots/pie/index-spec.ts
__tests__/unit/plots/pie/interaction-spec.ts
src/plots/pie/adaptor.ts
src/plots/pie/interaction.ts
src/plots/pie/interaction/index.ts
src/plots/pie/interaction/pie-legend-action.ts
src/plots/pie/interaction/pie-statistic-action.ts
src/utils/g-util.ts

v2 pie/enhance

---

__tests__/unit/plots/progress/index-spec.ts
__tests__/unit/plots/ring-progress/index-spec.ts
src/index.ts
src/plots/progress/adaptor.ts
src/plots/progress/index.ts
src/plots/progress/types.ts
src/plots/ring-progress/adaptor.ts
src/plots/ring-progress/index.ts
src/plots/ring-progress/types.ts

feat: add progress

---

__tests__/data/radar.ts
__tests__/unit/plots/radar/area-spec.ts
__tests__/unit/plots/radar/axis-spec.ts
__tests__/unit/plots/radar/index-spec.ts
__tests__/unit/plots/radar/point-spec.ts
__tests__/unit/plots/radar/style-spec.ts
__tests__/unit/plots/radar/tooltip-spec.ts
src/index.ts
src/plots/radar/adaptor.ts
src/plots/radar/constants.ts
src/plots/radar/index.ts
src/plots/radar/types.ts

feat: add radar plot

---

__tests__/data/radar.ts
__tests__/unit/plots/pie/interaction-spec.ts
__tests__/unit/plots/pie/statistic-spec.ts
__tests__/unit/plots/radar/tooltip-spec.ts
src/plots/radar/index.ts
src/plots/radar/interaction/index.ts
src/plots/radar/interaction/radar-tooltip-action.ts
src/plots/radar/types.ts

feat(v2/radar): 自定义 radar tooltip，允许横向对比显示 tooltip

---

__tests__/unit/plots/pie/empty-data-spec.ts
src/plots/pie/adaptor.ts

**特性**
**待处理**
**相关调研**
- 调研了 highcharts、anycharts、echarts 等，最后综合一下方案：
||数据全为0|数据全为null或undefined|数据部分为0、部分为null或undefined|
|---|---|---|---|
|highcharts|![image](https://user-images.githubusercontent.com/15646325/88471842-20995e00-cf40-11ea-89b3-b67da86a6418.png)|![image](https://user-images.githubusercontent.com/15646325/88471847-28590280-cf40-11ea-84fb-50e61ec437e8.png)|![image](https://user-images.githubusercontent.com/15646325/88471849-2f801080-cf40-11ea-92a8-59151d8a8d71.png)|
|echarts|![image](https://user-images.githubusercontent.com/15646325/88471852-39a20f00-cf40-11ea-81e7-a57330a3e1a3.png)|![image](https://user-images.githubusercontent.com/15646325/88471853-3f97f000-cf40-11ea-8858-19ba24ad8035.png)|![image](https://user-images.githubusercontent.com/15646325/88471856-44f53a80-cf4 …

feat(v2/pie): 饼图数据全为 0 的处理

---

__tests__/unit/utils/invariant-spec.ts
src/plots/pie/adaptor.ts
src/utils/index.ts
src/utils/invariant.ts

feat(util): add invariant/log util method

---

__tests__/unit/plots/tiny-area/index-spec.ts
__tests__/unit/plots/tiny-column/index-spec.ts
__tests__/unit/plots/tiny-line/index-spec.ts
package.json
src/plots/tiny-area/adaptor.ts
src/plots/tiny-area/types.ts
src/plots/tiny-column/adaptor.ts
src/plots/tiny-column/types.ts
src/plots/tiny-line/adaptor.ts
src/plots/tiny-line/constants.ts
src/plots/tiny-line/types.ts
src/types/tooltip.ts

- tiny-line: add tooltip
- tiny-column: add tooltip
- tiny-area: add tooltip

V2 tiny tooltip

---

src/plots/column/apply-responsive/label.ts
src/plots/grouped-bar/layer.ts
src/plots/grouped-column/layer.ts
src/plots/grouped-rose/layer.ts
src/plots/line/apply-responsive/label.ts
src/plots/percent-stacked-area/layer.ts
src/plots/radar/layer.ts
src/plots/stacked-area/layer.ts
src/plots/stacked-bar/layer.ts
src/plots/stacked-column/component/label.ts
src/plots/stacked-column/layer.ts
src/plots/stacked-rose/layer.ts
src/util/responsive/apply/label.ts
src/util/responsive/rules/node-jitter-upward.ts
src/util/responsive/rules/nodes-resampling-by-state.ts

修复如下问题：
+ line 的 responsive: true 失效
+ column 的 label 自动调整失效
+ 雷达图 tooltip 不生效
+ 漏斗图： 动态高度以及对比漏斗图报错

Fix responsive not work

---

src/interaction/scrollbar.ts

```
scrollbar.ts:178 Uncaught (in promise) TypeError: Cannot read property 'field' of undefined
at eval (scrollbar.ts:178)
at Module.oe (map-values.ts:13)
at e.measureScrollBar (scrollbar.ts:177)
at e.n (scrollbar.ts:95)
at a (index.ts:70)
at e.t.emit (index.ts:74)
at e.paint (view.ts:1247)
at e.render (view.ts:223)
at e.render (view-layer.ts:312)
at t.processAutoPadding (padding.ts:85)
```
https://stackblitz.com/edit/react-mqqbsc?embed=1&file=index.js

fix: fix scrollbar render error with multi geometry

---

__tests__/bugs/issue-1137-spec.ts
__tests__/unit/plots/stacked-column/component/label-spec.ts
src/geoms/line/main.ts
src/plots/pie/component/label/spider-label.ts
src/plots/pie/layer.ts
src/plots/stacked-column/component/label.ts

* 修复饼图数值字段为分类类型时，导致浏览器崩溃的问题...
* fix 失败的测试用例

Daily 0730 fix

---

__tests__/bugs/issue-1378-spec.ts
src/components/marker-point.ts

多折线图时，dataArray 是多条数据组。每一条折线都应该匹配 marker point 点

fix(issue-1378): 修复多折线图设置 marker point 时，只对一条线生效

---

__tests__/bugs/issue-1389-spec.ts
src/combo/column-line/layer.ts

fix(#1389): 修复 GroupedColumnLine 右侧 tooltip formatter 不生效

---

src/plots/pie/layer.ts

fix: 修复饼图事件不生效的问题

---

__tests__/bugs/issue-1405-spec.ts
src/base/view-layer.ts

fix: issue 1405

---

src/components/axis/state.ts
src/util/responsive/apply/axis.ts

fix(#1268): 修复 undefined 问题

---

examples/gallery/index.en.md
examples/scatter/basic/index.en.md
gatsby-config.js

docs: 修改网站地址

---

CHANGELOG.md
README.md
README.zh-CN.md
__tests__/unit/index-spec.ts
examples/line/multiple/demo/marker-active.ts
package.json
src/index.ts

chore: v2.0.0-beta.1

---

docs/common/chart-options.en.md
docs/common/chart-options.zh.md
examples/scatter/basic/API.en.md
examples/scatter/basic/API.zh.md
package.json

- 添加通用图表配置 chart-options
- 升级 @antv/gatsby-theme-antv

docs: 添加图表通用配置

---

docs/common/chart-options.zh.md
docs/common/line-style.en.md
docs/common/line-style.zh.md
docs/common/shape-style.en.md
docs/common/shape-style.zh.md
docs/common/text-style.en.md
docs/common/text-style.zh.md
docs/common/tooltip.en.md
docs/common/tooltip.zh.md
examples/scatter/basic/API.zh.md

- line-style.zh.md
- text-style.zh.md
- shape-style.zh.md
- tooltip.zh.md

docs: 添加 tooltip

---

src/core/plot.ts
src/utils/g-util.ts

Chore walkthrough

---

docs/common/axis.en.md
docs/common/axis.zh.md
docs/common/label.en.md
docs/common/label.zh.md
examples/scatter/basic/API.en.md
examples/scatter/basic/API.zh.md

docs: 添加 axis

---

src/core/plot.ts

- 修改 changeData ,  去掉 render 。

fix: 修改 changeData

---

examples/bullet/basic/demo/basic.js
examples/bullet/basic/demo/color-range.js
examples/bullet/basic/demo/group-color-range.js
examples/bullet/basic/demo/group.js
examples/bullet/basic/demo/multi-targets.js
examples/bullet/basic/demo/overflow.js

fix(bullet): 子弹图图例隐藏，修改 demo，设置图例 offsetY 偏移

---

src/plots/heatmap/layer.ts

修复function进入isObject逻辑块及shapeStyle拼写错误问题

fix: heatmap shapeStyle设置callback无效

---

CHANGELOG.md
package.json
src/combo/groupedColumn-line/layer.ts
src/plots/funnel/layer.ts

* fix: 修复分组柱折线图坐标轴标题遮挡问题
* fix: 修复漏斗图不支持 Tooltip formatter 问题

fix: 1.x bugfix

---

src/core/plot.ts

- 解决 changeData 无效问题， 没有 data 时不调用 adaptor 方法。

fix: 解决 changeData 无效问题

---

__tests__/unit/plots/pie/empty-data-spec.ts
__tests__/unit/plots/pie/state-spec.ts
src/core/plot.ts
src/plots/box/index.ts
src/plots/pie/index.ts
src/plots/radar/index.ts
src/types/animation.ts

- 新增基类 getDefaultOptions animation: true 配置
- 修改子类 getDefaultOptions 写法

perf: 新增 animation 并更正其它图表 getDefaultOptions

---

.eslintrc
package.json
src/core/plot.ts
src/plots/_template/index.ts
src/plots/area/index.ts
src/plots/bar/adaptor.ts
src/plots/bar/index.ts
src/plots/box/adaptor.ts
src/plots/column/index.ts
src/plots/dual-axes/index.ts
src/plots/line/index.ts
src/plots/pie/index.ts
src/plots/pie/label/index.ts
src/plots/pie/label/inner-label.ts
src/plots/progress/adaptor.ts
src/plots/progress/index.ts
src/plots/ring-progress/adaptor.ts
src/plots/ring-progress/index.ts
src/plots/rose/adaptor.ts
src/plots/rose/index.ts
src/plots/scatter/adaptor.ts
src/plots/scatter/index.ts
src/plots/tiny-area/adaptor.ts
src/plots/tiny-area/index.ts
src/plots/tiny-column/adaptor.ts
src/plots/tiny-column/index.ts
src/plots/tiny-line/adaptor.ts
src/plots/tiny-line/index.ts

test(eslint): add import-order rules for eslint

---

package.json
webpack.config.js

理论上去除 data-set 全量依赖（改成按需引入，下周 data-set 进行改造），可以将包降低了 600 Kb

chore: add limit-size

---

__tests__/unit/plots/scatter/quadrant-spec.ts
examples/scatter/basic/demo/meta.json
examples/scatter/basic/demo/quadrant.ts
src/plots/scatter/adaptor.ts
src/plots/scatter/types.ts
src/plots/scatter/util.ts
src/types/common.ts

feat: scatter chart supported quadrant

---

__tests__/unit/plugin/index-spec.ts
__tests__/unit/plugin/step-line.ts
package.json
src/core/plot.ts
src/index.ts
src/plugin/index.ts

chore: 2.0.0-beta.3

---

package.json

chore: upgrade to latest g2

---

__tests__/unit/plots/area/index-spec.ts
examples/area/basic/demo/basic-gradients.ts
examples/area/basic/demo/basic-slider.ts
examples/area/basic/demo/meta.json
examples/area/stacked/demo/basic-slider.ts
examples/area/stacked/demo/meta.json
src/plots/area/index.ts

ref https://github.com/antvis/G2Plot/issues/1536

chore: area 走查优化

---

src/core/plot.ts
src/plots/dual-axes/adaptor.ts

**checklists**
**效果图**
||效果|
|---|---|
|没有设置seriesField|![image](https://user-images.githubusercontent.com/15646325/92435967-24263300-f1d6-11ea-9c65-d64f676534e0.png)|
|设置了 seriesField|![image](https://user-images.githubusercontent.com/15646325/92436026-44ee8880-f1d6-11ea-90b2-c615d47b7f7b.png)|

feat(legend): add legend to dual-axes

---

__tests__/unit/plots/line/annotation-spec.ts
api-extractor.json
examples/area/basic/demo/basic-annotation.ts
examples/area/basic/demo/meta.json
examples/line/basic/demo/line-annotation.ts
examples/line/basic/demo/line-slider.ts
examples/line/basic/demo/meta.json
src/plots/line/index.ts

Fix line bugs

---

__tests__/unit/plots/word-cloud/animation-spec.ts
__tests__/unit/plots/word-cloud/axis-spec.ts
__tests__/unit/plots/word-cloud/index-spec.ts
__tests__/unit/plots/word-cloud/label-spec.ts
__tests__/unit/plots/word-cloud/legend-spec.ts
__tests__/unit/plots/word-cloud/style-spec.ts
__tests__/unit/plots/word-cloud/tooltip-spec.ts
src/index.ts
src/plots/word-cloud/adaptor.ts
src/plots/word-cloud/index.ts
src/plots/word-cloud/shapes/cloud.ts
src/plots/word-cloud/shapes/word-cloud.ts
src/plots/word-cloud/types.ts
src/plots/word-cloud/utils.ts

feat(v2/word-cloud): 新增词云图

---

examples/histogram/basic/demo/basic.ts
src/plots/bullet/index.ts

1. 解决走查问题
2. 解决子弹图的遗漏
Issue #1536 直方图

fix: 解决走查问题和修复遗漏问题（#1536）

---

__tests__/unit/plots/progress/index-spec.ts
__tests__/unit/plots/ring-progress/index-spec.ts
src/plots/progress/adaptor.ts
src/plots/progress/constant.ts
src/plots/progress/index.ts
src/plots/ring-progress/adaptor.ts
src/plots/ring-progress/index.ts
src/plots/ring-progress/types.ts

走查修复进度条图，进度环图

---

.lintmdrc
__tests__/unit/adaptor/geometries/base-spec.ts
__tests__/unit/plots/scatter/size-spec.ts
src/adaptor/geometries/base.ts
src/adaptor/geometries/interval.ts
src/adaptor/geometries/point.ts
src/core/plot.ts
src/plots/box/types.ts
src/plots/histogram/adaptor.ts
src/plots/tiny-column/types.ts
src/plots/tiny-line/types.ts
src/types/common.ts

attr mapping string

---

__tests__/unit/plots/tiny-area/index-spec.ts
__tests__/unit/plots/tiny-column/index-spec.ts
__tests__/unit/plots/tiny-line/index-spec.ts
package.json
src/plots/tiny-area/adaptor.ts
src/plots/tiny-area/types.ts
src/plots/tiny-column/adaptor.ts
src/plots/tiny-column/types.ts
src/plots/tiny-line/adaptor.ts
src/plots/tiny-line/constants.ts
src/plots/tiny-line/types.ts
src/types/tooltip.ts

- 修复 tiny tooltip 不统一问题。
- 删除多余文件。

fix: 修复迷你图 tooltip 不统一

---

__tests__/data/bullet.ts
__tests__/unit/plots/bullet/data-spec.ts
src/plots/bullet/adaptor.ts
src/plots/bullet/utils.ts
src/plots/histogram/adaptor.ts

1. 按照统一风格改造代码
- 修复一些命名问题
- 优化一些写法
2. docs和demo可能需要稍微修改下
- 目前运行不起来demo（后面提一个修复版本）

refactor: 改造v2子弹图为统一风格方式

---

docs/common/shape-style.en.md
docs/common/shape-style.zh.md
examples/bullet/basic/API.en.md
examples/bullet/basic/demo/basic.ts
examples/bullet/basic/demo/color.ts
examples/bullet/basic/demo/grouped.ts
examples/bullet/basic/demo/layout.ts
examples/bullet/basic/demo/meta.json
examples/bullet/basic/demo/stacked.ts
src/plots/bullet/utils.ts

docs: 修改文档和优化demo

---

__tests__/unit/plots/bullet/data-spec.ts
src/plots/bullet/adaptor.ts
src/plots/bullet/utils.ts

fix: 默默修复颜色问题，定义不同映射颜色的key

---

package.json
src/core/plot.ts
src/types/common.ts

fix(sync-view-padding): add syncViewPadding in core plot

---

examples/pie/basic/demo/meta.json
examples/pie/basic/demo/spider-label.ts
src/plots/pie/adaptor.ts

feat(pie): support spider-label

---

examples/word-cloud/basic/API.zh.md
examples/word-cloud/basic/demo/interaction.ts
examples/word-cloud/basic/demo/meta.json
src/plots/word-cloud/adaptor.ts
src/plots/word-cloud/index.ts
src/plots/word-cloud/types.ts
src/plots/word-cloud/utils.ts

feat(word-cloud): 主要是添加图表尺寸变化时自动重渲染

---

CHANGELOG.md
__tests__/unit/combo/columnLine-spec.ts
package.json
src/combo/column-line/index.ts
src/combo/column-line/layer.ts
src/combo/dual-line/index.ts
src/combo/dual-line/layer.ts

fix: 修复双轴图相关 bugs

---

src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/util/legend.ts

https://github.com/antvis/G2Plot/issues/1536

Fix dual axes view filter

---

__tests__/unit/plots/gauge/index-spec.ts
src/index.ts
src/plots/gauge/adaptor.ts
src/plots/gauge/constant.ts
src/plots/gauge/index.ts
src/plots/gauge/shapes/gauge.ts
src/plots/gauge/types.ts
src/plots/gauge/utils.ts

feat(gauge): new plot gauge

---

docs/manual/plots/pie.en.md
docs/manual/plots/pie.zh.md
docs/manual/plots/radar.en.md
docs/manual/plots/radar.zh.md
examples/pie/basic/API.en.md
examples/pie/basic/API.zh.md
examples/radar/basic/API.en.md
examples/radar/basic/API.zh.md
examples/scatter/basic/API.zh.md
src/index.ts
src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/index.ts
src/plots/dual-axes/types.ts
src/plots/dual-axes/util/option.ts
src/plots/word-cloud/index.ts

- 修正 demos  格式和书写错误
- 重命名 DualAxesOption => DualAxesOptions
- 修改词云图销毁之后报错

fix: demos and  reaname dual axes  option

---

examples/line/basic/demo/line-annotation-color.ts
examples/line/basic/demo/meta.json

docs: 增加一个line的annatation的demo

---

__tests__/unit/plots/word-cloud/utils-spec.ts
src/plots/word-cloud/utils.ts

chore(word-cloud): 完善词云图单测

---

__tests__/unit/plots/bullet/axis-spec.ts
__tests__/unit/plots/bullet/data-spec.ts
__tests__/unit/plots/bullet/index-spec.ts

test: 增加修改bullet测试用例

---

package.json
src/index.ts

chore: v2.0.0

---

examples/bullet/basic/API.en.md
examples/bullet/basic/API.zh.md
examples/bullet/basic/demo/color.ts
examples/bullet/basic/demo/layout.ts

fix(bullet): 修复文档和demo的问题

---

src/core/plot.ts
src/types/common.ts

feat(transform): add supportCSSTransform option

---

__tests__/unit/plots/gauge/index-spec.ts
__tests__/unit/plots/progress/index-spec.ts
__tests__/unit/plots/ring-progress/index-spec.ts
src/core/plot.ts
src/plots/gauge/adaptor.ts
src/plots/gauge/index.ts
src/plots/progress/adaptor.ts

fix(indicator): when indicator > 1 or < 0 in gauge, progress, ring

---

site/pages/index.less
site/pages/index.zh.tsx

feat(website): add css for demo container

---

__tests__/data/sales.ts
__tests__/unit/plots/bar/axis-spec.ts
__tests__/unit/plots/bar/index-spec.ts
__tests__/unit/plots/column/axis-spec.ts
__tests__/unit/plots/column/index-spec.ts
src/plots/bar/index.ts
src/plots/column/index.ts

fix: column和bar默认type为cat

---

__tests__/bugs/issue-968-spec.ts
src/constant.ts
src/types/axis.ts

feat(axis): add type config axis, it will picked into scale config

---

__tests__/bugs/issue-1684-spec.ts
__tests__/unit/plots/dual-axes/column-spec.ts
__tests__/unit/plots/dual-axes/default-options-spec.ts
__tests__/unit/plots/dual-axes/util/option-spec.ts
examples/area/basic/demo/basic-gradients.ts
examples/area/basic/demo/basic-slider.ts
examples/area/basic/demo/basic.ts
examples/column/percent/demo/basic.ts
examples/dual-axes/column-line/demo/column-line.ts
examples/dual-axes/column-line/demo/column-multi-line.ts
examples/dual-axes/column-line/demo/custom-column-line.ts
examples/dual-axes/column-line/demo/demo-more-1.ts
examples/dual-axes/dual-line/demo/custom-dual-line.ts
examples/dual-axes/dual-line/demo/dual-line.ts
examples/dual-axes/dual-line/demo/dual-multi-line.ts
examples/dual-axes/grouped-column-line/demo/custom-grouped-column-line.ts
examples/dual-axes/grouped-column-line/demo/grouped-column-line.ts
examples/dual-axes/grouped-column-line/demo/grouped-column-multi-line.ts
examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
examples/dual-axes/stacked-column-line/demo/stacked-column-line.ts
examples/dual-axes/stacked-column-line/demo/stacked-column-multi-line.ts
examples/general/theme/demo/dark.ts
examples/line/basic/demo/line-slider.ts
examples/line/basic/demo/line.ts
src/core/plot.ts
src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/constant.ts
src/plots/dual-axes/index.ts
src/plots/dual-axes/util/legend.ts
src/plots/dual-axes/util/option.ts

fix(dual-axes): 双轴图问题走查

---

site/pages/index.less

fix(website): style for bk image

---

src/plots/tiny-area/index.ts
src/plots/tiny-column/index.ts
src/plots/tiny-line/index.ts

feat(tiny-area): update tiny area default color

---

__tests__/bugs/issue-1708-spec.ts
__tests__/unit/plots/bar/legend-spec.ts
__tests__/unit/plots/column/legend-spec.ts
__tests__/unit/plots/ring-progress/index-spec.ts
src/plots/area/adaptor.ts
src/plots/column/adaptor.ts
src/plots/ring-progress/adaptor.ts

bugfix: 走查

---

__tests__/unit/adaptor/geometries/base-spec.ts
__tests__/unit/plots/liquid/liquid-style-spec.ts
__tests__/unit/plots/scatter/size-spec.ts
__tests__/unit/plots/waterfall/index-spec.ts
src/adaptor/geometries/base.ts
src/plots/waterfall/adaptor.ts

feat(mapping): color shape size 字段只去对应的字段即可

---

__tests__/unit/utils/transform/histogram-spec.ts
src/plots/histogram/adaptor.ts
src/utils/transform/histogram.ts

- 去掉histogram的data-set引用
- 增加函数的单测用例

refactor: 去掉histogram的data-set

---

site/pages/index.zh.tsx

fix(404): link 404 on index page

---

docs/common/legend.en.md
docs/common/legend.zh.md

文档错误
fix https://github.com/antvis/G2Plot/issues/1717

docs: legend -> lengend , Unexpected semicolon

---

__tests__/unit/plots/heatmap/axis-spec.ts
__tests__/unit/plots/heatmap/calendar-spec.ts
__tests__/unit/plots/heatmap/shape-spec.ts
__tests__/unit/plots/heatmap/size-spec.ts
__tests__/unit/plots/heatmap/type-spec.ts
src/plots/heatmap/adaptor.ts
src/plots/heatmap/index.ts
src/plots/heatmap/shapes/boundary-polygon.ts
src/plots/heatmap/types.ts

- shapeType 统一为 shape，和其它图形保持一致
- 提取配置到 getDefaultOptions
- 新增 type 类型， 默认使用 polygon.

feat: heatmap

---

__tests__/bugs/issue-1757-spec.ts
__tests__/unit/plots/column/percent-spec.ts
src/utils/tooltip.ts

fix: formatter 样式丢失

---

examples/dual-axes/column-line/API.en.md
examples/dual-axes/column-line/API.zh.md
examples/funnel/basic/API.en.md
examples/funnel/basic/API.zh.md

fix: 订正双轴图&漏斗图文档

---

__tests__/unit/lab-spec.ts
src/index.ts
src/lab.ts
src/plots/radial-bar/adaptor.ts
src/plots/radial-bar/index.ts
src/plots/radial-bar/types.ts

对于没有开发完成的图表，可以暂时先放到 Lab 下面，先做体验，稳定后放到根 export

feat: add lab domain

---

__tests__/unit/plots/dual-axes/legend-spec.ts
__tests__/unit/plots/funnel/compare-spec.ts
examples/dual-axes/grouped-column-line/demo/custom-grouped-column-line.ts
examples/dual-axes/stacked-column-line/demo/custom-stacked-column-line.ts
src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/util/legend.ts

1. 双轴图 column 图例的颜色隐射 fixed #1170 
2. 双轴图支持完全自定义图例

fix: line-column legend color & custom legend

---

examples/bullet/basic/demo/basic.ts

fix: 修复bullet的demo写错问题

---

examples/bar/basic/demo/conversion-tag.ts
examples/column/basic/demo/conversion-tag.ts
src/adaptor/conversion-tag.ts
src/plots/bar/index.ts
src/plots/column/index.ts

fix: adjust default column width ratio

---

__tests__/bugs/issue-1754-spec.ts
__tests__/unit/adaptor/geometries/base-spec.ts
__tests__/unit/plots/dual-axes/stack-spec.ts
__tests__/unit/utils/tooltip-spec.ts
package.json
src/adaptor/geometries/base.ts
src/adaptor/geometries/point.ts
src/index.ts
src/plots/dual-axes/adaptor.ts
src/plots/scatter/adaptor.ts
src/plots/waterfall/adaptor.ts
src/plots/waterfall/index.ts
src/plots/word-cloud/index.ts
src/plots/word-cloud/types.ts
src/utils/tooltip.ts

fix(tooltip): 走查 tooltip 实现逻辑

---

__tests__/unit/plots/gauge/index-spec.ts
src/plots/gauge/adaptor.ts
src/plots/gauge/types.ts

feat(gauge): add indicator = false, to hide the indicator

---

__tests__/unit/plots/sunburst/index-spec.ts
examples/sunburst/basic/demo/basic.ts
examples/sunburst/basic/demo/reflect.ts
src/plots/sunburst/index.ts
src/plots/sunburst/utils.ts

fix: 修复 sunburst tooltip

---

docs/common/meta.en.md

fix: correct spelling for "default"

---

docs/common/meta.en.md

fix: correct spelling for Configuration

---

__tests__/unit/plots/dual-axes/point-spec.ts
__tests__/unit/plots/dual-axes/stack-spec.ts
src/plots/dual-axes/util/geometry.ts

https://github.com/ant-design/ant-design-charts/issues/279

fix: 双轴图 point 颜色映射错误和参数丢失

---

__tests__/unit/plots/histogram/axis-spec.ts
__tests__/unit/plots/histogram/index-spec.ts

test: 提升histogram的测试覆盖率

---

__tests__/unit/plots/area/index-spec.ts
__tests__/unit/plots/area/y-meta-min-max-spec.ts
__tests__/unit/plots/bidirectional-bar/update-spec.ts
__tests__/unit/plots/bidirectional-bar/utils-spec.ts
__tests__/unit/plots/column/update-spec.ts
__tests__/unit/plots/line/index-spec.ts
src/core/plot.ts
src/plots/area/index.ts
src/plots/bar/adaptor.ts
src/plots/bar/index.ts
src/plots/bidirectional-bar/adaptor.ts
src/plots/bidirectional-bar/index.ts
src/plots/bidirectional-bar/utils.ts
src/plots/column/adaptor.ts
src/plots/column/index.ts
src/plots/line/adaptor.ts
src/plots/line/index.ts

fix(update): line, area, bar, column, bidirectional-bar update bugs

---

__tests__/unit/adaptor/connected-area-spec.ts
__tests__/unit/adaptor/conversion-tag-spec.ts
src/adaptor/conversion-tag.ts

修复转化率在图形多次render后由于 component update 的时候存在相同 ID 情况下 update 出错问题。目前是 component 组件要求组件内部的各个 shape 都有自己的 ID

fix(conversion-tag): set an uniqe id for every shape

---

__tests__/unit/plots/word-cloud/index-spec.ts
src/plots/word-cloud/index.ts

chore(word-cloud): 完善测试

---

__tests__/bugs/issue-1870-spec.ts
__tests__/unit/plots/dual-axes/util/option-spec.ts
src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/constant.ts
src/plots/dual-axes/types.ts
src/plots/dual-axes/util/option.ts

fix(#1870): when y are same in dual-axes, axis position is wrong

---

__tests__/unit/core/index-spec.ts
__tests__/utils/dom.ts
docs/manual/plots/scatter.en.md
docs/manual/plots/scatter.zh.md
examples/scatter/basic/demo/custom-shape.ts
examples/scatter/basic/demo/meta.json
src/core/plot.ts

- 散点图、热力图、旭日图API走查
- getChartSize 修改默认值和文档保存一致
- 散点图新增自定义图形 demo

docs: api 走查

---

README.md
README.zh-CN.md

fix: badge img

---

__tests__/unit/plots/scatter/regression-line-spec.ts
__tests__/unit/plots/sunburst/hierarchy/partition-spec.ts
__tests__/unit/plots/sunburst/hierarchy/util-spec.ts
src/plots/scatter/util.ts

test: coverage up

---

__tests__/unit/plots/dual-axes/legend-spec.ts
src/plots/dual-axes/adaptor.ts

feat/duax: 关闭多个图例

---

CHANGELOG.md
package.json

chore: 2.0.9

---

docs/manual/plots/bullet.en.md
docs/manual/plots/bullet.zh.md

- review bullet and histogram docs
- fix docs

docs: fix docs

---

src/plots/area/index.ts
src/plots/histogram/index.ts
src/plots/line/index.ts
src/plots/rose/index.ts

feat(default-options): update default option for plots

---

__tests__/bugs/issue-1909-spec.ts
src/plots/liquid/shapes/liquid.ts

fix(#1909): opacity 配置不生效

---

gatsby-config.js
package.json

* update gatsby-theme-antv version
* just for theme switcher preview test

feat: update gatsby-theme-antv version

---

.github/workflows/mirror.yml
__tests__/unit/plots/multi-view/index-spec.ts
__tests__/unit/plots/stock/tooltip-spec.ts

ref https://github.com/antvis/G2/pull/3014/files

chore: only sync gh-pages to Gitee Mirror

---

__tests__/unit/plots/gauge/shapes/index-spec.ts
src/plots/gauge/adaptor.ts
src/plots/gauge/shapes/gauge.ts

test(gauge): coverage increase

---

__tests__/bugs/issue-292-spec.ts
__tests__/data/sunburst.ts
__tests__/unit/adaptor/conversion-tag-spec.ts
__tests__/unit/plots/area/point-spec.ts
__tests__/unit/plots/heatmap/type-spec.ts
__tests__/unit/plots/sunburst/change-data-spec.ts
__tests__/unit/plots/sunburst/index-spec.ts

test: fix test error when no network

---

examples/scatter/basic/demo/meta.json
examples/scatter/basic/demo/quadrant-tooltip.ts

docs: 补充四象限气泡图

---

.github/workflows/mirror.yml

chore: gitee mirror action

---

examples/case/statistical-charts/demo/funnel.ts
examples/tiny/progress/demo/meta.json
examples/tiny/progress/demo/progress-style.ts
examples/tiny/progress/demo/progress.ts
examples/tiny/ring-progress/demo/meta.json

漏斗图 demo 优化 & 迷你缩略图替换

---

__tests__/bugs/issue-1970-spec.ts
src/plots/word-cloud/index.ts
src/utils/transform/word-cloud.ts

fix(word-cloud): 修复错误的边界值导致的重叠及间隙过大问题

---

__tests__/unit/plots/heatmap/shape-spec.ts
src/plots/heatmap/adaptor.ts
src/plots/heatmap/shapes/circle.ts
src/plots/heatmap/shapes/square.ts

现状： https://g2plot.antv.vision/zh/examples/heatmap/basic#shape
修复态：

fix: 修复热力图颜色映射错误

---

examples/bullet/basic/demo/basic.ts
examples/bullet/basic/demo/color.ts
examples/bullet/basic/demo/grouped.ts
examples/bullet/basic/demo/layout.ts
examples/bullet/basic/demo/stacked.ts
examples/general/state/demo/meta.json
examples/heatmap/density/demo/basic.ts

- 调整子弹图配色
- 更新状态量缩略图
- 调整密度热力图颜色映射、新增图例。

docs: demo走查

---

examples/bidirectional-bar/basic/demo/meta.json
examples/case/statistical-scenario/demo/meta.json
examples/tiny/tiny-area/demo/area-annotation.ts
examples/tiny/tiny-area/demo/basic-area.ts
examples/tiny/tiny-area/demo/filled-area.ts
examples/tiny/tiny-area/demo/meta.json
examples/tiny/tiny-column/demo/basic-column.ts
examples/tiny/tiny-column/demo/column-annotation.ts
examples/tiny/tiny-column/demo/meta.json
examples/tiny/tiny-line/demo/basic-line.ts
examples/tiny/tiny-line/demo/line-annotation.ts
examples/tiny/tiny-line/demo/meta.json

fix: 对称条形图 & 迷你折柱面图 demo

---

examples/heatmap/basic/demo/calendar.ts
examples/heatmap/basic/demo/shape.ts
examples/heatmap/basic/demo/size.ts
examples/heatmap/density/demo/basic.ts

docs: 调整色值

---

examples/area/basic/demo/basic-slider.ts
examples/line/basic/demo/line-point-style.ts
examples/line/basic/demo/meta.json

fix(demo): fix line, area demo

---

examples/case/customize/demo/customize-tooltip.ts
package.json
site/pages/index.zh.tsx

1.  升级网站主题到 1.0.2 版本
2. refactor(demo): 修改自定义demo的tooltip背景色
- close: https://yuque.antfin-inc.com/antv/topics/217
3. fix(website): 修复网站 图表实验室链接 404

daily walkthrough

---

__tests__/unit/plots/scatter/regression-line-spec.ts
docs/common/chart-options.en.md
docs/common/chart-options.zh.md
docs/manual/plots/scatter.en.md
docs/manual/plots/scatter.zh.md
src/plots/scatter/adaptor.ts
src/plots/scatter/types.ts

feat: scatter regression 新增 top 配置

---

__tests__/unit/utils/data-spec.ts
src/utils/data.ts

fix(y-scale): update y scale min, max

---

__tests__/unit/plots/word-cloud/utils-spec.ts
src/plots/word-cloud/types.ts
src/plots/word-cloud/utils.ts

fix(word-cloud): 修复字体权重值都相同时，不显示的问题

---

CHANGELOG.md
package.json
src/index.ts

chore: release 2.2.13

---

examples/line/multiple/demo/line-grid.ts
examples/line/multiple/demo/meta.json

- 新增 axis | annotations 配置demo ，答疑引流。

docs: 新增网格配置demo

---

docs/manual/plots/radial-bar.zh.md
docs/manual/plots/rose.en.md
docs/manual/plots/rose.zh.md
docs/manual/plots/scatter.en.md
docs/manual/plots/scatter.zh.md
docs/manual/plots/sunburst.en.md
docs/manual/plots/sunburst.zh.md
docs/manual/plots/word-cloud.en.md
docs/manual/plots/word-cloud.zh.md

• 图表容器
• 数据映射
• 图形样式
• 图表组件
• 图表事件
• 图表方法
• 图表主题
• 图表交互

feat(docs): plots 文档按照以下格式补全

---

__tests__/unit/plots/word-cloud/utils-spec.ts
src/plots/word-cloud/utils.ts

fix(word-cloud): 修复当宽高为0时浏览器卡死

---

__tests__/unit/plots/line/line-mapping-spec.ts
src/adaptor/geometries/line.ts
src/plots/line/adaptor.ts
src/plots/line/types.ts

feat(line): support lineShape config

---

docs/manual/plugin.en.md
docs/manual/plugin.zh.md

在文档的plugin.md和plugin.en.md增加angular技术栈的g2plot封装收录链接

feat(docs): 增加angular技术栈的g2plot封装收录链接

---

__tests__/bugs/issue-charts-367-spec.ts
src/plots/gauge/adaptor.ts
src/plots/gauge/index.ts

fix(gauge): 仪表盘的 ticks 默认不均匀,且自定义 scale 无效

---

gatsby-browser.js

fix: 修改官网样式覆盖问题

---

docs/common/label.en.md
docs/common/label.zh.md
src/adaptor/geometries/interval.ts

docs: 日常走查

---

examples/case/multi-view/demo/nobel-prize.ts
src/plots/multi-view/adaptor.ts

refactor(demo): 诺贝尔奖可视化 demo 优化

---

__tests__/bugs/issue-2105-spec.ts
src/plots/column/adaptor.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/7856674/102295324-0fe89380-3f86-11eb-95d0-a9e429c4972a.png)  |  ![image](https://user-images.githubusercontent.com/7856674/102295244-f34c5b80-3f85-11eb-9d05-7da97c2cabac.png)  |

fix(2105): fix percent column/bar yAxis lable > 1

---

examples/general/annotation/API.en.md
examples/general/annotation/API.zh.md

docs: 修复文档 404

---

README.md
README.zh-CN.md
docs/manual/introduction.en.md
docs/manual/introduction.zh.md

|----|----|
|  ❌ <img width="538" alt="图片" src="https://user-images.githubusercontent.com/507615/102442887-66c29b80-4060-11eb-8291-0c096a0d0e57.png">  |  ✅  |

docs: fix image url is http

---

__tests__/unit/core/index-spec.ts
src/core/plot.ts

feat: add chart type source in container

---

__tests__/bugs/issue-21111-spec.ts
src/core/plot.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/7856674/102427206-d8441f00-404b-11eb-9b82-6a011231a971.png)  |  ![image](https://user-images.githubusercontent.com/7856674/102427177-c793a900-404b-11eb-93d2-3ad198242fdc.png)  |
```ts
// 重新生效
update({ appendPadding: 48 }); 
```

fix(#2111): appendPadding not update

---

examples/case/multi-view/demo/nobel-prize.ts

fix: 修复网站demo错误

---

__tests__/bugs/issue-2122-spec.ts
src/index.ts
src/plots/bidirectional-bar/adaptor.ts

fix(issue-2122): 修复对称条形图数据为空，报错

---

docs/common/marker.en.md
docs/common/marker.zh.md

docs: 修改图例 marker 配置的说明文档

---

__tests__/unit/adaptor/conversion-tag-spec.ts
__tests__/unit/utils/conversion-spec.ts
src/utils/conversion.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/7856674/103335827-3e4f8e00-4ab1-11eb-9ca0-9d391a5832c3.png)  |  ![image](https://user-images.githubusercontent.com/7856674/103335804-2972fa80-4ab1-11eb-82b9-8e163b1ac271.png)  |
转化率在前后值相同的时候，计算错误。

fix(conversion): conversion calculate error

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.6

---

__tests__/unit/index-spec.ts
src/index.ts

feat(open-ability): 开放通用的 adaptors 给自定义扩展图表使用

---

__tests__/unit/plots/stock/change-data-spec.ts
__tests__/unit/plots/stock/data-spec.ts
src/plots/stock/adaptor.ts
src/plots/stock/index.ts
src/plots/stock/utils.ts

fix: stock股票图重写changeData方法

---

__tests__/unit/plots/tiny-area/change-data-spec.ts
src/plots/tiny-area/index.ts

feat: override tiny-area changeData

feat: tiny area change data

---

docs/manual/plugin.en.md
docs/manual/plugin.zh.md

docs(plugin-plot): 收录 g2plot-lollipop 自定义图表

---

CHANGELOG.md
package.json
src/index.ts

Chore 2.3.7

---

__tests__/unit/plots/radial-bar/index-spec.ts
src/plots/radial-bar/adaptor.ts

- 修复line类型的珏玦图，设置color对point不生效
|----|----|
|![image](https://user-images.githubusercontent.com/15646325/103865117-a5e38a00-50fe-11eb-8c9f-e183da36cf1e.png)  |![image](https://user-images.githubusercontent.com/15646325/103865031-88162500-50fe-11eb-83dd-bef0bd0adb58.png) |

fix(radial-bar): 修复line类型的珏玦图，设置color对point不生效

---

src/plots/sankey/index.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/7856674/103866076-25be2400-5100-11eb-980c-391e49d53e60.png)  |  ![image](https://user-images.githubusercontent.com/7856674/103866119-39698a80-5100-11eb-91db-509e9777f96b.png)  |

feat(sankey): add default label layout

---

examples/more-plots/radial-bar/demo/background.ts
examples/more-plots/radial-bar/demo/basic.ts
examples/more-plots/radial-bar/demo/color.ts
examples/more-plots/radial-bar/demo/line.ts
examples/more-plots/radial-bar/demo/round-corner.ts
src/plots/radial-bar/index.ts

fix(demo): demo 实例容器自适应，不需要加宽高 否则影响动画效果

---

src/plots/progress/adaptor.ts
src/plots/progress/index.ts
src/plots/progress/utils.ts
src/plots/ring-progress/adaptor.ts
src/plots/ring-progress/index.ts

feat(progress): 进度条&环形进度条支持 changeData

---

src/plots/tiny-area/index.ts
src/plots/tiny-column/index.ts
src/plots/tiny-line/index.ts

feat(tiny-plot): 迷你图默认开启动画效果 & public 方法提前

---

__tests__/unit/plots/liquid/statistic-spec.ts
src/plots/liquid/adaptor.ts
src/plots/liquid/index.ts
src/plots/liquid/utils.ts

feat(liquid): 水波图支持动态 changedata

---

__tests__/unit/plots/histogram/change-data-spec.ts
src/plots/histogram/index.ts

|----|----|
|  ![](https://gw.alipayobjects.com/zos/antfincdn/cP7P4FV%24Qy/dynamtic-histogram-before.gif)  |  ![](https://gw.alipayobjects.com/zos/antfincdn/8YCNXIEp6C/dynamtic-histogram-after.gif)  |

feat(histogram): 直方图支持动态 changedata

---

docs/manual/plots/column.en.md
docs/manual/plots/column.zh.md
docs/manual/plots/pie.zh.md

docs(column): 柱状图 图表指引增加一些特性介绍

---

__tests__/unit/plots/radial-bar/change-data-spec.ts
src/plots/radial-bar/index.ts

override the changeData method of Radial-bar plot

feat: 玉珏图重写changeData方法 && 添加单测

---

__tests__/unit/plots/word-cloud/legend-spec.ts
examples/more-plots/word-cloud/demo/douban-2020-movie.ts
examples/more-plots/word-cloud/demo/meta.json
src/plots/word-cloud/adaptor.ts
src/plots/word-cloud/index.ts

|----|----|
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/x0MczjNEWG/298b11e6-731c-458b-97c8-f96c77ebb7c1.png)  |

feat(word-cloud): 词云图支持展示 legend

---

__tests__/bugs/issue-2203-spec.ts
__tests__/unit/plots/progress/utils-spec.ts
src/plots/progress/utils.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/7856674/104404345-65b85780-5595-11eb-97ea-e7c44563da84.png)  |  ![image](https://user-images.githubusercontent.com/7856674/104409990-69061000-55a2-11eb-97d4-c9b23a5c3b6a.png)  |

fix(#2203): crash when percent = NaN

---

site/pages/index.less

|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/104397453-cd67a600-5587-11eb-88dd-2adb5d284b67.png) |  ![image](https://user-images.githubusercontent.com/15646325/104397366-a0b38e80-5587-11eb-8b5d-87d43c0bc543.png) |

docs: 优化图表示例 api 文档样式

---

__tests__/unit/plots/waterfall/change-data-spec.ts
src/plots/waterfall/index.ts

override the changeData method of waterfall plot
|----|----|
|![瀑布图before](https://user-images.githubusercontent.com/24318174/104417963-2bf54a00-55b1-11eb-88b0-3542050226f0.gif)|![瀑布图after](https://user-images.githubusercontent.com/24318174/104417892-108a3f00-55b1-11eb-9d89-d3da3bb7f6ac.gif)|

feat: 重写瀑布图changeData方法 && 添加单测

---

README.md
README.zh-CN.md
docs/manual/contact.en.md
docs/manual/contact.zh.md

docs: 添加钉钉联系方式

---

__tests__/unit/plots/word-cloud/change-data-spec.ts
src/plots/word-cloud/index.ts

override the changeData method of wordCloud plot
|----|----|
|![词云图before](https://user-images.githubusercontent.com/24318174/104425501-b773d880-55bb-11eb-8e2b-67d7765608d6.gif) | ![词云图after](https://user-images.githubusercontent.com/24318174/104425529-c195d700-55bb-11eb-96aa-6f94c32055cf.gif)|

feat: 词云图重写changeData方法 && 添加单测

---

docs/manual/plots/bar.en.md
docs/manual/plots/bar.zh.md
docs/manual/plots/column.en.md
docs/manual/plots/column.zh.md
examples/bar/grouped/demo/corner-radius.ts
examples/bar/grouped/demo/meta.json
examples/column/grouped/demo/corner-radius.ts
examples/column/grouped/demo/meta.json

|----|----|
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/glkLYqZiXS/8f40c2ae-c581-4edc-9572-9609c752ecbb.png)  |
||![](https://gw.alipayobjects.com/zos/antfincdn/vFQNz1dCaD/21d77486-a9a3-4287-bc49-24fc40ad4800.png)|

feat(column): 柱状图支持圆角 & 添加图表指引

---

CHANGELOG.md
package.json
src/index.ts

chore: 2.3.8 & add changelog

---

__tests__/unit/plots/scatter/data-spec.ts
examples/scatter/bubble/demo/bubble-3d.ts
examples/scatter/bubble/demo/meta.json
examples/scatter/bubble/index.en.md
examples/scatter/bubble/index.zh.md
examples/scatter/scatter/demo/meta.json
src/plots/scatter/adaptor.ts
src/plots/scatter/index.ts

**feat(scatter):** 散点图支持动态更新数据 & 添加单测
**docs(bubble):** 散点气泡图提供伪 3D 的demo
|----|----|
| ![](https://gw.alipayobjects.com/zos/antfincdn/dGz8eH13ah/dongtaigengxinshuju-before.gif)  |  ![](https://gw.alipayobjects.com/zos/antfincdn/5yJfMS4PBK/dongtaigengxinshuju-after.gif)  |

feat: 散点图支持动态更新数据 & 添加单测

---

__tests__/unit/plots/waterfall/label-spec.ts
src/plots/waterfall/adaptor.ts

feat(waterfall): 瀑布图回调参数增加分类字段

---

__tests__/unit/plots/pie/index-spec.ts
src/adaptor/common.ts
src/plots/multi-view/types.ts
src/plots/pie/adaptor.ts

fix(issue-2216): 饼图默认强制关闭 tooltip shared

---

__tests__/unit/plots/scatter/size-spec.ts
src/plots/scatter/adaptor.ts

|----|----|
| <img  src="https://user-images.githubusercontent.com/31396322/104913549-ba5e3700-59c8-11eb-9af7-a5fe343ef91a.png" width="400" /> | <img  src="https://user-images.githubusercontent.com/31396322/104913563-bf22eb00-59c8-11eb-9359-7dcdc9a62d56.png" width="400" /> |

fix: 散点图新增默认size

---

src/plots/word-cloud/index.ts

fix(word-cloud): 由于无法判断首次 render 是否ready，changedata时，如果有 imageMask，重渲染

---

CHANGELOG.md
package.json
src/index.ts

chore: changelog

---

docs/common/axis.zh.md
docs/common/tooltip.en.md
docs/common/tooltip.zh.md

docs: 文档层级错误 & 修改 tooltip domStyles 类型定义

---

src/index.ts

fix: export multi view options

---

__tests__/unit/plots/scatter/size-spec.ts
src/plots/scatter/adaptor.ts

|----|----|
|  <img src="https://user-images.githubusercontent.com/31396322/105675523-35bd6c80-5f24-11eb-97b4-a2edf9b54099.png" width="337" />   |   <img src="https://user-images.githubusercontent.com/31396322/105675593-4cfc5a00-5f24-11eb-89fa-304d285fc75f.png" width="337" />  |

fix: 修复散点图 size 回调不生效

---

__tests__/bugs/issue-2180-spec.ts
__tests__/unit/plots/bidirectional-bar/data-spec.ts
__tests__/unit/plots/bidirectional-bar/layout-spec.ts
__tests__/unit/plots/bidirectional-bar/utils-spec.ts
src/plots/bidirectional-bar/adaptor.ts
src/plots/bidirectional-bar/utils.ts

对称条形图处理数据方法简化改造，方便后续处理 changeData

---

__tests__/bugs/issue-2264-spec.ts
__tests__/unit/plots/waterfall/component-spec.ts
src/plots/waterfall/adaptor.ts

fix(issue-2264): 修复瀑布图 formatter 不生效

---

__tests__/unit/plots/gauge/shapes/index-spec.ts
docs/api/plots/gauge.en.md
docs/api/plots/gauge.zh.md
docs/manual/plots/gauge.en.md
docs/manual/plots/gauge.zh.md
examples/progress-plots/gauge/demo/custom-meter-step.ts
examples/progress-plots/gauge/demo/meta.json
examples/progress-plots/gauge/demo/meter-gauge.ts
src/plots/gauge/adaptor.ts
src/plots/gauge/constant.ts
src/plots/gauge/index.ts
src/plots/gauge/shapes/gauge.ts
src/plots/gauge/shapes/meter-gauge.ts
src/plots/gauge/types.ts

feat(gauge): 支持配置米轨仪表盘

---

docs/common/theme.en.md
docs/common/theme.zh.md
examples/general/theme/demo/register-theme.ts
gatsby-config.js

docs: 图表案例导航顺序调整 & 主题文档修整

---

CHANGELOG.md
package.json
src/index.ts

chore: 2.3.10 changelog

---

docs/manual/plugin.en.md
docs/manual/plugin.zh.md

docs: add pyg2plot

---

__tests__/unit/plots/box/change-data-spec.ts
__tests__/unit/plots/box/outliers-spec.ts
__tests__/unit/plots/box/utils-spec.ts
src/plots/box/adaptor.ts
src/plots/box/constant.ts
src/plots/box/index.ts
src/plots/box/utils.ts

1、重写箱线图changeData方法
2、完善箱线图异常值view的scale度量不一致
|----|----|
| ![箱线图before](https://user-images.githubusercontent.com/24318174/106113146-16734900-6189-11eb-8167-166c347d0efd.gif) | ![箱线图after](https://user-images.githubusercontent.com/24318174/106113179-212dde00-6189-11eb-854f-1b25b6f99eef.gif) |

Feat box plot change data

---

site/pages/index.zh.tsx

docs: fix link 404

---

docs/api/plots/dual-axes.en.md
docs/api/plots/dual-axes.zh.md

docs(dual-axes): 双轴图补充meta使用示例

---

docs/api/options/interactions.en.md
docs/api/options/interactions.zh.md
docs/common/interactions.en.md
docs/common/interactions.zh.md

docs(interactions): 交互相关的 api 文档补充

---

__tests__/bugs/bar-changedata-spec.ts
__tests__/unit/plots/bar/change-data-spec.ts
src/plots/bar/adaptor.ts
src/plots/bar/index.ts
src/plots/bar/utils.ts

|----|----|
| ![image](https://user-images.githubusercontent.com/15646325/107176233-bcd11100-6a09-11eb-9027-fb44eb8e1484.png) |  ✅  |

fix(bar): bar plot not transformData before changedata

---

__tests__/bugs/issue-2220-spec.ts
__tests__/unit/plots/pie/data-spec.ts
__tests__/unit/plots/pie/statistic-spec.ts
__tests__/unit/plots/pie/tooltip-spec.ts
src/plots/pie/adaptor.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/107135546-98f0cb00-6936-11eb-8f46-55bd9ad9b5d1.png)  |  ![image](https://user-images.githubusercontent.com/15646325/107135551-a908aa80-6936-11eb-84aa-66f06866f185.png)  |
|![image](https://user-images.githubusercontent.com/15646325/107135592-f2f19080-6936-11eb-9d4e-57c7f7cb9e70.png)|![image](https://user-images.githubusercontent.com/15646325/107135581-e5d4a180-6936-11eb-8a6f-a67176eb8a01.png)|
|![image](https://user-images.githubusercontent.com/15646325/107135613-246a5c00-6937-11eb-8deb-95f4d23a2820.png)|![image](https://user-images.githubusercontent.com/15646325/107135617-2e8c5a80-6937-11eb-95ee-aeb200dc5ed9.png)|

fix: pie tooltip

---

__tests__/unit/plots/column/scrollbar-spec.ts
docs/api/components/scrollbar.en.md
docs/api/components/scrollbar.zh.md
docs/common/scrollbar.en.md
docs/common/scrollbar.zh.md
examples/general/theme/demo/custom-theme.ts
examples/general/theme/demo/meta.json
package.json

docs: scrollbar style & lock editor version

---

__tests__/unit/plots/heatmap/state-spec.ts
docs/api/plots/area.en.md
docs/api/plots/area.zh.md
docs/api/plots/bar.en.md
docs/api/plots/bar.zh.md
docs/api/plots/column.en.md
docs/api/plots/column.zh.md
docs/api/plots/heatmap.en.md
docs/api/plots/heatmap.zh.md
docs/api/plots/histogram.en.md
docs/api/plots/histogram.zh.md
docs/api/plots/line.en.md
docs/api/plots/line.zh.md
docs/api/plots/pie.en.md
docs/api/plots/pie.zh.md
docs/api/plots/rose.en.md
docs/api/plots/rose.zh.md
docs/api/plots/waterfall.en.md
docs/api/plots/waterfall.zh.md
docs/common/state-style.en.md
docs/common/state-style.zh.md
gatsby-config.js
src/plots/area/adaptor.ts
src/plots/column/adaptor.ts
src/plots/heatmap/adaptor.ts
src/plots/histogram/adaptor.ts

|----|----|
|  ❌  |  ![image](https://user-images.githubusercontent.com/15646325/108317016-a9d3f300-71f8-11eb-8f68-0db3c646e6c8.png)  |

feat(state-style): 若干图表支持 state 设置样式 & 增加文档

---

__tests__/unit/plots/radial-bar/label-spec.ts
src/plots/radial-bar/adaptor.ts

feat(radial-bar): add radial bar label adaptor

---

docs/common/bar-style.zh.md
docs/common/column-style.zh.md
docs/manual/plots/bar.en.md
docs/manual/plots/bar.zh.md
docs/manual/plots/column.en.md
docs/manual/plots/column.zh.md
examples/bar/basic/demo/bar-background.ts
examples/bar/basic/demo/meta.json
examples/column/stacked/demo/column-background.ts
examples/column/stacked/demo/meta.json

docs: 增加 column，bar 背景色设置的demo & 图表指引

---

__tests__/data/treemap.ts
__tests__/unit/plots/sunburst/index-spec.ts
__tests__/unit/plots/treemap/color-spec.ts
__tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
__tests__/unit/plots/treemap/lable-spec.ts
__tests__/unit/plots/treemap/sort-spec.ts
__tests__/unit/plots/treemap/tooltip-spec.ts
__tests__/unit/plots/treemap/utils-spec.ts
src/plots/treemap/adaptor.ts
src/utils/hierarchy/treemap.ts
src/utils/hierarchy/types.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/7856674/108502526-e6354b00-72ed-11eb-94f2-e63afd7850a4.png)  |  ![image](https://user-images.githubusercontent.com/7856674/108502483-d0c02100-72ed-11eb-8ca9-5193b8cc2d31.png)  |

feat: treemap layout optimize

---

examples/case/customize/demo/desire-heatmap.ts
examples/case/customize/demo/meta.json

docs(heatmap): 添加热力新年 demo

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.12

---

__tests__/unit/plots/ring-progress/index-spec.ts
src/plots/progress/adaptor.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/108928630-715f6980-767d-11eb-84d2-88015408adf9.png)  |  ![image](https://user-images.githubusercontent.com/15646325/108928586-5c82d600-767d-11eb-84ce-b273ffd14a02.png)  |

feat(ring-progress): 将环形进度条的z-index进行调整,默认置顶 shape0

---

__tests__/unit/plots/rose/coordinate-spec.ts
docs/api/plots/rose.en.md
docs/api/plots/rose.zh.md
src/plots/rose/adaptor.ts
src/plots/rose/types.ts

feat: 玫瑰图新增 startAngle、endAngle

---

__tests__/bugs/issue-2352-spec.ts
__tests__/unit/plots/sankey/index-spec.ts
src/plots/sankey/adaptor.ts

fix(sankey): shape order same with data, layout space

---

gatsby-browser.js
package.json

chore: fix website build error

---

docs/common/axis.en.md
docs/common/axis.zh.md

docs(axis): 坐标轴文档

---

docs/api/options/events.zh.md
docs/common/slider.en.md
docs/common/slider.zh.md

docs(slider): 缩略轴支持配置 handler 样式 & 增加 api 文档说明

---

__tests__/unit/plots/treemap/basic-spec.ts
src/plots/treemap/index.ts

feat: treemap 提供 changeData 能力

---

__tests__/unit/plots/bidirectional-bar/change-data-spec.ts
src/plots/bidirectional-bar/index.ts

添加对称条形图的changeData方法，并添加单测
|----|----|
| ![对称条形图before](https://user-images.githubusercontent.com/24318174/109143397-f42a1680-779a-11eb-92fe-bd3fc58239d8.gif)| ![对称条形图after](https://user-images.githubusercontent.com/24318174/109143448-fe4c1500-779a-11eb-8703-3feaff1b8f48.gif)|

Feat bidirectional bar change data

---

__tests__/unit/plots/treemap/interactions/view-zoom-spec.ts
__tests__/unit/plots/treemap/utils-spec.ts
__tests__/unit/utils/hierarchy/treemap-spec.ts
docs/api/plots/treemap.en.md
docs/api/plots/treemap.zh.md
examples/more-plots/treemap/demo/treemap-nest.ts
src/plots/treemap/adaptor.ts
src/plots/treemap/utils.ts
src/utils/hierarchy/treemap.ts

允许设置纵横比
|----|----|
|  <img width="411" alt="ratio_default" src="https://user-images.githubusercontent.com/11748654/109248691-3a29bd80-7821-11eb-94c9-2d90530bab6a.png"> |  <img width="412" alt="ratio_1" src="https://user-images.githubusercontent.com/11748654/109248706-401f9e80-7821-11eb-9b17-9f296e6b36f1.png">  |
| 默认纵横比(黄金分割）| 设置纵横比为 1 |

treemap 允许设置纵横比 & 滚动时阻止默认事件

---

.github/workflows/build.yml
CHANGELOG.md
package.json
src/index.ts
src/plots/sankey/types.ts

chore: new version

---

docs/manual/plugin.en.md
docs/manual/plugin.zh.md

|----|----|
|  ![image](https://user-images.githubusercontent.com/6930280/109749926-7a6caf80-7c16-11eb-8c17-a380e8e333bc.png) | ![image](https://user-images.githubusercontent.com/6930280/109752318-287a5880-7c1b-11eb-8b55-cedd2520609a.png)
|

docs: update plugin

---

docs/common/theme.en.md
docs/common/theme.zh.md
site/pages/index.less

docs(theme): 补充主题样式表的 api 使用文档

---

.github/workflows/build.yml
docs/common/interactions.en.md
docs/common/interactions.zh.md

docs(interactions): 补充交互配置文档

---

__tests__/bugs/issue-2229-spec.ts
src/plots/bullet/adaptor.ts

fix: bullet的target支持回调函数处理

---

__tests__/bugs/issue-2220-spec.ts
__tests__/bugs/issue-2375-spec.ts
__tests__/unit/plots/gauge/utils-spec.ts
__tests__/unit/plots/pie/annotation-spec.ts
__tests__/unit/plots/pie/html-statistic-spec.ts
__tests__/unit/plots/pie/interaction-spec.ts
__tests__/unit/plots/pie/statistic-spec.ts
__tests__/unit/plots/ring-progress/index-spec.ts
src/plots/pie/adaptor.ts
src/plots/pie/interactions/index.ts
src/plots/pie/interactions/pie-statistic-action.ts
src/utils/statistic.ts

|----|----|
|  ![](https://gw.alipayobjects.com/zos/antfincdn/iVvWIH2Cdc/before-bingtuzhongxinwenbenxiangying%252520custom-html.gif)  |  ![](https://gw.alipayobjects.com/zos/antfincdn/7gl5rLocGe/bingtuzhongxinwenbenxiangying%252520custom-html.gif)  |

fix(#2375): 修复饼图中心文本交互没有使用custom-html

---

__tests__/bugs/issue-2220-spec.ts
__tests__/unit/plots/pie/data-spec.ts
__tests__/unit/plots/pie/tooltip-spec.ts
docs/api/components/tooltip.en.md
src/plots/pie/adaptor.ts
src/plots/pie/utils.ts

fix(pie-tooltip): tooltip 默认设置fields和formatter只针对全0场景

---

CHANGELOG.md
package.json
src/index.ts

chore: 2.3.14 changelog

---

__tests__/unit/plots/liquid/liquid-shape-spec.ts
__tests__/unit/plots/liquid/statistic-spec.ts
package.json
src/index.ts
src/utils/statistic.ts

fix(liquid): annotation width

---

docs/api/plots/gauge.en.md
docs/common/statistic.en.md
docs/common/statistic.zh.md
examples/progress-plots/gauge/demo/basic.ts

docs: statistic 英文文档完善

---

docs/api/options/theme.en.md
docs/api/options/theme.zh.md

docs(theme): 文档补充主题配置参考链接

---

__tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
src/plots/treemap/interactions/treemap-drill-down.ts

|----|----|
|  ![upser_before](https://user-images.githubusercontent.com/11748654/111255573-4bacfb00-8652-11eb-91b8-a3fa32a0722f.gif) |  ![changesize_after](https://user-images.githubusercontent.com/11748654/111255592-54053600-8652-11eb-84f1-1e9c75546528.gif)|

[矩形树图] changesize 时重绘面包屑

---

__tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
src/plots/treemap/index.ts
src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
src/plots/treemap/utils.ts

调用 changeData 接口时，清空 treemap 面包屑
|----|----|
|  <img width="573" alt="屏幕快照 2021-03-16 12 30 24" src="https://user-images.githubusercontent.com/11748654/111256179-751a5680-8653-11eb-9b9a-61e7bcb3d870.png"> |  <img width="560" alt="屏幕快照 2021-03-16 12 30 34" src="https://user-images.githubusercontent.com/11748654/111256191-78addd80-8653-11eb-8ca0-19b5b6385a31.png"> |
| 解读：changeData 时reset面包屑|

[fix] Treemap 面包屑适配 changedata

---

docs/common/scrollbar.en.md
docs/common/scrollbar.zh.md

docs(scrollbar): 补充滚动条滑块的高亮色文档

---

__tests__/unit/plots/treemap/interactions/treemap-drill-down-spec.ts
__tests__/unit/plots/treemap/utils-spec.ts
src/plots/treemap/adaptor.ts
src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
src/plots/treemap/utils.ts

Fix treemap update

---

CHANGELOG.md
package.json
src/index.ts

chore: 2.3.17 & changelog

---

docs/api/plots/liquid.en.md
docs/api/plots/liquid.zh.md

修改了水波图自定义形状 API 案例中对参数的注释，主要是对参数 x 和 y 的注释。

docs(liquid): update comments for custom shape API

---

.github/workflows/build.yml
__tests__/bugs/issue-2064-spec.ts
__tests__/bugs/issue-2220-spec.ts
__tests__/bugs/issue-2260-spec.ts
__tests__/bugs/issue-2267-spec.ts
__tests__/unit/adaptor/conversion-tag-spec.ts
__tests__/unit/adaptor/geometries/interval-spec.ts
__tests__/unit/core/index-spec.ts
__tests__/unit/plots/area/limit-in-plot-spec.ts
__tests__/unit/plots/bar/index-spec.ts
__tests__/unit/plots/column/limit-in-plot-spec.ts
__tests__/unit/plots/line/line-mapping-spec.ts
__tests__/unit/plots/pie/label-spec.ts
__tests__/unit/plots/pie/tooltip-spec.ts
__tests__/unit/plots/scatter/tooltip-spec.ts
__tests__/unit/plots/word-cloud/change-data-spec.ts
__tests__/unit/plots/word-cloud/legend-spec.ts
package.json

chore: update build workflows node & add jest maxWorkers

---

__tests__/unit/plots/word-cloud/change-data-spec.ts
__tests__/unit/plots/word-cloud/legend-spec.ts

fix: 尝试修复词云图单测

---

__tests__/unit/plots/dual-axes/state-spec.ts
__tests__/unit/utils/geometry-spec.ts
src/plots/dual-axes/index.ts
src/utils/geometry.ts
src/utils/index.ts

|----|----|
|  <img width="757" alt="屏幕快照 2021-04-02 20 09 16" src="https://user-images.githubusercontent.com/11748654/113415357-9ae48100-93f1-11eb-8cab-e8be12adc18f.png"> | <img width="753" alt="屏幕快照 2021-04-02 20 08 43" src="https://user-images.githubusercontent.com/11748654/113415329-8f915580-93f1-11eb-9b16-5e4e1ddc5a67.png"> |  
| 解读: 适配双轴图的 setState |

feat: 为双轴图增加 setState 功能

---

src/plots/treemap/interactions/actions/treemap-drill-down-action.ts

fix(issue-2486): 不直接引用 @antv/matrix-util, 使用 G2 的 Util

---

__tests__/bugs/issue-2422-spec.ts
src/plots/gauge/adaptor.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/114289669-6be2a500-9aac-11eb-8d40-77f4e61c582f.png)|  ![image](https://user-images.githubusercontent.com/15646325/114289676-7735d080-9aac-11eb-8e59-f312066c3c75.png)|

fix(gauge-theme): 仪表盘主题需要放在第一个设置，否则设置主题会失效

---

docs/api/multi-view.en.md
docs/api/multi-view.zh.md

docs: 文档错误

---

__tests__/unit/plots/sankey/layout-spec.ts
src/plots/sankey/layout.ts
src/plots/sankey/sankey/sankey.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/7856674/114390972-7c3c7200-9bc9-11eb-96b3-0bd27b4dc84e.png)  |  ![image](https://user-images.githubusercontent.com/7856674/114391457-17cde280-9bca-11eb-9642-08593f0288d1.png)  |
在自定义 depth 的时候，如果 depth 小于 maxDepth，则出现有侧大量空白。

fix(sankey): depth is not right

---

CHANGELOG.md
package.json
src/index.ts

chore: update change log

---

__tests__/unit/plots/dual-axes/color-spec.ts

fix: 修复双轴图单测

---

examples/relation-plots/chord/API.en.md
examples/relation-plots/chord/API.zh.md

docs(chord): 和弦图增加examples处的文档

---

CHANGELOG.md
gatsby-config.js
package.json
src/index.ts

chore: 2.319 & changelog

---

gatsby-config.js

docs: 修改 theme-set 链接

---

examples/progress-plots/bullet/demo/basic.ts

docs: 子弹图提供自定义 ticks 的 demo

---

gatsby-config.js

modify url

---

docs/common/chord.zh.md
docs/common/theme.en.md
docs/common/theme.zh.md
src/index.ts
src/plots/chord/adaptor.ts
src/utils/transform/chord.ts

feat(chord): 和弦图增加 state 通道 & 文档移除 color 配置

---

docs/api/plots/liquid.en.md
docs/api/plots/pie.en.md
docs/api/plots/progress.en.md
docs/api/plots/ring-progress.en.md
docs/common/theme.en.md
docs/common/theme.zh.md
docs/manual/plots/bullet.en.md
docs/manual/plots/gauge.en.md

docs: 日常文档走查

---

__tests__/unit/plots/heatmap/index-spec.ts
__tests__/unit/plots/heatmap/theme-spec.ts
__tests__/unit/plots/word-cloud/change-data-spec.ts
examples/heatmap/basic/demo/calendar.ts
src/constant.ts
src/plots/heatmap/adaptor.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/117093661-286e1480-ad94-11eb-81be-50cea3ceb8b0.png) |  ![image](https://user-images.githubusercontent.com/15646325/117093668-3328a980-ad94-11eb-9f69-942153c4c6d6.png)  |
| 热力图默认连续色板不兼容，需要使用旧版的，请手动配置：`color: '#BAE7FF-#1890FF-#0050B3'`|

feat(heatmap): 热力图主题色默认从 theme 中获取连续色板

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.20

---

gatsby-config.js
package.json
src/index.ts

chore: 2.3.21, close 'side-effects' temporary

---

gatsby-config.js

网站 version 切换按钮显示实际版本
|----|----|
|  ❌  |  ✅  |
|  ![image](https://user-images.githubusercontent.com/29775873/118393609-9d81f980-b672-11eb-98ac-ab93ac86e36c.png) | ![image](https://user-images.githubusercontent.com/29775873/118393636-a96dbb80-b672-11eb-98e5-fd4a37c3967e.png) |

chore: use real version

---

__tests__/unit/plots/facet/use-plot-spec.ts
__tests__/unit/plots/heatmap/tooltip-spec.ts
src/plots/heatmap/adaptor.ts

refactor heatmap

---

__tests__/bugs/issue-2502-spec.ts
src/plots/bidirectional-bar/adaptor.ts

fix(issue-2502): 修复对称条形图 axis 设置

---

__tests__/unit/plots/gauge/statistic-spec.ts
__tests__/unit/plots/liquid/statistic-spec.ts
__tests__/unit/plots/pie/statistic-spec.ts
__tests__/unit/plots/ring-progress/statistic-spec.ts
__tests__/unit/utils/statistic-spec.ts
docs/api/components/slider.zh.md
docs/api/components/statistic.en.md
docs/api/components/statistic.zh.md
docs/common/statistic.en.md
docs/common/statistic.zh.md
examples/pie/donut/demo/basic.ts
src/plots/gauge/adaptor.ts
src/plots/liquid/adaptor.ts
src/plots/liquid/constants.ts
src/plots/pie/adaptor.ts
src/plots/ring-progress/adaptor.ts
src/plots/ring-progress/constants.ts
src/types/statistic.ts
src/utils/statistic.ts

|  What  |  Screenshot  |
|----|----|
|  增加 **Statistic** 说明  |  ![image](https://user-images.githubusercontent.com/15646325/118920346-db2f9c80-b968-11eb-8bf7-1efe4b054f22.png) |

feat(statistic): 中心统计文本支持 content 设置

---

__tests__/bugs/issue-2573-spec.ts
docs/common/point-style.en.md
docs/common/point-style.zh.md
src/plots/radar/adaptor.ts
src/types/state.ts

|----|----|
| ![image](https://user-images.githubusercontent.com/15646325/119222459-0a8c0800-bb27-11eb-880f-efcc0bfbe9ff.png)|  ![image](https://user-images.githubusercontent.com/15646325/119222420-e6c8c200-bb26-11eb-8488-8284574d52ad.png)|

fix(#2573): 修复雷达图设置 point state 状态样式不生效

---

.github/workflows/auto-inspection.yml

提交 PR 到 master 或者修改 PR 代码时会触发 surge 。

feat: 补充自动巡检 action

---

__tests__/unit/utils/view-spec.ts
src/plots/mix/interactions/association.ts
src/utils/index.ts
src/utils/view.ts

Enhance testcases

---

__tests__/unit/plots/box/tooltip-spec.ts
docs/common/legend-cfg.en.md
docs/common/legend-cfg.zh.md
examples/more-plots/box/demo/meta-alias.ts
examples/more-plots/box/demo/meta.json
src/plots/box/adaptor.ts
src/plots/box/constant.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/119442685-e0229080-bd5a-11eb-9fa5-75c00941156a.png)  |  ![image](https://user-images.githubusercontent.com/15646325/119442721-ed3f7f80-bd5a-11eb-97f3-34f925c5e434.png)  |

feat(box): 重构和增强箱线图

---

.github/workflows/auto-inspection.yml
docs/manual/faq.en.md
docs/manual/faq.zh.md

docs: add browser compatibility in FAQ

---

examples/more-plots/word-cloud/demo/basic.ts

fix: 使用 mock 数据

---

docs/manual/faq.zh.md

docs: fix typo in the faq.zh.md

---

__tests__/unit/core/global-spec.ts
__tests__/unit/core/locale-spec.ts
__tests__/unit/utils/template-spec.ts
jest.setup.js
package.json
src/core/global.ts
src/core/locale.ts
src/core/plot.ts
src/index.ts
src/locales/en_US.ts
src/locales/zh_CN.ts
src/plots/funnel/adaptor.ts
src/plots/pie/adaptor.ts
src/plots/waterfall/adaptor.ts
src/plots/waterfall/constant.ts
src/types/common.ts
src/types/index.ts
src/types/locale.ts
src/utils/template.ts

- **feat(i18n):** support `locale` config, and global config
|----|----|
|  ❌  |  ✅  |

feat: locale 支持

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/question.md

chore: 添加 issue-template

---

docs/api/plots/radar.en.md
docs/api/plots/radar.zh.md

|----|----|
|  ❌  |  ✅  |
修改依据:
https://github.com/antvis/G2Plot/blob/8c5c3e2a74dc5cf5f42065249b29b542edc5fae7/src/plots/radar/types.ts#L10

docs: Radar seriesField字段修复为非必需

---

CHANGELOG.md
docs/api/components/statistic.en.md
docs/api/components/statistic.zh.md
package.json
src/index.ts

chore: v2.3.22 & changelog

---

__tests__/unit/plots/stock/style-spec.ts
docs/api/plots/stock.en.md
docs/api/plots/stock.zh.md
examples/more-plots/stock/demo/custom-style.ts
src/plots/stock/adaptor.ts
src/plots/stock/types.ts

fix: rename style to stockStyle

---

docs/common/crosshairs-text.en.md
docs/common/crosshairs-text.zh.md
examples/more-plots/stock/demo/slider.ts
examples/more-plots/treemap/demo/drill-down.ts

fix(docs): 修复文档 demo 无限增大

---

__tests__/unit/plots/violin/change-data-spec.ts
src/plots/violin/adaptor.ts

fix(violin): 修复小提琴图数据为空时，渲染直接抛出 error

---

.github/workflows/contributor-helper.yml

chore: update contributor-helper.yml

---

__tests__/unit/plots/funnel/index-spec.ts
__tests__/unit/plots/funnel/style-spec.ts
docs/api/plots/funnel.en.md
docs/api/plots/funnel.zh.md
docs/common/plot-cfg.en.md
docs/common/plot-cfg.zh.md
examples/more-plots/funnel/demo/meta.json
examples/more-plots/funnel/demo/pyramid.ts
examples/more-plots/funnel/demo/static-field.ts
examples/plugin/multi-view/demo/composite-funnel.ts
examples/plugin/multi-view/demo/meta.json
src/locales/en_US.ts
src/plots/funnel/adaptor.ts
src/plots/funnel/constant.ts
src/plots/funnel/geometries/basic.ts
src/plots/funnel/geometries/compare.ts
src/plots/funnel/geometries/dynamic-height.ts
src/plots/funnel/index.ts
src/plots/funnel/types.ts
src/plots/mix/utils.ts

|----|----|
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/SbR2Vn52G6/02155166-d38c-4f32-825e-720ec25804e0.png)  |

refactor(funnel): 支持尖底漏斗图以及样式设置

---

__tests__/unit/plots/chord/state-spec.ts
src/plots/chord/index.ts

fix(chord): 修复和弦图 state 设置不生效

---

__tests__/unit/plots/scatter/legend-spec.ts

postion -> position
|----|----|
|  ❌  |  ✅  |

fix: typo in legend-spec.ts

---

__tests__/unit/plots/chord/state-spec.ts

fix(chord): 修复单测问题

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.24 & changelog

---

__tests__/bugs/issue-2616-spec.ts
src/plots/funnel/geometries/common.ts

fix: funnel with empty data, #2616

---

docs/api/plots/bar.en.md
docs/api/plots/bar.zh.md
docs/api/plots/column.en.md
docs/api/plots/column.zh.md
docs/api/plots/dual-axes.zh.md

docs: 文档修整，slider 对应缩略轴

---

CHANGELOG.md
package.json
src/index.ts

chore: 2.3.25 & changelog

---

examples/more-plots/circle-packing/demo/meta.json
examples/more-plots/stock/demo/meta.json
examples/more-plots/sunburst/demo/meta.json
examples/more-plots/treemap/demo/drill-down.ts
examples/more-plots/violin/demo/meta.json
examples/plugin/facet/demo/meta.json
gatsby-config.js
package.json

docs: 更新 antv-gastby-theme 版本 & 更新网站公告

---

docs/common/connected-area.en.md
docs/common/connected-area.zh.md
examples/column/stacked/demo/connect-area.ts
examples/column/stacked/demo/meta.json
src/adaptor/connected-area.ts

feat(connected-area): 联通区域支持样式配置

---

examples/column/stacked/demo/annotation-label.ts
examples/column/stacked/demo/meta.json

docs(column):  新增堆叠的柱状图展示总数 label 的 demo

---

CHANGELOG.md
package.json
src/index.ts

chore: 2.3.26 & changelog

---

src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/util/render-sider.ts

refactor: 函数命名修正

---

docs/common/legend-cfg.en.md
docs/common/legend-cfg.zh.md

docs(legend): 图例增加宽度,高度容器按照比例设置大小参数

---

docs/common/legend-cfg.en.md
docs/common/legend-cfg.zh.md

itemName、itemValue 支持对 style 进行回调。https://github.com/antvis/g2/pull/3529
|----|----|
|  ❌  |  ![image](https://user-images.githubusercontent.com/15646325/126441707-eb64bbf1-90b7-48c5-b26e-df64e2ddbefb.png)  |

docs(legend): 图例 itemName, itemValue 增加 style 回调

---

CHANGELOG.md
package.json
src/index.ts

choreL: v2.3.27

---

docs/api/plots/heatmap.en.md
docs/api/plots/heatmap.zh.md

docs(heatmap): 热力图补充密度热力图说明：color、style callback 以及 state 不可用

---

docs/api/plots/dual-axes.en.md
docs/api/plots/dual-axes.zh.md

fix(dual-axes): 修改双轴图 annotations 文档

---

__tests__/unit/plots/pixel-plot/tooltip-spec.ts
src/pixels/components/tooltip.ts
src/pixels/constant.ts
src/pixels/mock/data.ts
src/pixels/type.ts
src/pixels/util/canvas.ts

已经支持的配置：
（tooltipItems内容暂时使用mock数据）
|----|----|
|  ❌  |  ✅  |

feat(tooltip): 支持基本title和fields等配置，添加crosshair和markers

---

__tests__/unit/plots/funnel/state-spec.ts
src/plots/funnel/geometries/basic.ts
src/plots/funnel/geometries/compare.ts
src/plots/funnel/geometries/dynamic-height.ts
src/plots/funnel/index.ts

fix(funnel): 漏斗图增加状态样式设置

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.28 & changelog

---

CHANGELOG.md
docs/common/legend-cfg.en.md
docs/common/legend-cfg.zh.md
examples/component/legend/demo/legend-flippage.ts
examples/component/legend/demo/meta.json

feat(legend): 图例支持多行分页

---

__tests__/unit/plots/treemap/color-spec.ts
docs/api/plots/treemap.en.md
docs/api/plots/treemap.zh.md
src/plots/treemap/adaptor.ts
src/plots/treemap/types.ts

在 Treemap 中暴露 rawFields 配置项
|----|----|
|  <img width="278" alt="截屏2021-08-03 17 14 03" src="https://user-images.githubusercontent.com/11748654/127990582-53c74c2c-3ab4-4002-a267-e27b8e9acb0d.png"> |  <img width="367" alt="截屏2021-08-03 17 13 06" src="https://user-images.githubusercontent.com/11748654/127991136-afa79906-63d6-4778-a1fb-e9d7d7d5bb1f.png"> |

issue-2748: treemap color function apply rawFields

---

__tests__/unit/plots/sankey/state-spec.ts
docs/api/plots/sankey.en.md
docs/api/plots/sankey.zh.md
examples/relation-plots/sankey/demo/meta.json
examples/relation-plots/sankey/demo/set-state.ts
src/plots/sankey/adaptor.ts
src/plots/sankey/index.ts
src/plots/sankey/types.ts

✅ 新增 nodeState & edgeState
✅ 文档
|----|----|
|  ❌  |  ✅  |

feat(sankey): 桑基图支持 state 配置

---

src/adaptor/pattern.ts
src/plugin/pattern/index.ts
src/plugin/pattern/line.ts
src/plugin/pattern/pattern.ts
src/types/attr.ts
src/types/common.ts

feat: 初始化pattern

---

gatsby-config.js
src/core/plot.ts

fix: 修复错误 & 更新官网展示 github

---

docs/common/tooltip.en.md
docs/common/tooltip.zh.md

fix: 修复custom tooltip导致容器无限增大

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.29 & changelog

---

examples/pie/basic/demo/basic.ts
package.json
src/adaptor/pattern.ts
src/core/plot.ts
src/index.ts
src/plots/pie/adaptor.ts
src/plugin/pattern/base.ts
src/plugin/pattern/dot.ts
src/plugin/pattern/index.ts
src/plugin/pattern/line.ts
src/plugin/pattern/pattern.ts
src/types/attr.ts
src/types/common.ts

feat(pattern): 增加可配置的dot贴图，并将patternAdaptor用于饼图

---

examples/plugin/pattern/demo/bar-pattern.ts
examples/plugin/pattern/demo/column-pattern.ts
examples/plugin/pattern/demo/group-column-pattern.ts
examples/plugin/pattern/demo/meta.json
examples/plugin/pattern/demo/pie-pattern-callback.ts
examples/plugin/pattern/demo/pie-pattern.ts
examples/plugin/pattern/demo/radial-bar-pattern.ts
examples/plugin/pattern/index.en.md
examples/plugin/pattern/index.zh.md
src/adaptor/pattern.ts
src/plots/column/adaptor.ts
src/plots/pie/adaptor.ts
src/plots/radial-bar/adaptor.ts
src/plugin/pattern/dot.ts
src/types/attr.ts

feat: Upgrade pattern

---

src/types/pattern.ts
src/utils/pattern/dot.ts
src/utils/pattern/index.ts

refactor: pattern

---

src/types/pattern.ts
src/utils/pattern/dot.ts
src/utils/pattern/index.ts
src/utils/pattern/line.ts
src/utils/pattern/square.ts

feat(square-pattern): 添加square样式贴图

---

src/types/pattern.ts
src/utils/pattern/dot.ts
src/utils/pattern/line.ts
src/utils/pattern/square.ts
src/utils/pattern/util.ts

refactor(pattern): 优化pattern的写法，抽出一些方法

---

__tests__/unit/utils/pattern/dot-spec.ts
__tests__/unit/utils/pattern/line-spec.ts
__tests__/unit/utils/pattern/square-spec.ts
__tests__/unit/utils/pattern/util-spec.ts
__tests__/utils/getPixelColor.ts
src/types/pattern.ts
src/utils/pattern/dot.ts
src/utils/pattern/index.ts
src/utils/pattern/line.ts
src/utils/pattern/square.ts
src/utils/pattern/util.ts

refactor(pattern): 使用setTransform方法，rotation作用于整个pattern画布

---

__tests__/bugs/issue-2734-spec.ts
__tests__/unit/plots/multi-view/state-spec.ts
src/plots/dual-axes/adaptor.ts

fix: 修复双轴图 theme 设置覆盖 columnWidthRatio 设置

---

__tests__/unit/plots/funnel/basic-spec.ts
src/plots/funnel/geometries/basic.ts

|----|----|
|  <img width="735" alt="截屏2021-08-13 11 29 30" src="https://user-images.githubusercontent.com/11748654/129301131-d4beed3b-c18d-4a01-a1a3-6fa885f1ab0a.png"> | <img width="650" alt="截屏2021-08-13 11 28 14" src="https://user-images.githubusercontent.com/11748654/129301110-101b33f8-ac27-47aa-abad-d2e97143a5d4.png">|

fix: 修复尖底漏斗图最后一排错位

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.30 & changelog

---

examples/plugin/pattern/demo/bar-pattern.ts
examples/plugin/pattern/demo/column-pattern.ts
examples/plugin/pattern/demo/group-column-pattern.ts
examples/plugin/pattern/demo/pie-pattern-callback.ts
examples/plugin/pattern/demo/pie-pattern.ts
examples/plugin/pattern/demo/radial-bar-pattern.ts
src/utils/pattern/dot.ts
src/utils/pattern/line.ts
src/utils/pattern/square.ts

docs: 添加pattern的demo

---

__tests__/bugs/bug-dual-axes-legend-marker-spec.ts
__tests__/unit/adaptor/geometries/base-spec.ts
__tests__/unit/plots/dual-axes/legend-spec.ts
src/adaptor/geometries/base.ts
src/plots/dual-axes/util/legend.ts

fix(dual-axes): 修复双轴图使用 color 回调时，legend marker 颜色丢失

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.21 & changelog

---

README.md
README.zh-CN.md
__tests__/bugs/issue-2749-spec.ts
docs/manual/contact.en.md
docs/manual/contact.zh.md
examples/case/advanced/demo/conversion-analysis-bar.ts
examples/case/advanced/demo/conversion-analysis.ts
examples/case/advanced/demo/meta.json
examples/dynamic-plots/brush/demo/meta.json

|----|----|
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/p8r96Xc9o0/conversion-analysis-bar.gif) |
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/PojoRGFBN4/conversion-analysis-2.gif) |

docs: 增加 2 个转化分析漏斗图 demo, 带跳转

---

examples/rose/grouped/demo/basic.ts
examples/rose/grouped/demo/meta.json
examples/rose/grouped/demo/pattern.ts
src/plots/rose/adaptor.ts

feat: rose support pattern

---

examples/progress-plots/liquid/demo/meta.json
examples/progress-plots/liquid/demo/pattern.ts
src/plots/liquid/adaptor.ts

feat: liquid pattern

---

examples/dual-axes/column-line/demo/pattern.ts
examples/dual-axes/grouped-column-line/demo/meta.json
examples/dual-axes/grouped-column-line/demo/pattern-with-callback.ts
src/plots/dual-axes/util/geometry.ts

feat: dual axes pattern

---

CHANGELOG.md
package.json
src/index.ts

chore: 2.3.32 & changelog

---

__tests__/unit/plots/venn/color-spec.ts
__tests__/unit/plots/venn/data-spec.ts
__tests__/unit/plots/venn/index-spec.ts
__tests__/unit/plots/venn/label-spec.ts
__tests__/unit/plots/venn/legend-spec.ts
__tests__/unit/plots/venn/padding-spec.ts
__tests__/unit/plots/venn/style-spec.ts
__tests__/unit/plots/venn/tooltip-spec.ts
docs/api/plots/venn.en.md
docs/api/plots/venn.zh.md
examples/more-plots/venn/API.en.md
examples/more-plots/venn/API.zh.md
src/plots/venn/adaptor.ts

test: venn图的基础配置的单测和文档

---

README.en-US.md
README.md

docs: set default lang=zh in readme

---

src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/types.ts

feat(dual-axes): 双轴图支持单轴配置legend

---

__tests__/unit/plots/venn/padding-spec.ts
src/plots/circle-packing/adaptor.ts
src/plots/circle-packing/utils.ts
src/plots/venn/adaptor.ts
src/utils/padding.ts

refactor(padding): venn图增加padding配置项

---

CHANGELOG.md
examples/case/advanced/demo/meta.json
gatsby-config.js
package.json
src/index.ts
src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/util/legend.ts

chore: v2.3.33 & changelog

---

CHANGELOG.md

docs(changelog): 删除重复的 changelog

---

__tests__/unit/plots/venn/padding-spec.ts
src/plots/venn/adaptor.ts

fix(padding): 兼容非法padding

---

examples/pie/basic/demo/meta.json
examples/pie/basic/demo/pie-custome-label.ts

|----|----|
|  ❌  | ![image](https://cdn.nlark.com/yuque/0/2021/png/22203542/1631705960519-bab7f151-f210-4fc4-b33c-72386996888e.png)|

docs: 增加一个饼图 demo（个性化标签饼图）

---

examples/case/statistical-scenario/demo/funnel-analysis.jsx
examples/case/statistical-scenario/demo/meta.json

docs: 增加一个漏斗图分析 demo

---

__tests__/unit/plots/venn/data-spec.ts
src/plots/venn/adaptor.ts
src/plots/venn/utils.ts

fix：
- 空数组/null/undefined：G2Plot 层不报错，控制台打印warning
- 错误集合：过滤掉并集中存在not exist的集合组，在控制台打印warning提示
|----|----|
|  ❌  |  ✅  |

fix(venn): 处理非法数据

---

docs/api/plots/progress.en.md
docs/api/plots/progress.zh.md

|----|----|
|  ❌  |  ✅  |
完善了进度条progressStyle的回调方法描述文档

fix(#2486): 完善了进度条progressStyle的回调方法描述文档

---

examples/case/statistical-scenario/demo/meta.json
examples/component/label/API.en.md
examples/component/label/API.zh.md
examples/component/label/demo/custom-label.ts
examples/component/label/demo/meta.json
examples/plugin/custom-pattern/demo/meta.json

docs(label): 增加一个数据标签的 demo

---

__tests__/unit/plots/venn/interaction-spec.ts
docs/api/plots/venn.en.md
docs/api/plots/venn.zh.md
examples/more-plots/venn/demo/interaction.ts
examples/more-plots/venn/demo/meta.json
src/plots/venn/adaptor.ts
src/plots/venn/interaction/action.ts
src/plots/venn/interaction/index.ts

fix(interaction): 添加 venn图 selected 和 active 的交互

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.3.34 & changelog

---

.github/workflows/release-notify.yml

chore: not dingAll when release notify

---

docs/common/marker.en.md
docs/common/marker.zh.md
examples/component/legend/demo/legend-marker-customize.ts
examples/component/legend/demo/meta.json

close: #2953
|----|----|
|  ❌  |  ✅  |

docs: 增加图例自定义 marker 的demo

---

CHANGELOG.md
package.json
src/index.ts

chore(release): 2.3.40

---

examples/plugin/basic/demo/hill-column.ts

改了个错别字
|----|----|
|  ❌  |  ✅  |

fix: fix document typo

---

__tests__/unit/plots/word-cloud/index-spec.ts
docs/api/plots/bar.en.md
docs/api/plots/bar.zh.md
docs/api/plots/column.en.md
examples/bar/basic/demo/meta.json
examples/bar/basic/demo/shape.ts
examples/column/basic/demo/custom-shape.ts

- fix(test): 修复测试问题
- docs(bar): 条形图增加 shape 配置文档
|----|----|
|  ❌  |  ✅  |

docs(bar): 条形图增加 bar 配置文档说明和demo

---

__tests__/unit/plots/word-cloud/index-spec.ts
docs/api/plots/bar.en.md
docs/api/plots/bar.zh.md
docs/api/plots/column.en.md
docs/api/plots/line.zh.md
examples/bar/basic/demo/meta.json
examples/bar/basic/demo/shape.ts
examples/column/basic/demo/custom-shape.ts
examples/column/grouped/demo/meta.json
examples/column/grouped/demo/rc-tooltip.jsx
examples/line/multiple/demo/meta.json
examples/more-plots/box/demo/meta.json
examples/more-plots/sunburst/demo/meta.json
gatsby-browser.js
package.json
src/utils/data.ts

docs: 周常丰富文档和 demo

---

.github/workflows/release.yml

发现 node 12 下，会报 js 超出内存
|----|----|
|  ❌  |  ✅  |

ci: remove node 12

---

__tests__/unit/plots/word-cloud/legend-spec.ts
docs/common/legend-cfg.en.md
docs/common/legend-cfg.zh.md
examples/case/statistical-scenario/demo/conversion-funnel.ts
examples/case/statistical-scenario/demo/meta.json

- docs(legend): 完善图例文档
- docs(funnel-demo): 增加一个自定义转化漏斗图
|----|----|
|  ❌  |  ✅  |

docs: 补充 legend 文档 & 自定义转化漏斗图 demo

---

__tests__/unit/plots/sunburst/legend-spec.ts
package.json
src/plots/sunburst/adaptor.ts
src/plots/sunburst/constant.ts
src/plots/sunburst/types.ts

feat(sunburst): 旭日图支持图例配置 & 单测

---

__tests__/bugs/issue-3012-spec.ts
__tests__/unit/plots/bar/index-spec.ts
__tests__/unit/plots/bar/legend-spec.ts
src/plots/bar/adaptor.ts

fix(issue-3012): 修复条形图图例转置 & 单测

---

src/plots/venn/types.ts

fix(venn): fix venn color option type compatibility

---

CHANGELOG.md
package.json
src/index.ts

chore: release 2.4.0 & changelog

---

__tests__/bugs/bar-axis-label-spec.ts
src/plots/bar/adaptor.ts

fix(bar): 修复条形图 xAxis、yAxis 互相影响

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.1 & changelog

---

.github/workflows/auto-inspection.yml

chore: ci 升级到 yarn

---

docs/common/marker.en.md
docs/common/marker.zh.md

fix(docs): 文档链接 404

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.2 & changelog

---

src/plots/line/interactions/marker-active.ts

fix(line): 修复折线图 marker-active 交互，在point为空时存在隐藏错误

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.3 & changelog

---

CHANGELOG.md
__tests__/bugs/issue-1757-spec.ts
__tests__/bugs/issue-1761-spec.ts
__tests__/bugs/issue-2064-spec.ts
__tests__/unit/plots/area/change-data-spec.ts
__tests__/unit/plots/area/line-spec.ts
__tests__/unit/plots/area/point-spec.ts
__tests__/unit/plots/area/tooltip-spec.ts
__tests__/unit/plots/gauge/shapes/index-spec.ts
__tests__/unit/plots/line/area-spec.ts
__tests__/unit/plots/line/change-data-spec.ts
__tests__/unit/plots/line/interaction-spec.ts
__tests__/unit/plots/line/point-spec.ts
__tests__/unit/plots/line/stack-spec.ts
__tests__/unit/plots/line/tooltip-spec.ts
__tests__/unit/plots/multi-view/utils-spec.ts
examples/line/basic/demo/custom-marker.ts
examples/line/multiple/demo/marker-active.ts
package.json
src/index.ts
src/plots/area/adaptor.ts
src/plots/area/constants.ts
src/plots/area/index.ts
src/plots/line/adaptor.ts
src/plots/line/constants.ts
src/plots/line/index.ts
src/plots/line/interactions/marker-active.ts
src/utils/geometry.ts

Revert refactor 折线图和面积图的性能优化

---

package.json
src/index.ts

chore: v2.4.4

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.5 & changelog

---

package.json
src/plots/gauge/adaptor.ts
src/plots/pie/adaptor.ts
src/plots/progress/adaptor.ts

feat: 增加 sortZIndex 参数

---

docs/common/axis.en.md
docs/common/axis.zh.md
examples/case/statistical-scenario/demo/meta.json
examples/column/basic/demo/meta.json
examples/column/grouped/demo/meta.json

- docs: 增加 axis title api说明
- docs: 移除 demo 更新标识
|----|----|
|  ❌  |  ✅  |

docs: 增加 axis title api说明

---

src/plots/scatter/adaptor.ts

feat(scatter): 散点图气泡图添加 slider 缩略轴 scrollbar 滚动条 配置

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.6 & changelog

---

src/plots/liquid/adaptor.ts
src/plots/liquid/shapes/liquid.ts
src/plots/liquid/types.ts

fix(liquid): 水波图允许关闭动画效果

---

__tests__/unit/plots/bar/legend-spec.ts
__tests__/unit/plots/column/legend-spec.ts
__tests__/unit/plots/pie/label-spec.ts
docs/common/legend-cfg.en.md
docs/common/legend-cfg.zh.md
examples/component/legend/demo/legend-radio.ts
examples/component/legend/demo/meta.json
src/plots/area/constants.ts
src/plots/bar/constants.ts
src/plots/column/constants.ts
src/plots/line/constants.ts
src/plots/pie/contants.ts
src/plots/rose/constant.ts

|----|----|
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/LVM6Z%2473sn/legend-radio-focus.gif)  |

feat(legend): 图例增加 radio 按钮实现正选 focus 功能

---

__tests__/unit/plots/bar/legend-spec.ts
__tests__/unit/plots/column/legend-spec.ts
__tests__/unit/plots/pie/label-spec.ts
docs/common/legend-cfg.en.md
docs/common/legend-cfg.zh.md
examples/component/legend/demo/legend-radio.ts
examples/component/legend/demo/meta.json
src/plots/area/constants.ts
src/plots/bar/constants.ts
src/plots/column/constants.ts
src/plots/line/adaptor.ts
src/plots/line/constants.ts
src/plots/pie/contants.ts
src/plots/rose/constant.ts

feat(line): 折线图支持 scrollbar

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.7 & changelog

---

.github/workflows/release-notify.yml

ci: fix footer click

---

__tests__/bugs/issue-3085-spec.ts
src/utils/transform/percent.ts

fix(column): 修复百分比柱状图 总和为零时的 bug

---

examples/progress-plots/gauge/demo/custom-indicator3.ts
examples/progress-plots/gauge/demo/meta.json

docs(gauge): 增加仪表盘自定义 demo

---

__tests__/bugs/issue-2930-spec.ts
src/plots/dual-axes/adaptor.ts
src/plots/dual-axes/util/render-sider.ts

|----|----|
|   ![2930-1](https://user-images.githubusercontent.com/36756846/151116821-4f4e8c3a-678d-4d62-b94d-bd00871697b3.jpg) |  ![2930-6](https://user-images.githubusercontent.com/36756846/151117300-19307b83-4c1f-42b9-ae97-2105fd8d802e.jpg)|

fix(dual-axes): 修复双轴图bottom统一的问题 #2930

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.8 & changelog

---

src/types/button.ts
src/types/common.ts
src/types/drill-down.ts
src/types/interaction.ts
src/types/label.ts
src/types/meta.ts
src/types/pattern.ts
src/types/state.ts
src/types/statistic.ts
src/types/tooltip.ts

feat: 基于 JSDoc 标准调整 types 类型定义

---

gatsby-config.js

docs: 周边工具增加 性能检测工具

---

CHANGELOG.md
docs/api/plots/funnel.en.md
docs/api/plots/funnel.zh.md
package.json
src/index.ts
src/plots/funnel/geometries/compare.ts
src/plots/funnel/geometries/facet.ts
src/plots/funnel/types.ts

|----|----|
|  <img width="1032" alt="image" src="https://user-images.githubusercontent.com/15646325/157632671-a6d9c90a-8ae2-497b-a29d-5bd35bad1cfa.png">|  <img width="1004" alt="image" src="https://user-images.githubusercontent.com/15646325/157632700-88258acc-76cc-4652-bda6-5105fdd82fb3.png"> |

feat(funnel): 漏斗图增加关闭分面 title 的展示

---

examples/plugin/multi-view/demo/anomaly-detection-line-chart.ts
examples/plugin/multi-view/demo/meta.json

docs(multi-view): 增加异常检测折线图demo

---

docs/manual/plots/funnel.en.md
docs/manual/plots/funnel.zh.md
gatsby-config.js

chore: v2.4.10

---

__tests__/unit/plots/gauge/tooltip-spec.ts
docs/api/plots/gauge.en.md
docs/api/plots/gauge.zh.md
examples/progress-plots/gauge/demo/meta.json
examples/progress-plots/gauge/demo/tooltip-gauge.ts
src/plots/gauge/adaptor.ts
src/plots/gauge/types.ts

feat(gauge): 仪表盘增加 tooltip 配置

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.11 & changelog

---

__tests__/unit/plots/bidirectional-bar/index-spec.ts
src/plots/bidirectional-bar/adaptor.ts

feat(bidirectional-bar): 对称条形图支持主题配置

---

src/plots/mix/utils.ts

feat(mix): mix 图表支持 stock

---

site/locale.json

chore: fix typo in locale.json

---

CHANGELOG.md
package.json
src/index.ts

- feat(mix): mix 图表支持 stock
- chore: v2.4.13 & changelog
|----|----|
|  ❌  |  ✅  |

chore 2.4.13

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.15 & changelog

---

examples/case/statistical-scenario/demo/trend.jsx
examples/more-plots/stock/demo/large-data.ts
examples/plugin/facet/demo/tree-column.ts
examples/plugin/facet/demo/tree.ts
examples/plugin/multi-view/demo/drinks.ts
gatsby-browser.js
gatsby-config.js
package.json

chore(website): remove data-set & add bundle-analyser

---

docs/api/advanced-plots/mix.en.md
docs/api/advanced-plots/mix.zh.md
examples/plugin/multi-view/demo/meta.json
examples/plugin/multi-view/demo/nest-pie.ts

docs(mix): 增加 mix demo 和文档说明

---

examples/bar/percent/demo/meta.json

`百分百`改为`百分比`
|----|----|
|  ❌  |  ✅  |

fix: 勘误-百分比条形图

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.16 & changelog

---

docs/common/common-component.zh.md

加了示例配置代码更清晰，降低理解成本。
|----|----|
|  ❌  |  ✅  |

docs(bidirectional-bar): 新增双 y 轴中 yAxis 配置示例

---

examples/column/basic/demo/meta.json
examples/column/scenario/demo/meta.json
examples/component/legend/demo/meta.json
examples/line/scenario/demo/meta.json
examples/more-plots/circle-packing/demo/meta.json
examples/plugin/multi-view/demo/meta.json
examples/progress-plots/gauge/demo/meta.json
examples/relation-plots/sankey/demo/meta.json
examples/relation-plots/sankey/demo/node-sort-sankey.ts

docs(sankey): add demo for sankey

---

package.json

chore: specify @antv/util dependency

---

__tests__/unit/plots/bullet/data-spec.ts

fix(bullet): 修改子弹图单测

---

examples/bar/basic/demo/dynamic.ts
examples/bar/basic/demo/meta.json

feat(bar): 添加动态条形图

---

__tests__/unit/plots/sankey/index-spec.ts
__tests__/unit/utils/transform/word-cloud-spec.ts

注释 word-cloud 的 with data-set
增加 延迟时间， 等待 label 渲染

fix(test): g2plot label 延迟渲染 注释和增加延迟时间 到 test

---

__tests__/unit/plots/progress/index-spec.ts
__tests__/unit/plots/progress/utils-spec.ts
__tests__/unit/plots/ring-progress/index-spec.ts
src/plots/progress/adaptor.ts
src/plots/progress/utils.ts

| --- | --- |
|  ![image](https://user-images.githubusercontent.com/65594180/176432759-d2114541-fce6-4a54-a0a5-2049aca7bc7c.png) | ![image](https://user-images.githubusercontent.com/65594180/176432591-e7cd0a39-c3fc-40ac-bb81-3d2dfa084151.png) |
fixed #3267

fix(progress): 迷你进度条重新修改

---

README.en-US.md
README.md
docs/manual/contact.en.md
docs/manual/contact.zh.md

feat(md): 更新 钉钉群 二维码和信息

---

__tests__/unit/plots/histogram/index-spec.ts
src/plots/histogram/adaptor.ts

修复 直方图 histogram 修复不能关闭 legend 的问题

fix(histogram): 直方图 histogram 修复不能关闭 legend 的问题

---

__tests__/bugs/issue-2124-spec.ts
__tests__/unit/adaptor/conversion-tag-spec.ts
__tests__/unit/utils/conversion-spec.ts
src/utils/conversion.ts

| --- | --- |
| ![image](https://user-images.githubusercontent.com/65594180/183554312-e045f818-a095-41b8-b3e4-24e86454bf31.png) | ![image](https://user-images.githubusercontent.com/65594180/183554112-0006b237-fac4-4b28-ab10-9b56dd26dc12.png) |

fix(funnel): 当 next 为 0 时，应该显示 0% 而不是 -∞

---

src/plots/box/adaptor.ts

|----|----|
|  ![image](https://user-images.githubusercontent.com/65594180/185021911-95c33475-06d3-4d7e-baba-870a7d74a9cc.png) |  ![image](https://user-images.githubusercontent.com/65594180/185021879-5559eb40-4beb-4371-b5a5-a2b827ac04ef.png)|
fixed #https://github.com/ant-design/ant-design-charts/issues/1484

fix(box): 箱型图 添加 annotation 配置

---

CHANGELOG.md
package.json
src/index.ts

chore: v2.4.21 & changelog

---

__tests__/unit/plots/stock/data-spec.ts
src/plots/stock/utils.ts

fixes #3301
|  Before  |  After      |
|---------|----------|
|  BUG     |  NO BUG  |

fix(stock): avoid mutating stock data item

---

docs/api/plot-api.zh.md

删除一个 单引号
|----|----|
|  ❌  |  ✅  |

docs: fix typo

---

__tests__/bugs/issue-3367-spec.ts
src/plots/column/adaptor.ts

fix(column): custom customItems invalid issue (#3367)

---

src/types/common.ts

fix(type): fix appendPadding description typo

---

.github/workflows/deploy.yml
jest.config.js
package.json
site/.dumi/global.ts
site/CNAME

chore: update deploy action

---

site/docs/common/legend-cfg.en.md
site/examples/dynamic-plots/basic/demo/dynamic-spline.ts

fix: close issues

---

.github/workflows/deploy.yml
package.json
site/.dumi/global.ts

feat: add site direct

---

site/examples/case/advanced/demo/associate-filter.ts
site/examples/case/advanced/demo/associate-pie-tooltip.ts
site/examples/case/interactions/demo/meta.json
site/examples/dynamic-plots/brush/demo/advanced-brush1.ts
site/examples/dynamic-plots/brush/demo/advanced-brush2.ts

fix: several error demo in site

---

site/.dumirc.ts

chore: fix homepage url

---

__tests__/unit/plots/area/index-spec.ts
__tests__/unit/plots/radial-bar/index-spec.ts
__tests__/unit/plots/rose/index-spec.ts
__tests__/unit/plots/sunburst/index-spec.ts
__tests__/unit/plots/waterfall/index-spec.ts
src/adaptor/geometries/area.ts
src/plots/area/adaptor.ts
src/plots/area/types.ts
src/plots/radial-bar/adaptor.ts
src/plots/radial-bar/types.ts
src/plots/rose/adaptor.ts
src/plots/rose/types.ts
src/plots/sunburst/adaptor.ts
src/plots/sunburst/types.ts
src/plots/waterfall/adaptor.ts
src/plots/waterfall/types.ts

feat(custom shape): support custom shape for area/waterfall/radial-bar/rose/sunburst plot

---

__tests__/integration/main.ts
__tests__/integration/plots/column-basic.ts
__tests__/integration/plots/line-annotation-line.ts
__tests__/integration/plots/line-annotation-range.ts
__tests__/integration/plots/line-area.ts
__tests__/integration/plots/line-basic.ts
__tests__/integration/plots/line-color-mapping.ts
__tests__/integration/plots/line-condition-rangeY.ts
__tests__/integration/plots/line-point-shape.ts
__tests__/integration/plots/line-scrollbar.ts
__tests__/integration/plots/line-series.ts
__tests__/integration/plots/line-slider.ts
package.json
src/core/plot.ts
src/utils/index.ts

- 修复 renderer: `canvas | svg` 出错
- 内置默认 theme

fix: renderer error

---

CHANGELOG.md
package.json

因为 component 更新了，发一个版本更新一下线上的 build 产物。

chore: update to 2.4.28

---

src/index.ts

chore: update version in index.ts

---

__tests__/integration/main.ts
package.json
src/index.ts
src/types/common.ts

feat: export all G2

---

CHANGELOG.md
package.json

chore: update version of @antv/component to 0.8.34 for dist build

chore: update version of @antv/component to 0.8.34 for dist build

---

site/examples/plugin/multi-view/demo/customized-stock.jsx

chore: fix customized stock demo typo

---

README.en-US.md
README.md

docs: update readme

---

site/examples/heatmap/basic/demo/calendar.ts

https://g2plot.antv.antgroup.com/examples/heatmap/basic/#calendar

🐞 fix(demo):  heatmap-base parameter error

---

site/docs/api/plots/area.en.md
site/docs/api/plots/area.zh.md

area plot: the default value of isPercent option should be false

---

site/docs/manual/contact.en.md
site/docs/manual/contact.zh.md

chore: update contact
