antvis/G2Plot

src/geoms/interval/main.ts
柱状图不使用默认position field作为color filed
=> fix: don't set default color field

src/components/label/parser.ts
在label parser中直接将formatter函数传入，
=> fix: 允许label格式化时获取到原始数据点

__tests__/unit/biztheme.spec.js, __tests__/unit/liquid.spec.js, src/base/plot.ts, src/util/event.ts
* 单侧中的theme改成一定义主题
* Base plot 中不记录绑定到 view 上的事件，view destroy 的时候会统一注销事件
=> Remove unnecessary event off

src/base/controller/padding.ts
增加带翻页器的legend的auto padding处理逻辑，g2端修改见 https://github.com/antvis/g2/pull/1416
=> fix: auto padding for flipped legend

__tests__/unit/line.spec.js, src/geoms/point/guide.ts
support line point style。
以及修复折线图测试用例。
```
point: {
visible: true,
color: 'red',
size: 5,
style: {
fillStyle: 'pink',
lineWidth: 2,
strokeStyle: 'black',
},
},
```
=> Fix line point

src/base/controller/padding.ts
=> fix(legend): use legend.getBBox for auto padding

src/plots/pie/PieLayer.ts
修复pieLayer创建labelParser的时候,没有传入labelType,导致无法注册自定义pieLabel
=> fix(pieLayer):  无法注册自定义pieLabel

__tests__/unit/pie.spec2.js, src/plots/pie/component/label/spiderLabel.ts
1. 主要原因在于G层的shape没有用配置cfg.name对Shape name赋值，因此上层需要手动标注
2. 此为临时方案，后续建议下沉到shape处理，或者shape提供setter的方式，如`setName` 而不是直接赋值
closes #110
=> fix(spider-pie-label-events): 修复spider pie监听label事件失效

src/base/ViewLayer.ts
之前的写法会导致用户在meta中设置的meta信息没有传到到g2，因为在子图形中只处理了xField/yField的scale信息，用户可能还设置其他字段的scale信息，也需要传递下去
=> fix: config all meta scale in meta config

src/plots/radar/layer.ts
=> 雷达图radiusAxis默认以0值为起点

docs/manual/introduction.zh.md, examples/line/basic/index.en.md, examples/line/basic/index.zh.md, gatsby-config.js, package.json
- https://github.com/antvis/g2plot/pull/174
- https://github.com/antvis/g/pull/251
重新定义了一下 gatsby-config.js 的配置，有一些不兼容。
=> docs: Upgrade theme config

src/plots/area/index.ts, src/plots/bar/index.ts, src/plots/bubble/index.ts, src/plots/column/index.ts, src/plots/column/layer.ts, src/plots/density/index.ts, src/plots/gauge/index.ts, src/plots/group-bar/index.ts, src/plots/group-column/index.ts, src/plots/histogram/index.ts, src/plots/line/index.ts, src/plots/liquid/index.ts, src/plots/pie/index.ts, src/plots/radar/index.ts, src/plots/ring/index.ts, src/plots/stack-area/index.ts, src/plots/stack-bar/index.ts, src/plots/stack-column/index.ts, src/theme/default.ts, src/tiny-plots/progress/index.ts, src/tiny-plots/ring-progress/index.ts, src/tiny-plots/tiny-area/index.ts, src/tiny-plots/tiny-column/index.ts, src/tiny-plots/tiny-line/index.ts
Plot不需要为泛型
要不然用户使用的时候还需要
```
new G2Plot.Line<LineConfig>(...)
```
要不然updataConfig时 不能确定类型报错
=> fix: 修改plot为非泛型

src/components/axis/parser.ts, src/interface/config.ts
这里之前是允许整个grid是个callback，调整下还是保持gird.visible的结构，运行grid.style通过callback配置
=> fix: 修复axis grid的callback配置方式

src/plots/line/layer.ts
修复折线图上label相关的配置无效问题，如formatter
=> fix: support line label formatter config

.github/workflows/release.yml, package.json
* 目前使用GITHUB_TOKEN来push gh-pages不能触发github pages rebuid, 需要使用ACCESS_TOKEN
* 移除 package.json 中的publish script，避免npm publish时执行两次
=> chore: use ACCESS_TOKEN for release action

README.md, README.zh-CN.md
preview: https://github.com/antvis/G2Plot/blob/86db2cf1f832e078b289b7a101e843ef4a3b3b19/README.md
=> docs(readme): optimize readme style, and fix typo

src/plots/area/layer.ts, src/plots/pie/layer.ts, src/plots/radar/layer.ts
修复饼图 环图 在label.type=inner he renderer='svg'时多余线的渲染
修复带area类图表的透明度不符合视觉要求的bug
=> fix: 修复Pie Ring的labelLine 以及area的透明度

src/base/view-layer.ts, src/interface/config.ts, src/plots/bar/layer.ts, src/plots/density/layer.ts, src/plots/histogram/layer.ts, src/plots/percentage-stack-area/layer.ts, src/plots/percentage-stack-bar/layer.ts, src/plots/percentage-stack-column/layer.ts, src/plots/pie/layer.ts, src/plots/ring/layer.ts, src/util/data.ts
问题可在[DEMO](https://codesandbox.io/s/gracious-spence-uwxki?fontsize=14&hidenavigation=1&theme=dark)中复现
- 在 processData 中保证处理后的数据加起来恒为1
- scale中设置 minLimit/maxLimit 为0/1
=> fix: 修复百分比堆积图形在某些数据下出现120%的问题

docs/manual/introduction.zh.md
使用的版本为: antv/g2plot 0.11.4
按照文档中的使用实例使用时提示:
```shell
Attempted import error: '@antv/g2plot' does not contain a default export (imported as 'g2plot').
```
在react项目中按照官方文档这样提示没有默认导出语句,需要解构导入.
如果是我操作不当,请指出 :smile:
=> docs: update G2Plot/docs/manual/introduction.zh.md

__tests__/unit/pie-label-spec.ts, src/plots/pie/component/label/outer-label.ts
1. 复写pie outer-label  `getDefaultOffset`的方法 (强制offset > 0)
2. 当label offset 无配置（重置为16px）或小于等于0（重置为1px）时，自动重置
3. 提高测试覆盖率
=> test(pie-coverage): 增加pie-label测试断言

.github/workflows/release.yml
setting里面写的PERSONAL_ACCESS_TOKEN
=> chore: correct site-publish token

src/plots/bar/component/label/bar-label.ts, src/plots/column/component/label/column-label.ts, src/plots/column/layer.ts
=> fix: 修复column/bar数据标签position配置在负数值情况的位置

examples/bubble/basic/demo/trendline.js, examples/scatter/basic/demo/color-mapping.js, examples/scatter/basic/demo/trendline.js, src/index.ts, src/plots/bubble/layer.ts, src/plots/scatter/components/quadrant.ts, src/plots/scatter/components/trendline.ts, src/plots/scatter/layer.ts
=> fix: export mini chart config

src/plots/histogram/layer.ts
column将x轴scale type强制设为cat，直方图扩展自column，而x scale是linear的，造成无法绘制。
=> fix: 直方图绘制失效

demos/radar-basic.ts, demos/radar-series.ts, src/base/view-layer.ts, src/plots/radar/layer.ts
* 修复雷达图类型定义，部分定义非必须传入
* 修复雷达图空数据问题，viewLayer changeData 后，options 中的 data 应置为最新的 data，因为 render 与 resize 的 data 均为从 options 中获取
=> fix: fix radar errors #436

__tests__/bugs/issue-485-spec.ts, __tests__/unit/pie-outerLabel-spec.ts, __tests__/unit/pie-utils-spec.ts, src/plots/pie/component/label/base-label.ts, src/plots/pie/component/label/outer-label.ts, src/plots/pie/component/label/utils/index.ts, src/plots/pie/component/label/utils/text.ts, src/plots/pie/layer.ts
详细见 commit 记录
> 备注：此版 是 目前DI上线的label, todo 部分在 DI 先上线，年前再下沉至 G2Plot
其他后续处理
close #485
=> refactor: pie  outer label

demos/radar-series.ts, src/plots/bar/component/label/bar-label.ts, src/plots/column/component/label/column-label.ts, src/plots/radar/layer.ts, src/plots/scatter/components/label/scatter-label.ts, src/theme/dark.ts, src/theme/default.ts
1. 雷达图去除默认配置中的 label 配置，使用全局主题配置。另外：G2DefaultTheme 结构与 plotG2Theme 结构不一致，是否会存在问题？ @zqlu 需要关注一下
2. label 使用 adjustColor 时，当 label 处于 shape 外，需要考虑全局背景的影响，使用主题中的 label 颜色
=> fix: 修复 dark 下图表 label 问题 issue #489

demos/pie-labelPercent.ts, src/plots/pie/layer.ts
对于饼图的 label 与 tooltip 的内容回调中透出 percent 值，并且受到 legend 控制，解决 G2 类似问题：https://github.com/antvis/G2/issues/855
=> feat(pie): add tooltip and label percent

src/plots/pie/component/label/outer-center-label.ts
复现链接：https://riddle.alibaba-inc.com/riddles/266d13e6
=> fix：修复 pie outer-center-label 下引线 path 问题 

src/plots/ring/layer.ts
master 版本会自动给container加上position relative, 1.x 版本在环图存在中心文本的时候处理.后续看清楚再做统一处理
=> fix(ring): 修复环图中心文本定位问题

src/plots/pie/layer.ts
在 pie 图 label 上 line 为配置项，G2 3.6.x 内部是 labelLine，需要对齐
=> 【0.1.x】fix: 支持饼图 label line 上的样式配置

src/plots/range-bar/layer.ts, src/plots/range-column/layer.ts
- mark `RangeColumnViewConfig.labe`l as optional
- mark `RangeBarViewConfig.label` as optional
`label` is optional in [document](https://g2plot.antv.vision/zh/docs/manual/plots/range-column#label), but required in type definitions
https://github.com/antvis/G2Plot/blob/f5336becba2228ed3bb1180ce07ca3791c899ab7/src/plots/range-column/layer.ts#L8-L10
=> fix(types): fix type definition error

__tests__/unit/plots/bubble/bubble-spec.ts, src/plots/bubble/layer.ts, src/plots/scatter/layer.ts
* bubble 单元测试添加，由于继承自 bubble ，主要单测逻辑在 scatter 中
* 由于使用 G2 4.0 内置的 label，label 的 position 暂不支持
=> feat(bubble): 添加单元测试

__tests__/unit/plots/scatter/scatter-spec.ts, src/components/label/parser.ts, src/plots/scatter/layer.ts
在 G2 4.x 中 label 上没有 formatter 了，只有 content，并且参数上存在增强，目前做法是兼容老的 API，label.content 中的 mappingData 是否要从 G2Plot 中透出？
=> 【1.x】G2Plot label.formatter 兼容 G2 4.x label.content

webpack.config.js
- moment依赖的问题在 https://github.com/antvis/component/pull/148 中修复
- 现在打包产物还有G有两份的问题，等G2升级G发布后，再发G2Plot
=> fix: cleanup webpack config

src/base/controller/state.ts
当图表updateConfig后，view重新destory并更新，但是stateController中缓存了旧的shapes，导致新设置的状态apply到了旧的图形中，并且旧的图形已经被销毁，所以导致无法通过 shape.get('origin').data 获取到数据。
=> feat: 修复updateConfig后状态量更新失效

src/base/controller/canvas.ts
closed #745 
深层的原因见 #745 issue。
=> fix(#745): fix resize loop because canvas style

examples/step-line/basic/index.en.md, examples/step-line/multiple/index.en.md
close antvis/gatsby-theme-antv#120
阶梯图里的英文分类名和折线图里的重名，导致了两个分类的 demo 混在一起了。
=> docs: fix English gallery page wrong order

src/geoms/point/guide.ts, src/plots/line/layer.ts
```
point:{
visible: true,
size:4,
shape:{
fields:['type'],
callback:(v)=>{
const mapping = {
download:'circle',
bill:'square',
register:'diamond'
};
return mapping[v];
}
}
},
```
先以满足DI业务为优先，还有一些图表应该开放shape callback，后续再支持
=> feat: line point shape callback

src/plots/word-cloud/wordcloud2.ts
strict mode does not allow multiple definitions of an attribute（strict 模式下不允许一个属性有多个定义）
=> fix(word-cloud2): under the IE11 settings.animatable not allowed duplicate define

__tests__/unit/components/legend-spec.ts, package.json, src/base/view-layer.ts, src/interface/config.ts, src/theme/dark.ts
说明：
G2目前支持legend除marker外再增加一个value值，但这需要预先产生一个legend.items传入，并且不同的图表，legend.value的表现可能不同，例如饼图可以直接显示value，堆叠和分组图则hover显示value更合适，没有想清楚前暂不开放配置。
=> feat: support legend style & formatter Closes #966, #876, #856, #877

src/base/view-layer.ts
=> fix(tooltip): not use document to query ".g2-tooltip". (#1011)

src/dependents.ts
当一个模块没有默认的导出变量时，使用不带括号的import语法（类似于import a from 'b')，可能会导致错误。
=> fix(dependents): fix SyntaxError of import. (#954)

src/index.ts
rename `StackededColumnLine` to `StackedColumnLine`
=> fix: fix chart name typo

src/plots/donut/component/ring-statistic.ts, src/plots/donut/component/statistic.ts, src/plots/donut/layer.ts
- mark `totalLabel` as optional
- mark `triggerOn` as optional
- mark `triggerOff` as optional
- Improve `content` type definition
- fix typo
=> fix(types): fix Donut statistic type definitions

src/plots/line/layer.ts
fix `LineChart` render error without data provide
```
Uncaught TypeError: Cannot read property 'length' of undefined
```
demo: https://codesandbox.io/s/condescending-flower-qrffp
=> fix: fix line renderer without data

src/dependents.ts, src/index.ts, src/plots/line/layer.ts
1 . 折线图的 point stroke 不能写死，shape为空心的时候stroke无法配置
2. GestureController 注册放到了dependence中，作为核心依赖，便于按需使用。
=> 折线图的 point stroke 不能写死，shape为空心的时候stroke无法配置

src/plots/grouped-bar/layer.ts
=> fix: prevent js error when adjust tooltip

docs/manual/getting-started.en.md
Close #1230
The url for General configurations at [Getting Started](https://g2plot.antv.vision/en/docs/manual/getting-started#more) leads to a [404 page](https://g2plot.antv.vision/en/docs/manual/general-config). Removed the referene to it and also fixed some typos.
=> docs: remove url for General configurations and fix typos

src/plots/pie/component/label/spider-label.ts, src/plots/pie/layer.ts, src/plots/pie/utils.ts
数据process的时候，数据全空或者全0时，保留originValue
spider-label展示label的时候，取originKey对应的originValue
close #1241
=> fix(issue-1241): 修复饼、环 label设置为spider，数据都为0时，展示为1

__tests__/unit/core/index-spec.ts, __tests__/unit/plots/line/animation-spec.ts, __tests__/unit/plots/line/point-spec.ts, src/common/adaptor.ts, src/index.ts, src/plots/line/adaptor.ts, src/plots/line/types.ts, src/plots/pie/adaptor.ts, src/plots/tiny-line/adaptor.ts, src/plots/tiny-line/types.ts, src/types/animation.ts, src/types/common.ts
=> feat: line options

__tests__/bugs/issue-1245-spec.ts, src/plots/pie/adaptor.ts
=> feat(v2/pie): 饼图字段配置错误处理

__tests__/unit/plots/area/animation-spec.ts, __tests__/unit/plots/area/axis-spec.ts, __tests__/unit/plots/area/index-spec.ts, __tests__/unit/plots/area/label-spec.ts, __tests__/unit/plots/area/line-spec.ts, __tests__/unit/plots/area/point-spec.ts, __tests__/unit/plots/area/shape-spec.ts, __tests__/unit/plots/area/style-spec.ts, __tests__/unit/plots/area/tooltip-spec.ts, src/index.ts, src/plots/area/adaptor.ts, src/plots/area/index.ts, src/plots/area/types.ts, src/plots/line/adaptor.ts, src/plots/radar/adaptor.ts
=> feat(area): add plot area

__tests__/unit/plots/column/index-spec.ts, __tests__/unit/plots/column/label-spec.ts, src/plots/column/adaptor.ts, src/plots/column/types.ts
=> feat(v2/column): support groupField/stackField options

__tests__/unit/plots/column/index-spec.ts, src/adaptor/geometries/index.ts, src/adaptor/geometries/interval.ts, src/plots/column/adaptor.ts
=> feat(v2/column): extract common interval geometry

src/plots/pie/component/label/spider-label.ts
=> fix: 修改蜘蛛网布局中被剔除 label 仍出现在画布（左上角）

__tests__/unit/plots/waterfall/waterfall-spec.ts, docs/manual/plots/waterfall.en.md, docs/manual/plots/waterfall.zh.md, examples/column/waterfall/demo/basic.js, src/plots/waterfall/component/label/waterfall-label.ts, src/plots/waterfall/layer.ts
> 需求点：瀑布图存在js显示精度问题，`diffLabel` 可以通过 `formatter` 处理，不过 `label.formatter`失效。[演示链接](https://codesandbox.io/s/vigilant-lichterman-zfhz0)
1. 因为瀑布图中的 `label` 内容展示是通过后续计算得到的，处理方式是把原有的 `label.formatter` 处理逻辑重新载入
2. 在原有的 `waterfall-spec.ts` 中新增单测
3. 删除瀑布图多余的默认配置项 `data`
=> fix(waterfall): 修复瀑布图label.formatter失效问题

__tests__/unit/core/index-spec.ts, src/core/plot.ts
- 属性配置的方式
```ts
const line = new Line({
event: {
'element:click': () => {},
}
});
```
> 优点：保持兼容性，完全配置化
> 缺点：代码相对复杂，需要去 diff events 配置，然后做 bind 和 unbind（echarts 做 react 包装的时候遇到这个问题）
- API 的方式
```ts
const line = new Line({ /*...*/ });
line.on('element:click', () => {});
```
> 优点：代码简单，完全继承 G2 能力（echarts 使用这个方式）
> 缺点：和 v1 不兼容
大家看看哪种比较好，或者还有其他的方面没有考虑到
----
=> feat(event): add plot events bind

src/plots/pie/component/label/spider-label.ts, src/plots/pie/layer.ts
=> fix: 修复全 0 数据饼图 spider 布局 label 报错的问题

__tests__/unit/plots/histogram/index-spec.ts, package.json
dataset升级了，需要修改histogram直方图的测试用例
=> test: 修改histogram直方图的测试用例

__tests__/unit/core/index-spec.ts, __tests__/unit/plots/pie/state-spec.ts, examples/pie/basic/demo/meta.json, examples/pie/basic/demo/pie-state.ts, src/adaptor/common.ts, src/core/plot.ts, src/plots/pie/adaptor.ts, src/plots/pie/types.ts, src/types/common.ts, src/types/index.ts, src/types/state.ts, src/utils/geometry.ts, src/utils/index.ts
先看下思路，没问题再补充：文档、测试用例、接入到每个 plot 中
**others**
~~默认状态（后续再考虑，现状业务层自己可以满足）~~
~~组件联动（设置状态的时候，联动 tooltip、legend、axis 等，是否必须，待定）~~
**checklist**
=> feat(state): 添加 setState 方法，通过条件设置三种状态的激活与否

examples/biax/basic/API.zh.md, examples/histogram/basic/API.en.md, examples/histogram/basic/API.zh.md, package.json
[lint-md](https://github.com/lint-md/lint-md) 自卖自夸，目前社区最好的中文 markdown lint 工具。现在加入用来检测 markdown 文档。规则可以看这个项目的 [README 最下面](https://github.com/lint-md/lint-md#%E6%A3%80%E6%9F%A5%E7%B1%BB%E5%9E%8B)。
=> feat(lint-md): add markdown lint & fix markdown error

src/plots/_template/adaptor.ts, src/plots/_template/index.ts, src/plots/_template/types.ts, src/plots/dual-axes/adaptor.ts, src/plots/dual-axes/index.ts
=> chore(template): add plot template

__tests__/unit/plugin/index-spec.ts, __tests__/unit/plugin/step-line.ts, src/core/plot.ts, src/index.ts, src/plugin/index.ts
使用方式 示例：
- 封装并发布 g2plot-step-line
``` ts
import { Params, Options } from '@antv/g2plot';
export interface StepLineOption extends Options {
readonly xField: string;
readonly yField: string;
readonly stepType?: 'vh' | 'hv' | 'vhv' | 'hvh';
}
/** 这个方法作为一个包 export 出去 */
export function StepLineAdaptor(params: Params<StepLineOption>): Params<StepLineOption> {
const { chart, options } = params;
const { xField, yField, stepType = 'vh', data } = options;
chart.line().position(`${xField}*${yField}`).shape(stepType);
chart.data(data);
return params;
}
```
- 使用三方包
```ts
import { G2Plot } from '@antv/g2plot';
import { StepLineAdaptor, StepLineOption } from 'g2plot-step-line';
const plot = new G2Plot<StepLineOption>('container', {
width: 400,
height: 300,
appendPadding: 10,
data,
xField: 'date', …
```
=> feat(plugin): add plugin plot for customize

__tests__/unit/plots/liquid/index-spec.ts, __tests__/unit/plots/liquid/liquid-style-spec.ts, src/index.ts, src/plots/_template/adaptor.ts, src/plots/liquid/adaptor.ts, src/plots/liquid/index.ts, src/plots/liquid/shapes/liquid.ts, src/plots/liquid/types.ts, src/types/style.ts, src/utils/g-util.ts
=> feat(liquid): add new plot liquid

__tests__/unit/plots/bullet/axis-spec.ts, __tests__/unit/plots/bullet/index-spec.ts, __tests__/unit/plots/bullet/label-spec.ts, __tests__/unit/plots/bullet/layout-spec.ts, examples/bullet/basic/API.en.md, examples/bullet/basic/API.zh.md, examples/bullet/basic/demo/layout.ts, examples/bullet/basic/demo/meta.json, src/plots/bullet/adaptor.ts, src/plots/bullet/index.ts, src/plots/bullet/types.ts
1. 首先修复某个分支被合并掉的代码；
2. 支持竖着方向的子弹图  #1560
=> feat: v2增强子弹图

src/adaptor/geometries/base.ts, src/adaptor/geometries/interval.ts, src/core/adaptor.ts
=> fix(geometry): 修改 geometry/base 中存在多个相同的时候,导致索引出错

package.json, src/index.ts
add smart tips for G2Plot examples
=> fix: fix api-extractor does not support the export * as syntax

examples/liquid/basic/demo/style.ts, src/plots/liquid/adaptor.ts, src/plots/liquid/index.ts, src/plots/liquid/types.ts, src/plots/ring-progress/adaptor.ts, src/plots/ring-progress/types.ts, src/types/index.ts, src/types/statistic.ts
----
环图 的中心文本，formatter 提供的数据不一样，不确定是否可以统一。
=> refactor(statistic): 统一中心文本结构

examples/word-cloud/basic/demo/basic.ts, examples/word-cloud/basic/demo/image-mask.ts, src/core/plot.ts, src/plots/word-cloud/index.ts
=> fix(word-cloud): word cloud should exec data-set transform when resize

__tests__/unit/plots/bullet/axis-spec.ts, __tests__/unit/plots/bullet/index-spec.ts, __tests__/unit/plots/bullet/label-spec.ts, __tests__/unit/plots/bullet/legend-spec.ts, __tests__/unit/plots/bullet/tooltip-spec.ts, examples/bullet/basic/API.en.md, examples/bullet/basic/API.zh.md, examples/bullet/basic/demo/basic.ts, examples/bullet/basic/demo/color.ts, examples/bullet/basic/demo/grouped.ts, examples/bullet/basic/demo/layout.ts, examples/bullet/basic/demo/stacked.ts, package.json, src/plots/bullet/adaptor.ts, src/plots/bullet/index.ts, src/plots/bullet/types.ts
- 增加目标值label显示，增加一个api（targetLabel）
- #1599
=> feat: 增加显示目标值label #1599

src/plots/bullet/adaptor.ts, src/plots/bullet/index.ts
=> fix(v2-bullet): 修复legend错误

src/plots/word-cloud/index.ts
在把`processImageMask`有`callback`形式改为`Promise`时，不小心改出的一个bug。
=> fix(word-cloud): 修复this指向问题

__tests__/unit/plots/tiny-area/index-spec.ts, __tests__/unit/plots/tiny-column/index-spec.ts, __tests__/unit/plots/tiny-line/index-spec.ts, examples/tiny-area/basic/demo/area-style.ts, examples/tiny-area/basic/demo/area.ts, examples/tiny-column/basic/demo/column.ts, examples/tiny-line/basic/demo/line.ts, gatsby-config.js, src/plots/tiny-line/constants.ts
=> fix(tiny): tiny 图的 tooltip 默认给一个格式化,修改 demo 和单测

__tests__/unit/utils/template-spec.ts, src/utils/template.ts
=> fix(template): remove regex usage of lookbehind assertions

package.json, webpack.config.js
=> build(webpack): update webpack loader configure, to avoid umd bundle error

__tests__/bugs/issue-1758-spec.ts, src/plots/tiny-area/index.ts
=> fix(1758): 面积图 line.color 设置不生效的问题

__tests__/bugs/issue-1758-spec.ts, __tests__/bugs/issue-1761-spec.ts, src/plots/area/adaptor.ts, src/plots/line/adaptor.ts
=> fix(1761): 辅助 geometry 的 color 样式跟随主元素的 color 配置

__tests__/bugs/issue-1754-spec.ts, __tests__/unit/plots/word-cloud/color-spec.ts, __tests__/unit/plots/word-cloud/index-spec.ts, __tests__/unit/plots/word-cloud/style-spec.ts, __tests__/unit/utils/transform/word-cloud-spec.ts, docs/manual/plots/word-cloud.en.md, docs/manual/plots/word-cloud.zh.md, examples/word-cloud/basic/API.en.md, examples/word-cloud/basic/API.zh.md, examples/word-cloud/basic/demo/color-field.ts, examples/word-cloud/basic/demo/custom-tooltip.ts, examples/word-cloud/basic/demo/meta.json, package.json, src/plots/word-cloud/adaptor.ts, src/plots/word-cloud/index.ts, src/plots/word-cloud/shapes/word-cloud.ts, src/plots/word-cloud/types.ts, src/plots/word-cloud/utils.ts, src/utils/transform/word-cloud.ts
=> fix(word-cloud): fix tooltip and add demo for custom tooltip

src/adaptor/geometries/point.ts, src/plots/line/adaptor.ts
1⃣️ point geometry 通道需要指定 shapeField，不直接使用 seriesField
2⃣️ line plot 默认将 seriesField 作为 shapeField，作为 shape 回调参数使用，但是默认 shape 为 circle
=> fix(point-shape): 修复 point 的 shape 映射

__tests__/bugs/issue-1754-spec.ts, examples/word-cloud/basic/demo/custom-tooltip.ts, src/plots/word-cloud/index.ts
=> fix(word-cloud): 修复tooltip小圆点的颜色不显示

__tests__/bugs/issue-1754-spec.ts, __tests__/unit/core/index-spec.ts, __tests__/unit/plots/column/percent-spec.ts, __tests__/unit/plots/line/y-meta-min-max-spec.ts, __tests__/unit/utils/data-spec.ts, __tests__/unit/utils/transform/histogram-spec.ts, src/adaptor/geometries/line.ts, src/constant.ts, src/plots/gauge/adaptor.ts, src/plots/heatmap/index.ts, src/plots/line/index.ts, src/plots/sunburst/adaptor.ts, src/plots/tiny-area/index.ts, src/types/axis.ts, src/types/common.ts, src/types/index.ts, src/types/meta.ts, src/utils/data.ts, src/utils/transform/percent.ts
=> fix(line): when data all gt 0, or lt 0, set the default min/max

examples/general/annotation/index.en.md
=> fix: correct spelling

src/constant.ts
=> feat: add axis base, exponent option to scale

.github/workflows/ci.yml
close #1826
https://github.com/coverallsapp/github-action#troubleshooting
=> fix: coveralls ci not working

__tests__/bugs/issue-1836-spec.ts, src/plots/gauge/adaptor.ts
=> fix(#1836): fix gauge animate not work

__tests__/unit/plots/bullet/index-spec.ts, __tests__/unit/plots/bullet/label-spec.ts, src/plots/bullet/adaptor.ts
=> test: 提升bullet的测试覆盖率以及优化代码

__tests__/unit/core/index-spec.ts, __tests__/unit/plots/scatter/legend-spec.ts, src/types/animation.ts, src/types/axis.ts, src/types/legend.ts
类型定义只允许 false（true 可用但是不建议，使用方式上统一）
=> fix: type define of legend, axis

__tests__/unit/plots/histogram/index-spec.ts, __tests__/unit/utils/path-spec.ts, src/utils/path.ts
=> test: coverage for util/path

site/pages/index.zh.tsx
https://github.com/antvis/gatsby-theme-antv/pull/240
=> docs: update banner notifications

__tests__/bugs/issue-1882-spec.ts, src/core/plot.ts
=> fix(#1882): add limitInPoit options for G2.Chart

__tests__/bugs/issue-1882-spec.ts, package.json, src/core/plot.ts, src/index.ts
=> revert: limitInPlot

.github/workflows/preview.yml
修复部署了原始分支而不是 PR 所在分支的问题。
https://github.com/afc163/surge-preview/issues/62
=> fix: surge preview in wrong ref

__tests__/unit/utils/kebab-case-spec.ts, src/utils/kebab-case.ts
=> test: coverage for util

__tests__/bugs/issue-1944-spec.ts, __tests__/unit/plots/tiny-column/index-spec.ts, __tests__/unit/plots/tiny-line/index-spec.ts, src/constant.ts, src/plots/tiny-column/constants.ts, src/plots/tiny-line/constants.ts
=> fix: remove tiny default formatter & mask in axis not work

__tests__/unit/adaptor/conversion-tag-spec.ts, __tests__/unit/utils/conversion-spec.ts, src/adaptor/conversion-tag.ts, src/utils/conversion.ts
=> test: coverage for conversion-tag

__tests__/bugs/issue-1882-spec.ts, __tests__/unit/core/index-spec.ts, src/core/plot.ts, src/types/common.ts
- 打开 limitInPlot 配置
- fixed: https://github.com/ant-design/ant-design-charts/issues/326
=> feat: 打开 limit in plot 配置

__tests__/unit/plots/area/index-spec.ts, __tests__/unit/plots/line/index-spec.ts, examples/area/basic/demo/basic-gradients.ts, examples/area/basic/demo/basic.ts, src/constant.ts, src/plots/line/adaptor.ts
=> fix(line): do not set default range as [0, 1]

__tests__/bugs/issue-1882-spec.ts, __tests__/unit/plots/area/limit-in-plot-spec.ts, __tests__/unit/plots/bar/limit-in-plot-spec.ts, __tests__/unit/plots/column/limit-in-plot-spec.ts, __tests__/unit/plots/line/limit-in-plot-spec.ts, package.json, src/adaptor/common.ts, src/plots/area/adaptor.ts, src/plots/column/adaptor.ts, src/plots/line/adaptor.ts
yAxis 没有设置 min/max 的时候 自动设置 limitInPlot 为false，否则设置为 true
=> feat: auto set limitInPlot based on yAxis config

__tests__/bugs/issue-2021-spec.ts, src/plots/tiny-area/adaptor.ts, src/plots/tiny-column/adaptor.ts, src/plots/tiny-line/adaptor.ts, src/plots/tiny-line/constants.ts
|---|---|
|  ![image](https://user-images.githubusercontent.com/7856674/100447336-5b2c2680-30eb-11eb-9afa-f84c48477e20.png) |  ![image](https://user-images.githubusercontent.com/7856674/100447260-3f288500-30eb-11eb-8881-94cbc481dc7f.png)  |
|  设置最大为 1000，设置 yAxis.max = 2000 不生效，修改后生效！  |   |
=> fix(tiny): 迷你三个图的 yAxis.min/max 设置不生效

__tests__/unit/adaptor/common-spec.ts, __tests__/unit/plots/bidirectional-bar/limit-in-plot-spec.ts, __tests__/unit/plots/dual-axes/limit-in-plot-spec.ts, src/adaptor/common.ts, src/plots/bidirectional-bar/adaptor.ts, src/plots/dual-axes/adaptor.ts
问题描述：
在多 view 图表中，设置了 min 和负值以后，底线超出，chart.limitInPlot 不起作用
解决方案：
根据 chart.limitinplot 和 yaxis 中的 min max 值，为每个 view 增加 limitInPlot
相关问题：
对称条形图有类似问题，一并修复， @arcsin1  可以帮忙cr下代码
=> fix: 双轴图和对称条形图的 limitinplot

__tests__/bugs/issue-2015-spec.ts, __tests__/unit/plots/scatter/default-config-spec.ts, __tests__/unit/plots/scatter/legend-spec.ts, __tests__/unit/plots/scatter/tooltip-spec.ts, src/plots/scatter/adaptor.ts, src/plots/scatter/index.ts
- 修复散点图 tooltip 默认内容提示不全
- 优化 tooltip 默认配置
- closed #2015 
修改前
修改后
=> fix: 修复散点图 tooltip 默认 fields 丢失

__tests__/bugs/issue-2021-spec.ts, __tests__/unit/plots/dual-axes/column-spec.ts, __tests__/unit/plots/dual-axes/interaction-spec.ts, __tests__/unit/plots/funnel/compare-spec.ts, __tests__/unit/plots/gauge/shapes/index-spec.ts, __tests__/unit/plots/pie/html-statistic-spec.ts, examples/dual-axes/dual-line/demo/custom-dual-line.ts, src/plots/dual-axes/util/geometry.ts
=> fix: 双轴图 label.formatter

__tests__/unit/plots/bar/index-spec.ts, __tests__/unit/plots/bar/legend-spec.ts, __tests__/unit/plots/histogram/axis-spec.ts, __tests__/unit/plots/histogram/index-spec.ts, package.json, src/core/plot.ts, src/plots/bar/adaptor.ts
关联 PR https://github.com/antvis/G2/pull/3055
条形图中，按照设计师的需求，数据是从上玩下看，实现方式是对数据逆序，导致图例/tooltip的顺序和柱子视觉顺序在某些情况不一致，所以在 G2Plot 中对条形图的默认选项做对应调整：
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/100747681-56ce7900-341d-11eb-95fb-b156d7a6cdaf.png) | ![image](https://user-images.githubusercontent.com/1142242/100747816-7f567300-341d-11eb-8b6f-b1236a2c4077.png) |
=> fix(bar): adjust default legend and tooltip order

__tests__/bugs/issue-2054-spec.ts, src/plots/pie/adaptor.ts
- feat: 添加bugs测试
- fix(issue-2054): 修复数据为 0，label 设置 `content: '{percentage}'` 显示 null
| Before | After |
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/100850890-6dc5a780-34bf-11eb-8be0-d31487ff498b.png)|![image](https://user-images.githubusercontent.com/15646325/100850769-41119000-34bf-11eb-9eff-3c7ccfb34706.png)|
=> fix pie label percentage

__tests__/unit/plots/area/label-spec.ts, __tests__/unit/plots/bar/label-spec.ts, __tests__/unit/plots/column/label-spec.ts, __tests__/unit/plots/line/label-spec.ts, src/plots/area/adaptor.ts, src/plots/bar/adaptor.ts, src/plots/column/adaptor.ts, src/plots/line/adaptor.ts
为 Line/Area/Column/Bar 加上默认的 的 label layout，如果用户有配置，则以用户配置为准
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/100870303-5d222b00-34d9-11eb-8f58-ff25797ab1bf.png) | ![image](https://user-images.githubusercontent.com/1142242/100870343-70cd9180-34d9-11eb-86e2-bba6a3feb289.png) |
=> feat: add default label layout for line/area/column/bar

__tests__/bugs/issue-2078-spec.ts, __tests__/unit/plots/waterfall/component-spec.ts, src/plots/waterfall/adaptor.ts
修复瀑布图(waterfall) 设置 `tooltip: false` 失效
=> fix(issue-2078): 修复 waterfall 无法关闭 tooltip

__tests__/bugs/issue-2064-spec.ts, src/plots/area/adaptor.ts, src/plots/line/adaptor.ts, src/plots/radar/adaptor.ts
- 给 geometry adaptor 添加 config 配置，允许 geometry adaptor 跳过某些步骤
- line/area/radar 等大部分图形有自己的 label adaptor，需要调整基础 geometry 中内置的 label 处理逻辑
=> fix: fix duplicated label renderde for line and area plot

__tests__/unit/plots/scatter/data-spec.ts, __tests__/unit/utils/get-meta-spec.ts, src/plots/scatter/adaptor.ts, src/plots/scatter/util.ts
=> feat: 散点图一个数据点时调整 min max

__tests__/bugs/issue-2015-spec.ts, __tests__/unit/plots/scatter/tooltip-spec.ts, __tests__/unit/utils/tooltip-spec.ts, src/types/tooltip.ts, src/utils/tooltip.ts
|  before  |  after  |
|---|---|
|  ![image](https://user-images.githubusercontent.com/7856674/101147655-a1d3d080-3657-11eb-9817-14a9b7ea207f.png)  |  ![image](https://user-images.githubusercontent.com/7856674/101147697-aef0bf80-3657-11eb-9342-00b7b09483d0.png) |
| 桑基图节点其实信息有限，所以不显示 tooltip  |   |
=> fix(sankey): close sankey node tooltip

__tests__/unit/plots/area/tooltip-spec.ts, __tests__/unit/plots/line/tooltip-spec.ts, __tests__/unit/plots/radar/tooltip-spec.ts, __tests__/unit/plots/tiny-area/index-spec.ts, __tests__/unit/plots/tiny-line/index-spec.ts, src/plots/area/adaptor.ts, src/plots/line/adaptor.ts, src/plots/radar/adaptor.ts, src/plots/tiny-area/adaptor.ts, src/plots/tiny-line/adaptor.ts
修复折线上图上 tooltip 有时会出现重复的 tooltip items，原因为多个 geometry 的 tooltip 同时显示出来了：
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/101505021-d83e8200-39ae-11eb-82eb-c87c395e6b98.png) | ![image](https://user-images.githubusercontent.com/1142242/101505154-ff954f00-39ae-11eb-8f06-f5cdd0ae0a49.png) |
=> fix: only enable tooltip for primary geometry for line/area/radar

__tests__/bugs/issue-2080-spec.ts, __tests__/unit/plots/pie/statistic-spec.ts, __tests__/unit/utils/statistic-spec.ts, src/plots/pie/adaptor.ts
=> fix(pie-statistic): 修复环图中心文本从 false 更新为 null，读取空对象属性出错

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, __tests__/bugs/issue-1909-spec.ts, __tests__/bugs/issue-charts-367-spec.ts, __tests__/unit/plots/liquid/index-spec.ts, __tests__/unit/plots/liquid/liquid-style-spec.ts, docs/manual/plots/liquid.en.md, docs/manual/plots/liquid.zh.md, examples/liquid/basic/demo/basic.ts, src/plots/liquid/adaptor.ts, src/plots/liquid/index.ts, src/plots/liquid/shapes/liquid.ts, src/plots/liquid/types.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/7856674/101867381-f6c29a00-3bb5-11eb-981b-56afd747c531.png)    |  ![image](https://user-images.githubusercontent.com/7856674/101867345-df83ac80-3bb5-11eb-96d5-b940f4d386c0.png)  |
=> feat(liquid): add outline, wave options for customize

__tests__/unit/core/index-spec.ts, __tests__/unit/plots/histogram/axis-spec.ts, __tests__/unit/plots/histogram/index-spec.ts, src/core/plot.ts, src/plots/line/types.ts
1. 调整默认的 autoHide 配置
|----|----|
| ![image](https://user-images.githubusercontent.com/1142242/100538364-517cfd00-326a-11eb-9a09-1ba080ad86a9.png)| ![image](https://user-images.githubusercontent.com/1142242/100538359-3f02c380-326a-11eb-953a-dcd451a7af6f.png)| 
2. 修复折线图类型错误，close #2104
=> 修复折线图类型错误 & 调整默认 autoHide 配置

__tests__/bugs/issue-2096-spec.ts, __tests__/unit/plots/chord/index-spec.ts
- test: 修复 chord 测试挂了
- test: 增加单测，保证"开启中心文本交互时，显式注册 tooltip 交互可以开启 tooltip"
|----|----|
| ![](https://gw.alipayobjects.com/zos/antfincdn/tTOwFf211j/linshi-1.gif)  |  ![](https://gw.alipayobjects.com/zos/antfincdn/mu0RBA91Uo/linshi-2.gif) |
|解读：在某些场景下，环图开启中心文本交互时，需要开启开启 tooltip；这里可以通过显示声明 tooltip 交互即可|
=> 修复 chord 单测和增加 pie 单测

docs/api/plots/scatter.en.md, docs/api/plots/scatter.zh.md
close: #1657
|----|----|
|  ❌  |  ✅  |
=> docs: 修复链接 404

__tests__/bugs/issue-2124-spec.ts, __tests__/unit/plots/funnel/basic-spec.ts, __tests__/unit/plots/funnel/compare-spec.ts, __tests__/unit/plots/funnel/conversion-tag-spec.ts, __tests__/unit/plots/funnel/dynamic-height-spec.ts, __tests__/unit/plots/funnel/facet-spec.ts, __tests__/unit/utils/conversion-spec.ts, src/adaptor/conversion-tag.ts, src/plots/funnel/adaptor.ts, src/plots/funnel/geometries/common.ts, src/plots/funnel/geometries/dynamic-height.ts, src/utils/conversion.ts
|----|----|
|    |  ![image](https://user-images.githubusercontent.com/7856674/102994503-27151b80-455a-11eb-9791-a2cafddba36b.png)  |
对于数据存在 0， null 等非法数字的时候，和条形图使用一样的转化率逻辑。
=> fix(#2124): fix funnel crash when data contains null, 0

__tests__/unit/plots/bullet/label-spec.ts, src/plots/bullet/adaptor.ts, src/plots/bullet/types.ts
给 bullet 的 label 添加默认的 layout
close https://github.com/antvis/G2Plot/issues/1914
|----|----|
|  ![image](https://user-images.githubusercontent.com/1142242/103052335-da6e2680-45d3-11eb-9e53-78341eef57c8.png) |  ![image](https://user-images.githubusercontent.com/1142242/103052260-a7c42e00-45d3-11eb-8379-7b28152a1626.png) |
=> feat: add default label layout for bullet

CHANGELOG.md, package.json, src/index.ts
=> feat: chore: release 2.3.4

__tests__/bugs/issue-2124-spec.ts, src/plots/funnel/geometries/common.ts, src/plots/funnel/geometries/dynamic-height.ts
|----|----|
|  ❌  |  <img width="733" alt="屏幕快照 2020-12-28 09 58 42" src="https://user-images.githubusercontent.com/11748654/103184457-54175480-48f3-11eb-9ec0-43cd0ec7afb5.png"> | 
| 值为 undefined 时，图形合理渲染| |
=> fix: funnel undefined render

CHANGELOG.md, package.json, src/index.ts
=> chore: v2.3.5

__tests__/unit/core/index-spec.ts, __tests__/unit/plots/gauge/index-spec.ts, __tests__/unit/plots/gauge/statistic-spec.ts, __tests__/unit/plots/gauge/utils-spec.ts, __tests__/unit/plots/line/change-data-spec.ts, docs/api/plots/gauge.zh.md, examples/line/basic/demo/dynamic-line.ts, examples/line/basic/demo/line-with-data-marker.ts, examples/line/basic/demo/meta.json, examples/line/basic/demo/spline.ts, examples/progress-plots/gauge/demo/basic.ts, examples/progress-plots/gauge/demo/complex.ts, src/core/plot.ts, src/plots/gauge/adaptor.ts, src/plots/gauge/constant.ts, src/plots/gauge/index.ts, src/plots/gauge/utils.ts, src/plots/line/index.ts
- 使用 g2 的 `changeData` api 来更新数据，每个 plot 复写 core 的 `changeData` 方法（后续全面迁移完成后，设置为**抽象方法**）
- `core/plot` 提供 `updateOption` 方法
- 图表大致可以分为两类：数据为正常 Data 类型（无需转换） & 单数据、组合数据或 多view（数据转换），关于组合的，可以把数据获取抽取为通用纯函数，在 chagneData 的时候，也可以对数据进行相应转换，但存在问题是：逻辑会存在在 adpator 和 changeData 处，比较分散；
- 另外，为此提供两个示例验证下：折线图 和 仪表盘
|----|----|
| ![](https://gw.alipayobjects.com/zos/antfincdn/YSyzHbOmkX/dongtaigengxinzhexiantushuju.gif)   |  ![](https://gw.alipayobjects.com/zos/antfincdn/AlVS5aBYOi/dongtaigengxinzhexiantushuju2.gif)  |
=> feat: changedata

__tests__/unit/plots/area/change-data-spec.ts, __tests__/unit/plots/funnel/conversion-tag-spec.ts, examples/area/basic/demo/basic.ts, examples/area/basic/demo/meta.json, src/plots/area/adaptor.ts, src/plots/area/index.ts, src/plots/area/utils.ts
> 截图都是 gif，新 tab 打开可见
|----|----|
|  ![](https://gw.alipayobjects.com/zos/antfincdn/KjCCJ3DOmq/mianjitugengxinshuju-before.gif)  |  ![](https://gw.alipayobjects.com/zos/antfincdn/ST7cMsPsxS/mianjitugengxinshuju-after.gif)  |
=> feat: area support changeData

docs/api/plots/bar.en.md, docs/api/plots/bar.zh.md, docs/api/plots/column.en.md, docs/api/plots/column.zh.md, docs/common/connected-area.en.md, docs/common/connected-area.zh.md, docs/common/conversion-tag.en.md, docs/common/conversion-tag.zh.md, examples/area/percent/demo/meta.json, examples/bar/basic/demo/meta.json, examples/bar/basic/demo/width-ratio.ts, examples/bar/basic/demo/width.ts, examples/column/basic/demo/meta.json, examples/column/basic/demo/width-ratio.ts, src/adaptor/geometries/interval.ts, src/plots/bar/adaptor.ts, src/plots/bar/types.ts, src/plots/column/types.ts
Column plot supports `minColumnWidth` and `maxColumnWidth`, and bar plot   supports `minBarWidth` and `maxBarWidth`. With this feature, you can set pixel column or bar width.
|----|----|
|  ❌  |  ✅  |
=> feat: column and bar plot support pixel width setting

docs/api/plots/funnel.en.md, docs/api/plots/funnel.zh.md, examples/more-plots/funnel/demo/basic-transpose.ts, examples/more-plots/funnel/demo/compare-transpose.ts, src/index.ts, src/plots/funnel/index.ts
暴露 FUNNEL_CONVERSATION 变量，同时规范并修复使用此变量的 demo
=> [漏斗图] 暴露转化率给用户

__tests__/bugs/issue-2161-spec.ts, __tests__/unit/plots/radial-bar/utils-spec.ts, src/plots/radial-bar/utils.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/103467568-3fbbd780-4d8b-11eb-9613-b7d4b3baabbc.png)|  ![image](https://user-images.githubusercontent.com/15646325/103467585-611cc380-4d8b-11eb-961b-ce61375773ac.png) |
=> fix(issue-2161): 修复数据项存在非法 undefined 时，获取数据 max 为 NaN，导致玉珏图渲染页面崩溃

__tests__/bugs/bug-dual-axes-same-y-spec.ts, __tests__/unit/plots/dual-axes/util/option-spec.ts, gatsby-config.js, src/plots/dual-axes/adaptor.ts, src/plots/dual-axes/util/option.ts
=> fix(dual-axes): 双轴图的 y 字段相同的时候,导致 yaxis 配置被覆盖

__tests__/unit/plots/sankey/circle-spec.ts, __tests__/unit/plots/sankey/index-spec.ts, src/plots/sankey/adaptor.ts, src/plots/sankey/circle.ts
=> feat(sankey): remove the circle data in sankey

__tests__/unit/adaptor/geometries/interval-spec.ts, __tests__/unit/plots/bar/index-spec.ts, __tests__/unit/plots/column/index-spec.ts, __tests__/unit/plots/radial-bar/index-spec.ts, docs/api/plots/bar.en.md, docs/api/plots/bar.zh.md, docs/api/plots/column.en.md, docs/api/plots/column.zh.md, docs/api/plots/radial-bar.en.md, docs/api/plots/radial-bar.zh.md, docs/common/bar-style.en.md, docs/common/bar-style.zh.md, docs/common/column-style.en.md, docs/common/column-style.zh.md, examples/more-plots/radial-bar/demo/apple-watch-activity.ts, examples/more-plots/radial-bar/demo/background.ts, examples/more-plots/radial-bar/demo/meta.json, examples/more-plots/radial-bar/demo/round-corner.ts, src/adaptor/geometries/interval.ts, src/plots/bar/adaptor.ts, src/plots/bar/types.ts, src/plots/column/types.ts, src/plots/radial-bar/adaptor.ts, src/plots/radial-bar/index.ts, src/plots/radial-bar/types.ts
- **feat(column)**: column 新增配置项 ` columnBackground`
- **feat(bar)**: bar 新增配置项 `barBackground`
- **feat(radial-bar)**: radial-bar 新增配置项 `barBackground`、`minBarWidth`、`maxBarWidth`
- **docs(radial-bar)**:  优化玉珏图 demos ([前往](https://g2plot.antv.vision/en/examples/more-plots/radial-bar#basic))
- **docs**: 柱形图、条形图、玉珏图关于图形样式 文档更新，支持 `minWidth`、`maxWidth`、`background`
|----|----|
|![image](https://user-images.githubusercontent.com/15646325/103979579-07682f00-51b9-11eb-9e67-9bc280517a65.png)|![image](https://user-images.githubusercontent.com/15646325/103979601-1222c400-51b9-11eb-8bbe-10a61c64845a.png)|
|  ❌  |  ![image](https://user-images.githubusercontent.com/15646325/103979490-d982ea80-51b8-11eb-90cf-3e97c687950d.png) |
|  ❌  | …
=> feat: interval geometry 支持配置图形背景，支持图表: 柱、条形图，玉珏图

__tests__/unit/plots/rose/change-data-spec.ts, src/plots/rose/index.ts
override the changeData method of rose plot
=> feat: 玫瑰图修改 changeData && 添加单测

__tests__/bugs/issue-2180-spec.ts, src/plots/bidirectional-bar/adaptor.ts
|----|----|
|  ❌ ![1610442169237_953CEA85-4A39-4744-8729-998645C71923](https://user-images.githubusercontent.com/13724222/104298159-9ef1b880-54fe-11eb-821a-0f2efb41357c.png)  |  ✅ ![1610444834308_D9A559E4-AA24-4C8B-B31A-46D8104F0018](https://user-images.githubusercontent.com/13724222/104298213-aca73e00-54fe-11eb-9dbc-c1b1c6f6321d.png) |
=> fix: 对称条形图数据顺序问题

__tests__/unit/plots/radial-bar/change-data-spec.ts, __tests__/unit/plots/radial-bar/utils-spec.ts, src/plots/radial-bar/index.ts, src/plots/radial-bar/utils.ts
|----|----|
|  ![玉珏图before](https://user-images.githubusercontent.com/24318174/104293039-84b4dc00-54f8-11eb-9316-7ae72c8d327a.gif) | ![玉珏图after](https://user-images.githubusercontent.com/24318174/104293457-fdb43380-54f8-11eb-9fb0-9f1dc0d5fa6a.gif)
|
=> fix: 修复玉珏图changeData时未同步变更scale

__tests__/unit/plots/bullet/axis-spec.ts, __tests__/unit/plots/bullet/index-spec.ts, docs/api/plots/bullet.en.md, docs/api/plots/bullet.zh.md, docs/manual/plots/bullet.en.md, docs/manual/plots/bullet.zh.md, examples/more-plots/bidirectional-bar/demo/layout.ts, examples/more-plots/box/demo/basic.ts, examples/more-plots/stock/demo/basic.ts, examples/more-plots/sunburst/demo/basic.ts, examples/more-plots/waterfall/demo/absolute-label.ts, examples/more-plots/word-cloud/demo/image-mask-base64.ts, examples/progress-plots/bullet/demo/basic.ts, examples/progress-plots/bullet/demo/color.ts, examples/progress-plots/bullet/demo/grouped.ts, examples/progress-plots/bullet/demo/layout.ts, examples/progress-plots/bullet/demo/meta.json, examples/progress-plots/bullet/demo/stacked.ts, examples/progress-plots/liquid/demo/style.ts, examples/scatter/bubble/demo/axis-right.ts, src/plots/bullet/adaptor.ts, src/plots/bullet/index.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/104805872-2ba5ba80-580e-11eb-9058-a51e0873e586.png) | ![image](https://user-images.githubusercontent.com/15646325/104805879-352f2280-580e-11eb-8112-bd30a44f2370.png)|
=> refactor(bullet): 子弹图升级下 & 修复 axis 配置失效

__tests__/unit/plots/bullet/change-data-spec.ts, src/plots/bullet/adaptor.ts, src/plots/bullet/index.ts
override the changeData method of Bullet plot
|----|----|
|![子弹图before](https://user-images.githubusercontent.com/24318174/104566780-ff146600-5688-11eb-95b0-7cade7712a29.gif)|![子弹图after](https://user-images.githubusercontent.com/24318174/104566798-05a2dd80-5689-11eb-9eed-86d95b325748.gif)|
=> feat: 重写子弹图changeData方法 && 添加单测

__tests__/unit/plots/treemap/rect-style-spec.ts, __tests__/unit/plots/treemap/utils-spec.ts, docs/api/plots/treemap.en.md, docs/api/plots/treemap.zh.md, src/plots/treemap/adaptor.ts, src/plots/treemap/types.ts, src/plots/treemap/utils.ts
|----|----|
|  ❌  |  <img width="584" alt="屏幕快照 2021-01-17 18 35 10" src="https://user-images.githubusercontent.com/11748654/104837937-d7c0d180-58f2-11eb-951b-5b08c7f59e1e.png"> |
描述：用户可通过 rectStyle 配置图形样式，上述图片配置为 `rectStyle: { lineWidth: 5, fillOpacity: 0.7 }`
|----|----|
|  ❌  |  <img width="586" alt="屏幕快照 2021-01-17 18 38 27" src="https://user-images.githubusercontent.com/11748654/104838014-38e8a500-58f3-11eb-9790-bcc3982bb2f5.png"> |
描述：用户可通过 hierarchyConfig 对矩形树图的布局方式做高级配置，上述图片配置为 `hierarchyConfig: { tile: 'treemapDice' }`
=> feat: 为 treemap 新增rectstyle 和 hierarchyConfig 属性

__tests__/bugs/issue-2180-spec.ts, __tests__/unit/plots/bidirectional-bar/data-spec.ts, __tests__/unit/plots/bidirectional-bar/index-spec.ts, __tests__/unit/plots/bidirectional-bar/meta-spec.ts, __tests__/unit/plots/bidirectional-bar/utils-spec.ts, docs/api/plots/bidirectional-bar.en.md, docs/api/plots/bidirectional-bar.zh.md, docs/api/plots/bullet.en.md, docs/api/plots/column.en.md, docs/api/plots/dual-axes.en.md, docs/api/plots/heatmap.en.md, docs/api/plots/histogram.en.md, docs/api/plots/pie.en.md, docs/api/plots/radar.en.md, docs/api/plots/rose.en.md, docs/api/plots/scatter.en.md, docs/api/plots/stock.en.md, docs/api/plots/treemap.en.md, docs/api/plots/waterfall.en.md, docs/api/plots/word-cloud.en.md, src/plots/bidirectional-bar/adaptor.ts, src/plots/bidirectional-bar/constant.ts, src/plots/bidirectional-bar/types.ts, src/plots/bidirectional-bar/utils.ts
```ts
meta: {
'2016年耕地总面积': { alias: '耕地总面积' },
'2016年转基因种植面积': { alias: '转基因种植面积' },
},
```
|----|----|
| ![image](https://user-images.githubusercontent.com/15646325/105009956-1c28aa80-5a76-11eb-824b-3d98ad5b7993.png) |  ![image](https://user-images.githubusercontent.com/15646325/105009880-01563600-5a76-11eb-8b84-1ed2d65f6482.png) |
=> fix: 对称条形图 meta 支持 yField 设置别名

docs/api/plots/radial-bar.en.md, docs/api/plots/radial-bar.zh.md, docs/common/axis.zh.md, examples/more-plots/radial-bar/demo/line.ts, src/plots/radial-bar/adaptor.ts, src/plots/radial-bar/types.ts
=> feat(radial-bar): 玉珏图支持配置开始角度和结束角度

docs/api/plots/bar.en.md, docs/api/plots/bullet.en.md, docs/api/plots/column.en.md, docs/api/plots/dual-axes.en.md, docs/api/plots/gauge.en.md, docs/api/plots/heatmap.en.md, docs/api/plots/histogram.en.md, docs/api/plots/line.en.md, docs/api/plots/pie.en.md, docs/api/plots/progress.en.md, docs/api/plots/radar.en.md, docs/api/plots/radial-bar.en.md, docs/api/plots/ring-progress.en.md, docs/api/plots/rose.en.md, docs/api/plots/sankey.en.md, docs/api/plots/sunburst.en.md, docs/api/plots/tiny-area.en.md, docs/api/plots/tiny-column.en.md, docs/api/plots/tiny-line.en.md, docs/api/plots/treemap.en.md, docs/api/plots/waterfall.en.md, docs/api/plots/word-cloud.en.md, docs/common/bar-style.en.md, docs/common/chart-methods.en.md, docs/common/chord.en.md, docs/common/column-style.en.md, examples/general/annotation/API.en.md, examples/more-plots/bidirectional-bar/API.en.md
Supplement English documentation.
=> docs: 补充图表英文文档

__tests__/unit/core/index-spec.ts, __tests__/unit/plots/pie/annotation-spec.ts, __tests__/unit/plots/pie/data-spec.ts, __tests__/unit/plots/pie/index-spec.ts, __tests__/unit/plots/pie/statistic-spec.ts, __tests__/unit/plots/pie/utils-spec.ts, examples/dynamic-plots/basic/demo/dynamic-pie.ts, examples/dynamic-plots/basic/demo/meta.json, src/core/plot.ts, src/plots/pie/adaptor.ts, src/plots/pie/contants.ts, src/plots/pie/index.ts, src/plots/pie/utils.ts
|----|----|
|  ![动态更新数据-pie-before](https://user-images.githubusercontent.com/15646325/105461829-b849f000-5cc8-11eb-9e3e-5ba3f8c8280a.gif) | ![动态更新数据-pie-after](https://user-images.githubusercontent.com/15646325/105461835-bbdd7700-5cc8-11eb-8b7a-261b60667392.gif)|
|饼图中心文本从展示到隐藏再展示后，样式丢失 ||
|![](https://gw.alipayobjects.com/zos/antfincdn/lI%26kgW7%26%24J/zhongxinwenbencongyoudaowuzaidaoyou%2Cyangshidiushi.gif)|![](https://gw.alipayobjects.com/zos/antfincdn/G3sKp20YOE/zhongxinwenbencongyoudaowuzaidaoyou%2Cyangshibudiushi.gif)|
|![image](https://user-images.githubusercontent.com/15646325/105568380-ef291000-5d73-11eb-9390-232c3273dec2.png)|![image](https://user-images.githubusercontent.com/15646325/105568373-db7da980-5d73-11eb-8a31-57c5743f5239.png)|
=> feat(change-data): 饼图支持动态更新数据 & 其他若干处理，见 PR 描述

__tests__/unit/plots/pie/data-spec.ts, __tests__/unit/plots/pie/index-spec.ts, src/plots/pie/adaptor.ts, src/plots/pie/contants.ts
=> feat(pie): 饼图 geometry 默认对 elemenent 的 zIndex 进行反序

__tests__/unit/core/index-spec.ts, docs/api/components/annotations.en.md, docs/api/components/annotations.zh.md, docs/api/components/axis.en.md, docs/api/components/axis.zh.md, docs/api/components/label.en.md, docs/api/components/label.zh.md, docs/api/components/legend.en.md, docs/api/components/legend.zh.md, docs/api/components/scrollbar.en.md, docs/api/components/scrollbar.zh.md, docs/api/components/slider.en.md, docs/api/components/slider.zh.md, docs/api/components/tooltip.en.md, docs/api/components/tooltip.zh.md, docs/common/annotations.zh.md, docs/common/axis.en.md, docs/common/axis.zh.md, docs/common/scrollbar.en.md, docs/common/scrollbar.zh.md, docs/common/tooltip.en.md, docs/common/tooltip.zh.md, docs/styles/component.md, examples/more-plots/bidirectional-bar/demo/basic.ts, examples/more-plots/bidirectional-bar/demo/layout.ts
=> docs: 图表组件文档

__tests__/bugs/issue-2267-spec.ts, __tests__/data/sankey-energy.ts, __tests__/unit/plots/sankey/index-spec.ts, src/plots/sankey/adaptor.ts, src/plots/sankey/helper.ts, src/plots/sankey/index.ts, src/plots/sankey/types.ts, src/plots/treemap/interactions/actions/treemap-drill-down-action.ts
依赖 G2 的 PR https://github.com/antvis/G2/pull/3261
|----|----|
|  ❌  |  ✅  |
=> feat(sankey): add nodeWidth, nodePadding options

__tests__/unit/plots/radar/coordinate-spec.ts, docs/api/plots/radar.en.md, docs/api/plots/radar.zh.md, src/plots/radar/adaptor.ts, src/plots/radar/types.ts
> 雷达图新增  innerRadius、startAngle、endAngle
=> feat: 雷达图新增 innerRadius、startAngle、endAngle

__tests__/bugs/issue-2260-spec.ts, src/plots/gauge/index.ts, src/plots/liquid/index.ts, src/plots/pie/index.ts, src/plots/ring-progress/index.ts
**todo list**
|----|----|
|  ❌  |  ✅  |
=> fix: gague,pie,ring-progress,liquid 等 changedata 触发钩子事件

src/plots/gauge/adaptor.ts
=> feat(gauge): 仪表盘支持 annotations

__tests__/bugs/issue-2352-spec.ts, __tests__/bugs/issue-2353-spec.ts, docs/api/plots/sankey.en.md, docs/api/plots/sankey.zh.md, src/plots/sankey/adaptor.ts, src/plots/sankey/types.ts, src/utils/data.ts, src/utils/transform/sankey.ts
=> feat: sankey node depth configure

__tests__/unit/plots/sankey/change-data-spec.ts, __tests__/unit/plots/sankey/index-spec.ts, __tests__/unit/plots/word-cloud/index-spec.ts, __tests__/unit/utils/transform/sankey-spec.ts, src/plots/sankey/adaptor.ts, src/plots/sankey/constant.ts, src/plots/sankey/helper.ts, src/plots/sankey/index.ts, src/plots/sankey/types.ts, src/utils/data.ts, src/utils/transform/sankey.ts
=> feat(sankey): changeData API for sankey

docs/api/options/events.en.md, docs/api/options/events.zh.md
=> docs(typo): dblclick, not dbclick

__tests__/unit/plots/gauge/style-spec.ts, docs/api/plots/gauge.en.md, docs/api/plots/gauge.zh.md, src/plots/gauge/adaptor.ts, src/plots/gauge/shapes/meter-gauge.ts, src/plots/gauge/types.ts, src/plots/gauge/utils.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/109904471-4954b380-7cd8-11eb-9fa5-5aa4346c31c8.png) |  ![image](https://user-images.githubusercontent.com/15646325/109904395-20ccb980-7cd8-11eb-8079-b79f9ec9550d.png)|
|通过设置 `gaugeStyle.lineCap: 'round'`, 可以配置出圆角的仪表盘 |
=> feat(gauge): 仪表盘支持配置 style,支持圆角仪表盘

examples/dual-axes/column-line/demo/slider-column-line.ts, examples/plugin/association/demo/association-line.ts, examples/plugin/association/demo/meta.json, src/plots/multi-view/interactions/association.ts
|----|----|
|  ![](https://gw.alipayobjects.com/zos/antfincdn/lbvuBgmXse/line-assocation-before.gif)  |  ![](https://gw.alipayobjects.com/zos/antfincdn/B6tDZlQy5t/line-assocation-after.gif) |
=> fix(multi-view): 修复多图层图表折线图联动取数问题

docs/api/components/tooltip.en.md, docs/api/components/tooltip.zh.md, docs/common/marker.zh.md, docs/common/tooltip.en.md, docs/common/tooltip.zh.md
=> docs(tooltip): 更新 tooltip 关于 marker 的文档

docs/api/components/tooltip.en.md, docs/api/components/tooltip.zh.md, docs/common/label.en.md, docs/common/label.zh.md, docs/common/marker.zh.md, docs/common/tooltip.en.md, docs/common/tooltip.zh.md
=> docs: label-line 类型定义补全

__tests__/unit/plots/scatter/legend-spec.ts, src/plots/scatter/adaptor.ts, src/plots/scatter/types.ts
=> test(scatter-legend): 增加散点图图例用例（shapeLegend、sizeLegend）

__tests__/bugs/issue-2122-spec.ts, __tests__/unit/plots/scatter/color-spec.ts, __tests__/unit/plots/scatter/legend-spec.ts, docs/api/plots/scatter.en.md, docs/api/plots/scatter.zh.md, examples/scatter/scatter/demo/mapping-color-and-shape.ts, examples/scatter/scatter/demo/meta.json, src/plots/scatter/adaptor.ts, src/plots/scatter/types.ts
|----|----|
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/xqD9bPVmaU/4ecbc1e7-ebf0-4777-ad7b-7190a4db51e9.png)  |
=> feat(scatter): 散点图支持color和shape同时映射图例字段 & 添加单测

docs/manual/plots/pie.en.md, docs/manual/plots/pie.zh.md, docs/manual/plugin.en.md, docs/manual/plugin.zh.md, examples/plugin/multi-view/demo/combo-plot.ts, examples/plugin/multi-view/demo/meta.json
|----|----|
|  ❌  | ![](https://gw.alipayobjects.com/zos/antfincdn/GMzV%24DSDAX/68a9190b-a4eb-4ad4-be3b-4fef31595a3f.png)   |
=> docs(demo): 补充组合图表 demo & 增加一个插件图表

__tests__/bugs/issue-2394-spec.ts, src/plots/radial-bar/adaptor.ts
=> fix(radial-bar): 修复玉钰图存在非法数据崩溃问题 (#2394)

__tests__/bugs/issue-2220-spec.ts, __tests__/unit/plots/liquid/color-spec.ts, __tests__/unit/plots/liquid/index-spec.ts, __tests__/unit/plots/liquid/liquid-style-spec.ts, __tests__/unit/plots/pie/utils-spec.ts, docs/api/plots/liquid.en.md, docs/api/plots/liquid.zh.md, docs/manual/plots/liquid.en.md, docs/manual/plots/liquid.zh.md, docs/manual/plots/pie.en.md, examples/progress-plots/liquid/demo/custom-star.ts, examples/progress-plots/liquid/demo/meta.json, examples/progress-plots/liquid/demo/outline-style.ts, examples/progress-plots/liquid/demo/rect.ts, examples/progress-plots/liquid/demo/style.ts, src/plots/liquid/adaptor.ts, src/plots/liquid/constants.ts, src/plots/liquid/index.ts, src/plots/liquid/shapes/liquid.ts, src/plots/liquid/types.ts, src/plots/pie/adaptor.ts, src/plots/pie/index.ts, src/plots/pie/utils.ts, src/plots/radial-bar/adaptor.ts, src/plots/radial-bar/index.ts, src/utils/data.ts, src/utils/index.ts
|  Description  |  Preview  |
|----|----|
|  水波图支持跟随主题色切换  |  ![image](https://user-images.githubusercontent.com/15646325/112239991-79adc300-8c82-11eb-962e-141308a101de.png) |
| 水波图支持配置 outline 样式 | ![image](https://user-images.githubusercontent.com/15646325/112240201-dc06c380-8c82-11eb-9e19-d421de3e0fbb.png)|
=> feat(liquid): 水波图支持跟随主题色 & 水波图支持 outline 配置样式 & 文档以及 demo 优化

__tests__/unit/plots/treemap/lable-spec.ts, __tests__/unit/plots/treemap/tooltip-spec.ts, __tests__/unit/plots/treemap/utils-spec.ts, docs/api/plots/dual-axes.en.md, docs/api/plots/dual-axes.zh.md, docs/api/plots/treemap.en.md, docs/api/plots/treemap.zh.md, examples/more-plots/treemap/demo/drill-down.ts, examples/more-plots/treemap/demo/treemap-nest.ts, src/plots/treemap/adaptor.ts, src/plots/treemap/utils.ts
该 issue 需求是为矩形树图增加占比字段，但作为层级数据中。直接暴露占比很难定义，以及满足所有需求，因此暴露出 path 字段，储存当前节点的层级信息，方便用户根据需求快速计算占比
|----|----|
|  ❌  |  <img width="578" alt="屏幕快照 2021-03-23 17 05 50" src="https://user-images.githubusercontent.com/11748654/112147206-6285bb80-8c17-11eb-895e-da4edae82a70.png"> |
=> [issue-2369] 矩形树图增加 path 字段 

__tests__/unit/plots/dual-axes/theme-spec.ts, src/plots/dual-axes/adaptor.ts
|----|----|
|  <img width="534" alt="屏幕快照 2021-03-23 11 32 51" src="https://user-images.githubusercontent.com/11748654/112089106-f762c780-8bcb-11eb-82b5-34749cb15396.png"> |  <img width="537" alt="屏幕快照 2021-03-23 11 32 34" src="https://user-images.githubusercontent.com/11748654/112089117-fcc01200-8bcb-11eb-8e64-f17535a352cc.png">|
| 解读： 修复双轴图主题设置中坐标轴不生效的问题 |
=> fix: 双轴图 theme 主题设置

docs/manual/plots/area.en.md, docs/manual/plots/area.zh.md, docs/manual/plots/bar.en.md, docs/manual/plots/bar.zh.md, docs/manual/plots/column.en.md, docs/manual/plots/column.zh.md, docs/manual/plots/gauge.en.md, docs/manual/plots/gauge.zh.md, docs/manual/plots/line.en.md, docs/manual/plots/line.zh.md, docs/manual/plots/liquid.en.md, docs/manual/plots/liquid.zh.md, docs/manual/plots/scatter.en.md, docs/manual/plots/scatter.zh.md, docs/manual/plots/waterfall.en.md, docs/manual/plots/waterfall.zh.md, examples/component/annotation/demo/area-with-line-annotation.ts, examples/component/annotation/demo/line-annotation.ts, examples/component/annotation/demo/meta.json, gatsby-config.js
|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/115491418-87ab2f80-a292-11eb-8913-68ba1089a047.png)  |  ![image](https://user-images.githubusercontent.com/15646325/115491577-cc36cb00-a292-11eb-9990-067037466326.png) |
=> docs: 文档日常更新 & 网站导航增加周边生态

__tests__/unit/plots/sankey/type-spec.ts, src/plots/sankey/adaptor.ts
=> fix: 修改桑基图 的 来源字段 type 类型为cat

.github/workflows/build.yml, __tests__/unit/core/index-spec.ts, __tests__/unit/plots/sankey/draggable-spec.ts, __tests__/unit/plots/word-cloud/change-data-spec.ts, docs/api/plots/sankey.en.md, docs/api/plots/sankey.zh.md, package.json, src/plots/sankey/adaptor.ts, src/plots/sankey/constant.ts, src/plots/sankey/index.ts, src/plots/sankey/interactions/actions/node-drag.ts, src/plots/sankey/interactions/index.ts, src/plots/sankey/interactions/node-draggable.ts, src/plots/sankey/sankey/sankey.ts, src/plots/sankey/types.ts
|----|----|
|  ❌  |  ![Apr-27-2021 20-41-57](https://user-images.githubusercontent.com/7856674/116243045-1ccd8d00-a799-11eb-9ab8-c02bd48ab966.gif)  |
=> feat(sankey): add nodeDraggable interaction configure

__tests__/unit/plots/word-cloud/change-data-spec.ts, examples/component/tooltip/API.en.md, examples/component/tooltip/API.zh.md, examples/component/tooltip/demo/html-tooltip.ts, examples/component/tooltip/demo/meta.json, examples/component/tooltip/index.en.md, examples/component/tooltip/index.zh.md, gatsby-config.js
|  What  |  Screenshot  |
|----|----|
|  新增自定义 tooltip demo  |  ![image](https://user-images.githubusercontent.com/15646325/116844584-11091d00-ac16-11eb-9b35-76002b3723ef.png)  |
| 新增 [vis-dashboard](https://vis-dashboard.antv.vision) 周边生态 | ![image](https://user-images.githubusercontent.com/15646325/117094481-78e67180-ad96-11eb-821a-187f2b454e6a.png)|
=> examples: 添加若干 demo

package.json
=> feat: 支持上层 tree shaking

docs/manual/faq.en.md, docs/manual/faq.zh.md
在 FAQ 的地方说明了水波图不能设置带透明度和图片的背景。
=> docs: update FAQ for liquid background

__tests__/bugs/issue-2572-spec.ts, examples/column/grouped/demo/meta.json, examples/column/grouped/demo/tooltip-formatter.ts, src/plots/column/adaptor.ts, src/utils/index.ts
> 先行 G2Plot 处理，后续 G2 5.0 需要注意下 @hustcc 
**Tooltip behavior**
- **Default** works
- **Formatter** works
- **CustomContent** works
|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/119209676-801db700-bada-11eb-8a67-c509d055cc4b.png) | ![image](https://user-images.githubusercontent.com/15646325/119209681-93308700-bada-11eb-97b7-2db9b46fbec8.png) |
|![image](https://user-images.githubusercontent.com/15646325/119209713-d68af580-bada-11eb-8e61-e41c5f890f67.png)| ![image](https://user-images.githubusercontent.com/15646325/119209729-ef93a680-bada-11eb-8db9-caf3c66745e0.png)|
| ![image](https://user-images.githubusercontent.com/15646325/119209806-6af55800-badb-11eb-8cbd-0e437eeaa9e3.png) | ![image](https://user-images.githubusercontent.com/15646325/11 …
=> fix(#2572): 修复堆叠分组状图 tooltip 展示不正常 (只展示第一个小分组的数据)

__tests__/unit/adaptor/geometries/schema-spec.ts, __tests__/unit/plots/stock/color-spec.ts, __tests__/unit/plots/stock/style-spec.ts, __tests__/unit/plots/stock/tooltip-spec.ts, docs/api/graphic-style.zh.md, docs/api/plots/stock.en.md, docs/api/plots/stock.zh.md, docs/api/plots/waterfall.en.md, docs/common/crosshairs-text.en.md, docs/common/crosshairs-text.zh.md, docs/common/tooltip.en.md, docs/common/tooltip.zh.md, examples/more-plots/stock/demo/custom-color.ts, examples/more-plots/stock/demo/custom-crosshairs.ts, examples/more-plots/stock/demo/custom-style.ts, examples/more-plots/stock/demo/custom-tooltip.ts, examples/more-plots/stock/demo/meta-alias.ts, examples/more-plots/stock/demo/meta.json, examples/more-plots/stock/demo/slider.ts, src/adaptor/geometries/index.ts, src/adaptor/geometries/schema.ts, src/index.ts, src/plots/stock/adaptor.ts, src/plots/stock/constant.ts, src/plots/stock/types.ts
- **feat(stock)**: 股票图支持配置上涨色&下跌色
- **feat(stock)**: 股票图支持缩略轴 slider 
- **docs(stock)**: 添加股票图上涨色&下跌色配置的 demo 和文档
- **docs(tooltip)**: 完善 tooltip crosshairs 文档
- **refactor(stock)**: 增加 schema geometry adaptor & 重构股票图 tooltip（精简股票图 tooltip 配置，默认展示更优）
- **docs(stock)**: 增加若干股票图 demo
|----|----|
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/H1Rf%26M6wMO/af51e97a-7665-4591-a3f0-9c7931b15b76.png) ​|
|  ❌  |  ![](https://gw.alipayobjects.com/zos/antfincdn/UKHCDVwzFB/stock-crosshairs.png) |
=> feat: 股票图增强

docs/api/plots/sunburst.en.md, docs/api/plots/sunburst.zh.md, examples/more-plots/sunburst/demo/tooltip-fields.ts, src/plots/sunburst/types.ts, src/utils/hierarchy/partition.ts
=> feat(sunburst): 旭日图增加 ignoreParentValue 配置

__tests__/unit/plots/chord/index-spec.ts, __tests__/unit/plots/chord/tooltip-spec.ts, __tests__/unit/utils/geometry-spec.ts, examples/relation-plots/chord/demo/custom-tooltip.ts, examples/relation-plots/chord/demo/meta.json, src/index.ts, src/plots/chord/adaptor.ts, src/plots/chord/constant.ts, src/plots/chord/types.ts, src/utils/geometry.ts, src/utils/index.ts
- 【组件】tooltip 支持展示节点信息，默认不显示 & 增加自定义节点 tooltip 信息的 demo
- 【动画】支持 'wave-in'，'zoom-in'，"scale-in-x"，'scale-in-y' 等动画效果
|----|----|
|  ❌  |  ![image](https://user-images.githubusercontent.com/15646325/121766508-dbe0da80-cb84-11eb-95b1-daa90619fc0e.png) |
=> fix(chord): 和弦图支持展示节点 tooltip & 修复动画效果不生效

__tests__/bugs/issue-2636-spec.ts, src/plots/bullet/adaptor.ts
=> fix(bullet): 修复轴组件添加max时，子弹图scale呈现不正确问题

__tests__/unit/plots/scatter/data-spec.ts, __tests__/unit/plots/scatter/size-spec.ts, __tests__/unit/plots/scatter/style-spec.ts, src/plots/scatter/adaptor.ts, src/plots/scatter/index.ts, src/plots/scatter/util.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/122648019-c0b03500-d159-11eb-945f-d7763f4ba6a9.png)   单一数据点  |  ![image](https://user-images.githubusercontent.com/15646325/122648175-85623600-d15a-11eb-96ea-0e48472a5502.png) |
| ![image](https://user-images.githubusercontent.com/15646325/122648055-dc1b4000-d159-11eb-8c6d-9e0b9d5a4642.png) 等 y 轴数值 |  ![image](https://user-images.githubusercontent.com/15646325/122648170-7d09fb00-d15a-11eb-8f75-689a0bab5324.png) |
| ![image](https://user-images.githubusercontent.com/15646325/122648146-58ae1e80-d15a-11eb-9b94-9969241efe3c.png) 等 x 轴数值 |  ![image](https://user-images.githubusercontent.com/15646325/122648165-6f547580-d15a-11eb-8f98-47d0bf085785.png) |
=> fix(scatter): 散点图刷选交互之后的 scale 处理

__tests__/bugs/issue-2651-spec.ts, __tests__/unit/utils/get-meta-spec.ts, src/plots/scatter/adaptor.ts, src/plots/scatter/index.ts, src/plots/scatter/util.ts
|----|----|
|  ❌  |  ![image](https://user-images.githubusercontent.com/7856674/123607682-b0224d80-d830-11eb-8ecc-03fcb44a1be7.png)  |
=> fix(#2651): when scatter data length = 1 and x is cat

__tests__/unit/interactions/drill-down-spec.ts, __tests__/unit/plots/circle-packing/index-spec.ts, __tests__/unit/plots/treemap/interactions/drill-down-spec.ts, examples/more-plots/circle-packing/demo/meta.json, package.json, src/interactions/actions/drill-down.ts, src/plots/circle-packing/constant.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/123935542-e85b9480-d9c6-11eb-94f0-93e6a93e6531.png)  |  ![image](https://user-images.githubusercontent.com/15646325/123935600-f4dfed00-d9c6-11eb-8b75-d96bd2de0ca0.png)  |
=> feat(drill-down): 优化下下钻的面包屑位置

__tests__/unit/plots/rose/index-spec.ts, src/plots/rose/constant.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/15646325/124713807-93260280-df33-11eb-9b9c-03d5ccb418ac.png)  |  ![image](https://user-images.githubusercontent.com/15646325/124716568-cfa72d80-df36-11eb-8323-e3d4a1f9268c.png)   |
=> fix(rose): 玫瑰图 legend 默认配置，不进行 offset 偏移

__tests__/unit/plots/radial-bar/utils-spec.ts, src/plots/radial-bar/adaptor.ts, src/plots/radial-bar/types.ts, src/plots/radial-bar/utils.ts
=> fix:修复 玉珏图没有考虑isStack的情况 重新计算最大值

__tests__/unit/plots/radial-bar/index-spec.ts, __tests__/unit/plots/radial-bar/utils-spec.ts, examples/more-plots/radial-bar/demo/grouped.ts, examples/more-plots/radial-bar/demo/meta.json, examples/more-plots/radial-bar/demo/stacked.ts, src/plots/circle-packing/types.ts, src/plots/radial-bar/adaptor.ts, src/plots/radial-bar/utils.ts
ref: #2685 
**原则:** 最小化改动。既然是计算 yScale 最大值有问题，且问题出现在于处理 stack 的时候，没有根据 stack 后的数据进行计算。那就有两个方案：
1、G2 提供钩子获取 stack 处理后的数据
2、G2Plot 自己去获取 stack 后的数据（目前选择 方案2。但是比较简单滴进行处理而已，通过独立的 util 方法，具备内聚性，后续迭代优化逻辑更可控）
|----|----|
|  ❌  |  ✅  |
=> refactor: 优化下玉珏图处理 stack 的代码

__tests__/unit/plots/histogram/index-spec.ts, __tests__/unit/utils/transform/histogram-spec.ts, docs/api/plots/histogram.en.md, docs/api/plots/histogram.zh.md, docs/api/plots/sunburst.en.md, src/index.ts, src/plots/dual-axes/adaptor.ts, src/plots/histogram/adaptor.ts, src/plots/histogram/constant.ts, src/utils/transform/histogram.ts
=> fix(histogram): binNumber 设置出错

__tests__/unit/plots/pixel-plot/tooltip-spec.ts, src/pixels/components/tooltip.ts, src/pixels/constant.ts, src/pixels/index.ts, src/pixels/mock/data.ts
新增配置：
已经支持配置：
follow
offset
position
showTitle
title
fields
customContent
=> refactor(tooltip): 支持y轴crosshair以及formatter等配置，添加单测

__tests__/bugs/issue-2755-spec.ts, src/plots/sankey/adaptor.ts, src/plots/sankey/index.ts
=> fix(sankey): 修复桑基图 rawFields 在 label & tooltip 处不生效

CONTRIBUTING.md, docs/api/options/interactions.en.md, docs/api/plots/liquid.en.md, docs/common/interactions.en.md
There are small typos in:
- CONTRIBUTING.md
- docs/api/options/interactions.en.md
- docs/api/plots/liquid.en.md
- docs/common/interactions.en.md
Fixes:
- Should read `outline` rather than `ouline`.
- Should read `interactions` rather than `interacions`.
- Should read `written` rather than `wirtten`.
- Should read `reason` rather than `reasone`.
- Should read `guarantee` rather than `garantee`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

__tests__/unit/plots/dual-axes/legend-spec.ts, src/plots/dual-axes/util/legend.ts
| `修复前` |   `修复后`|
| --- | --- |
|![image](https://user-images.githubusercontent.com/65594180/128685515-8e881412-d85b-43f6-8436-1b6f4775c7c6.png)|![image](https://user-images.githubusercontent.com/65594180/128685433-7dc56bc0-82f5-4f76-ade2-f331da659a60.png)|
=>  修复:   [BUG] 双轴图图例legend使用symbol的时候，颜色不能自动调整

__tests__/bugs/issue-2783-spec.ts, src/plots/dual-axes/adaptor.ts
| Before| After|
|----|----|
| ![dualaxes-before](https://user-images.githubusercontent.com/5092842/128896564-99aac4b0-e70c-493a-a820-ea999b178859.jpg)      | ![dualaxes-after](https://user-images.githubusercontent.com/5092842/128896461-8247293d-ed2e-4c0e-9477-2fe4e67a0a29.jpg) |
=> fix(dualaxes): configure legend selected

__tests__/unit/plots/dual-axes/legend-spec.ts, __tests__/unit/utils/pattern/index-spec.ts, package.json, src/plots/dual-axes/util/legend.ts, src/types/pattern.ts, src/utils/pattern/dot.ts, src/utils/pattern/line.ts, src/utils/pattern/square.ts
=> test(pattern): 修复dot的stagger呈现问题，初步添加util中getCanvasPattern的单测

__tests__/unit/plots/word-cloud/color-spec.ts, __tests__/unit/plots/word-cloud/legend-spec.ts, src/plots/word-cloud/adaptor.ts, src/plots/word-cloud/constant.ts
=> fix: 修复词云图 legend 配置不起效 修复 词云图 color 回调缺少其他数据

__tests__/bugs/issue-2749-spec.ts, src/adaptor/geometries/base.ts
|----|----|
| <img src="https://user-images.githubusercontent.com/31396322/127994958-8b573b61-b9f6-4da6-9a50-4e8816d2f85e.png" width="375" />  |  <img src="https://user-images.githubusercontent.com/31396322/127995007-5673d7d9-c608-430d-b76c-a67e0a6a0a8a.png" width="375" />
=> fix: 修复无拆分时折线图 color 回调报错

examples/plugin/pattern/demo/bar-pattern.ts, src/utils/pattern/line.ts, src/utils/pattern/square.ts
=> fix(line-pattern): 修复linewidth>=spacing 时，绘制异常问题

docs/api/pattern.zh.md, examples/tiny/tiny-area/demo/meta.json, examples/tiny/tiny-area/demo/pattern.ts, src/plots/tiny-area/adaptor.ts
=> feat: tiny area pattern

__tests__/unit/plots/funnel/basic-spec.ts, src/plots/funnel/geometries/basic.ts
之前为了解决漏斗最下面一层文字无法对其的问题，将 label 的 layout type 设置为了 interval-adjust-position。但这样会出现 label:{position: 'right'} 失效的问题，所以在 G2 层修复了文字对齐的问题，不需要设置为 interval-adjust-position 了。
G2 的解决如下：https://github.com/antvis/G2/pull/3585
=> fix(funnel): 不将 label 的 layout 的 type 设置为 interval-adjust-position

examples/case/statistical-scenario/demo/compare-funnel.ts, examples/case/statistical-scenario/demo/meta.json, package.json
=> example(compare funnel): 添加了对比漏斗图案例

.github/workflows/build.yml, package.json
=> chore(action): change macos to ubuntu

__tests__/unit/plots/funnel/label-spec.ts, __tests__/unit/plots/venn/index-spec.ts, __tests__/unit/plots/venn/label-spec.ts, __tests__/unit/plots/venn/padding-spec.ts, examples/more-plots/venn/demo/customize.ts, package.json, src/plots/venn/adaptor.ts, src/plots/venn/constant.ts, src/plots/venn/label.ts, src/plots/venn/shape.ts, src/plots/venn/utils.ts
=> fix(label): 处理venn图label遮挡问题

docs/api/plots/gauge.en.md, docs/api/plots/pie.en.md, docs/api/plots/radar.en.md, docs/api/plots/radial-bar.en.md, docs/api/plots/rose.en.md, docs/api/plots/word-cloud.en.md, docs/api/plots/word-cloud.zh.md, docs/common/axis.en.md, docs/common/label.en.md, docs/common/label.zh.md, docs/common/statistic.en.md
In the [doc](https://g2plot.antv.vision/zh/docs/api/components/axis), type for `rotate` is number. However in example code, `rotate` is `boolean`. Indeed `rotate` does support `boolean` value, casue [`Math.sin`](https://github.com/antvis/gl-matrix/blob/master/src/gl-matrix/mat3.js#L420) will convert `boolean` to `number`. But add `boolean` for `rotate` would cause many type definition changes in numbers of reposetories
So I thinks for the time being, we can remove `rotate: true` in doc, so the user would not be confused.
=> docs: correct doc about `rotate`

__tests__/bugs/issue-1761-spec.ts, __tests__/bugs/issue-2064-spec.ts, __tests__/unit/plots/area/change-data-spec.ts, __tests__/unit/plots/area/line-spec.ts, __tests__/unit/plots/area/point-spec.ts, __tests__/unit/plots/area/tooltip-spec.ts, __tests__/unit/plots/gauge/shapes/index-spec.ts, __tests__/unit/plots/line/change-data-spec.ts, examples/line/basic/demo/custom-marker.ts, examples/line/multiple/demo/marker-active.ts, src/index.ts, src/plots/area/adaptor.ts, src/plots/area/constants.ts, src/plots/area/index.ts, src/plots/line/index.ts, src/plots/line/interactions/marker-active.ts, src/utils/geometry.ts
#3032 同折线图，如果调用底层 api，获取 point Geometry，需要更新用法：
```ts
// 旧用法
- const pointGeometry = view.geometries.filter((geom) => geom.type === 'point');
// 新用法
+ import { Util } from '@antv/g2plot';
+
+ const pointGeometry = Util.findGeometry(line.chart, 'point');
```
=> refactor(area): 优化面积图渲染耗时, point 几何图形绘制在单独的 view 上，空数据不渲染

__tests__/unit/plots/area/state-spec.ts, docs/api/plots/area.en.md, docs/api/plots/area.zh.md, src/plots/area/adaptor.ts, src/plots/area/types.ts, src/plots/line/adaptor.ts, src/plots/line/types.ts
demo: https://codesandbox.io/s/area-plot-state-lvvmk?file=/index.ts
|----|----|
|![image](https://user-images.githubusercontent.com/15646325/147521982-2cb0372e-9836-43fe-8526-13808b5eb255.png) |  ![image](https://user-images.githubusercontent.com/15646325/147521983-9bfc477b-f346-4eef-8003-15d7b48f7d39.png) |
=> feat(area): 面积图支持line独立设置state，避免填充颜色出现问题

__tests__/unit/plots/sankey/interations-spec.ts, docs/api/plots/sankey.en.md, docs/api/plots/sankey.zh.md, src/plots/sankey/adaptor.ts, src/plots/sankey/types.ts
=> feat(sankey): 分别对 node 和 edge 添加 交互属性配置

__tests__/bugs/issue-3084-spec.ts, docs/api/plot-api.en.md, docs/api/plot-api.zh.md, src/core/plot.ts
|----|----|
| <img width="696" alt="iShot2022-02-14 15 13 07" src="https://user-images.githubusercontent.com/36756846/153829289-59aadc0a-1065-491f-a7af-00d3eae20a28.png">|  <img width="956" alt="iShot2022-02-14 16 42 46" src="https://user-images.githubusercontent.com/36756846/153829501-d3af8a88-8099-4c85-9387-82da60ef24af.png">  |
=> fix(annotations): 修复addAnnotations在双轴图等具有分view图表失效的问题

examples/case/statistical-scenario/demo/conversion-funnel.ts, src/index.ts, src/plots/liquid/index.ts, src/plots/liquid/shapes/liquid.ts
=> feat(consionBar): 转化分析图 + 水波图

CHANGELOG.md, __tests__/unit/plots/sankey/index-spec.ts, package.json, src/index.ts, src/plots/sankey/layout.ts
```ts
import { Sankey } from '@antv/g2plot';
const DATA = [
{ source: '首次打开', target: '首页 UV', value: 160 },
{ source: '结果页', target: '首页 UV', value: 40 },
{ source: '验证页', target: '首页 UV', value: 10 },
{ source: '我的', target: '首页 UV', value: 10 },
{ source: '朋友', target: '首页 UV', value: 8 },
{ source: null, target: '首页 UV', value: 27 },
{ source: '首页 UV', target: '理财', value: 30 },
{ source: '首页 UV', target: '扫一扫', value: 40 },
{ source: '首页 UV', target: '服务', value: 35 },
{ source: '首页 UV', target: '蚂蚁森林', value: 25 },
{ source: '首页 UV', target: '跳失', value: 10 },
{ source: '首页 UV', target: '借呗', value: 30 },
{ source: '首页 UV', target: '花呗', value: 40 },
{ source: '首页 UV', target: null, value: 45 },
];
const sankey = new Sankey('container', {
data: DATA,
sourceField: 'source', …
```
=> feat(sankey): support `null` to represent loss.

CHANGELOG.md, __tests__/bugs/pie-statistic-spec.ts, package.json, src/index.ts, src/plots/pie/adaptor.ts
=> fix(pie): 修复饼图 title statistic 没有使用 meta formatter

__tests__/unit/plots/bullet/data-spec.ts, src/plots/bullet/utils.ts
| --- | --- |
| 更改前 range 和 measures 只能传入数组，不然报错 ，target 的颜色color 不起作用  |更改后 range 和 measures 支持单个数值， target 的颜色配置起效果 |
|  ![image](https://user-images.githubusercontent.com/65594180/171344506-f548a496-b49b-44a9-af17-d67a66ae5545.png)  |  ![image](https://user-images.githubusercontent.com/65594180/171345974-2f677dfa-7ce6-4774-85aa-a8fe04d2aab1.png) |
=> fix(bullet): 子弹图 添加单数值range/measures 、 多 target 数据修改兼容

__tests__/bugs/issue-3200-spec.ts, src/plots/chord/constant.ts
| --- | --- |
| ![image](https://user-images.githubusercontent.com/65594180/177732561-13f2e879-d8cf-4958-8bed-7ff9427c6560.png) |  ![image](https://user-images.githubusercontent.com/65594180/177732758-5722edca-d116-4148-90fe-c972cd56c340.png)|
fixed #3200
=> fix(Chord): 修复弦图label 样式不能修改的问题

src/plots/heatmap/adaptor.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/65594180/177946162-bba2fa5a-dd8e-44fe-85f0-85ed666af52a.png)|  ![image](https://user-images.githubusercontent.com/65594180/177945712-d17e7b43-e4c8-4d33-b9c0-7e419d6c4d03.png)|
fixed #3170
=> fix(heatmap): 添加 meta 中的最大最小值参数 可以控制最小显示参数

__tests__/bugs/issue-3262-spec.ts, __tests__/unit/plots/gauge/utils-spec.ts, src/plots/gauge/utils.ts
仪表盘 percent 0 时，数据被过滤. 导致 geometry 渲染第一个 range  直接为 1 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/65594180/175933713-9b2b8165-9a8b-4a48-92d8-f419c06cdff5.png)|  ![image](https://user-images.githubusercontent.com/65594180/175933767-ee1bad82-8aea-4120-ac8b-3bfc852d6e17.png) |
fixed #3262
=> fix(gauge): 仪表盘 percent 0 时，数据被过滤重新添加回来

__tests__/unit/plots/heatmap/coordinate-spec.ts, src/plots/heatmap/adaptor.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/65594180/180410159-e7b94076-59e4-4b53-bf74-e46f128b19d7.png)|  ![image.png](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9e64759c661749bd9a2f33b8ab464ddb~tplv-k3u1fbpfcp-watermark.image?) |
=> fix(heatmap): 修复色力图 coordinate部分配置不起效 和 配置了 refect coordinate 失效的问题

src/adaptor/geometries/base.ts, src/types/common.ts
-[x] rawFields 添加回调，对 geometry color shape 进行了区分 (和 G2 一样进行了区分)
|----|----|
| 原先 rawFields 对 line 和 point 等统一加的分组  |  回调后可以对 line 和 point 等进行区分分组 |
| 原先 rawFields 对 color 和 shape 等统一加的分组  |  回调后可以对 color 和 shape 等进行区分分组 |
可以对 point 区分 并且不改变 line 的分组
fixed #3287
=> fix(base): rawFields 添加回调，对 geometry color shape 进行了区分

__tests__/unit/plots/facet/animation-spec.ts, __tests__/unit/plots/line/animation-spec.ts, __tests__/unit/plots/sankey/animation-spec.ts, src/adaptor/common.ts, src/plots/chord/adaptor.ts, src/plots/facet/types.ts, src/plots/facet/utils.ts, src/plots/sankey/adaptor.ts, src/plots/violin/adaptor.ts, src/types/common.ts, src/utils/index.ts, src/utils/view.ts
包含所有图表， 外加 特殊 图表 分面图、小提琴图、桑基图
Screenshot
|----|----|
|  每一个形状都是一个动画， 并且 同时存在 point 点形状 和 'path' 动画 点时候，报错并渲染失败  ![image](https://user-images.githubusercontent.com/65594180/178224292-39b4c105-b538-48a7-adec-cb2d2704e46d.png) |  添加更多的动画 ![image](https://user-images.githubusercontent.com/65594180/178224685-8ca8bb07-2453-403a-86c5-48ac04bb58c3.png) | 
| | ![image](https://user-images.githubusercontent.com/65594180/178224716-40fb9347-2666-45e1-ab71-12bc48176bf0.png) |
=> fix(animation):  动画添加回调， 可以给不同的 形状添加动画

docs/api/options/shape.en.md, docs/api/options/shape.zh.md, examples/plugin/custom-shape/demo/bar-custom-shape.ts, examples/plugin/custom-shape/demo/conversion-bar-shape.ts, examples/plugin/custom-shape/demo/meta.json, examples/plugin/custom-shape/demo/pie-custom-shape.ts, examples/plugin/custom-shape/index.en.md, examples/plugin/custom-shape/index.zh.md, src/plots/pie/adaptor.ts, src/plots/pie/types.ts
=>  feat(custom Shape): 添加 Shape 文档 以及 添加 三个 自定义 Shape demo

package.json
remark-mdx 新版本采用 ESM 方式引入。锁定旧版本可以解决问题。
参考：https://github.com/doczjs/docz/issues/1674
=> fix: 锁 remark-mdx 版本修复启动报错

__tests__/unit/plots/funnel/compare-spec.ts, src/plots/funnel/adaptor.ts, src/plots/funnel/geometries/basic.ts, src/plots/funnel/geometries/common.ts, src/plots/funnel/geometries/compare.ts, src/plots/funnel/index.ts, src/plots/funnel/interactions/funnel-conversion-tag.ts, src/plots/funnel/interactions/index.ts, src/plots/funnel/types.ts
fixed #3350 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/65594180/190343659-e3f29a51-2632-47cd-9e6f-5dd68cc9c3d7.png)| ![image](https://user-images.githubusercontent.com/65594180/190343565-12fb193a-209d-4f2c-a680-27b32e10f5da.png)  ![image](https://user-images.githubusercontent.com/65594180/190581428-c2b4782e-288f-4437-920a-0122353266a4.png)|
=> fix(funnel): 漏斗图转化率文本位置获取修改

docs/api/plots/liquid.en.md, docs/api/plots/liquid.zh.md, examples/progress-plots/liquid/demo/custom.ts, examples/progress-plots/liquid/demo/meta.json, src/plots/liquid/adaptor.ts, src/plots/liquid/shapes/liquid.ts, src/plots/liquid/types.ts
- My business scenario with shape background and without outline:
- `shapeStyle` is for shape background:
|----|----|
| ![image](https://user-images.githubusercontent.com/14918822/204965663-64729192-6ed3-4a83-9c41-184ca29f56e8.png) | ![image](https://user-images.githubusercontent.com/14918822/204965467-ebd9f2cf-cabd-4765-8935-f8e9d46582b9.png) |
- wave count is 1:
|----|----|
| ![image](https://user-images.githubusercontent.com/14918822/205021774-23cab97a-2cd8-482b-aa6f-d9b243f3ae11.png) | ![image](https://user-images.githubusercontent.com/14918822/205021161-0862d216-264d-42dc-8792-4ba346008feb.png) |
=> feat(Liquid): Add shapeStyle config

src/utils/transform/word-cloud.ts
使用词云图时，若更新数据或者更改图表的尺寸会触发浏览器警告:
```
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: <URL>
```
在 `canvas.getContext` 时，增加这个配置可以避免这个警告，优化部分性能。
=> perf(word-cloud):  add willReadFrequently option when canvas getContext

src/plots/liquid/adaptor.ts, src/plots/liquid/shapes/liquid.ts, src/plots/liquid/types.ts
|----|----|
|  ![image](https://user-images.githubusercontent.com/14918822/216010075-6d5112e1-e520-4c84-af45-6efbd8f60ecb.png) |  ![image](https://user-images.githubusercontent.com/14918822/216009658-cadce0c6-4507-4b83-b892-6d143de337e7.png)  |
| ![image](https://user-images.githubusercontent.com/14918822/216010172-00f32296-de59-4f77-b067-9773c4fe503d.png) | ![image](https://user-images.githubusercontent.com/14918822/216009893-3948d697-22a9-4d96-85ed-e66ec7415d1e.png) |
=> fix(Liquid): should render wave only when percent > 0

__tests__/unit/plots/sankey/adaptor-spec.ts, src/plots/sankey/adaptor.ts
- fix the bug that the the callback function `edgeStyle` has no sufficient parameters
Before:
Only the parameters of `name`, `x` and `y` are passed into the callback function `edgeStyle`. The value of `name` is the name of the source node. Users cannot get the name of the target node while using `edgeStyle`. The `rawFields` does not affect.
After:
The parameters of `source` and `target` are passed into the callback function `edgeStyle`. Users can get the name of the target node from `target`. The `rawFields` takes effect.
=> fix(Sankey): insufficient pass-in parameters for the callback function of edgeStyle

__tests__/unit/plots/scatter/regression-line-spec.ts, __tests__/unit/plots/scatter/util-spec.ts, site/docs/api/plots/scatter.en.md, site/docs/api/plots/scatter.zh.md, src/plots/scatter/adaptor.ts, src/plots/scatter/types.ts, src/plots/scatter/util.ts
|----|----|
|  ![antv-g2plot-regression-old](https://user-images.githubusercontent.com/4497555/220839781-325894ad-7203-4f4c-94e8-ebdbff2c7885.png) |  ![antv-regression-equation-snapshot](https://user-images.githubusercontent.com/4497555/220809373-c6517a7b-9b78-4180-abe8-19e9a7c14201.png)  |
=> (feat) 回归散点图增加显示回归拟合函数相关配置，close #3474

src/plots/column/adaptor.ts
在百分比柱状图中，如果y中拆分字段是空字符串，显示就有问题，错误的使用了 xField 作为title:
|----|----|
|  ![image](https://user-images.githubusercontent.com/17964556/224649270-3c9b7c89-e20d-46c1-b77f-1bd53ce14fd4.png)  |  ![image](https://user-images.githubusercontent.com/17964556/224648597-9caf0499-2c3e-4659-a8c1-e52d63e7081b.png)  |
=> fix(column): 修复柱状图拆分维度为空字符串时，错误显示了 xField 作为 title 的问题

CHANGELOG.md, package.json
应为线上版本和 package.json 的不一致，导致上一个 [PR](https://github.com/antvis/G2Plot/pull/3511) 更新版本号错误，这个 PR 修复问题。
=> chore: update version to 2.4.29

CHANGELOG.md, package.json, src/index.ts
发上一个版本的时候本地 node_modules 安装了错误的 component 0.8.32 版本，导致 dist 相应的修改没有生效。准备更新本地依赖之后，重新发布一次。
=> chore: update version of @antv/component to 0.8.33 for dist build

.github/workflows/build.yml, CHANGELOG.md, __tests__/bugs/issue-3804-spec.ts, package.json, src/adaptor/geometries/line.ts, src/index.ts, src/plots/area/adaptor.ts, src/plots/line/adaptor.ts, src/plots/radar/adaptor.ts
=> fix: line,area,radar label style with callback

__tests__/unit/utils/pattern/line-spec.ts, src/plots/dual-axes/util/render-sider.ts
g2 代码里取值用的 Math.round，而 G2Plot 这边用的 Math.floor，导致双轴缩略不同步
|----|----|
|![image](https://github.com/user-attachments/assets/1b661bf9-af69-436c-84fd-968b75d910d3) |   ![image](https://github.com/user-attachments/assets/cd39ee0e-c232-48d9-ae52-956392b7dd58)
=> fix: thumbnail of dual-axes are out of sync

src/adaptor/geometries/base.ts
=> Fix: add custom mapping field

CHANGELOG.md, package.json, src/index.ts
=> chore: 更新版本
